unoplatform/uno.extensions

samples/Commerce/UWP/Commerce.Droid/Commerce.Droid.csproj
samples/Commerce/UWP/Commerce.Skia.Gtk/Commerce.Skia.Gtk.csproj
samples/Commerce/UWP/Commerce.Skia.WPF/Commerce.Skia.WPF.csproj
samples/Commerce/UWP/Commerce.UWP/Commerce.Uwp.csproj
samples/Commerce/UWP/Commerce.Wasm/Commerce.Wasm.csproj
samples/Commerce/UWP/Commerce.iOS/Commerce.iOS.csproj
samples/Commerce/UWP/Commerce.macOS/Commerce.macOS.csproj
samples/Commerce/WinUI/Commerce.Droid/Commerce.Droid.csproj
samples/Commerce/WinUI/Commerce.iOS/Commerce.iOS.csproj
samples/Commerce/WinUI/Commerce.macOS/Commerce.macOS.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Droid/MyExtensionsApp.Droid.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows.Desktop/MyExtensionsApp.Windows.Desktop.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.iOS/MyExtensionsApp.iOS.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.macOS/MyExtensionsApp.macOS.csproj
src/extensions/ExtensionsSampleApp/ExtensionsSampleApp.UWP/ExtensionsSampleApp.UWP.csproj

- Bugfix
Some Material styles are not taken into account on some platforms
Add missing Uno.Toolkit.UI.Material and Uno.Toolkit.WinUI.Material references in order to fix that.

fix: Add missing Uno.Toolkit.UI/WinUI.Material references

---

samples/Commerce/Commerce.Shared/App.xaml
samples/Commerce/UWP/Commerce.Droid/Commerce.Droid.csproj
samples/Commerce/UWP/Commerce.Skia.Gtk/Commerce.Skia.Gtk.csproj
samples/Commerce/UWP/Commerce.Skia.WPF/Commerce.Skia.WPF.csproj
samples/Commerce/UWP/Commerce.UWP/Commerce.Uwp.csproj
samples/Commerce/UWP/Commerce.Wasm/Commerce.Wasm.csproj
samples/Commerce/UWP/Commerce.iOS/Commerce.iOS.csproj
samples/Commerce/UWP/Commerce.macOS/Commerce.macOS.csproj
samples/Commerce/WinUI/Commerce.Droid/Commerce.Droid.csproj
samples/Commerce/WinUI/Commerce.Skia.Gtk/Commerce.Skia.Gtk.csproj
samples/Commerce/WinUI/Commerce.Skia.WPF/Commerce.Skia.WPF.csproj
samples/Commerce/WinUI/Commerce.Wasm/Commerce.Wasm.csproj
samples/Commerce/WinUI/Commerce.Windows.Desktop/Commerce.Windows.Desktop.csproj
samples/Commerce/WinUI/Commerce.iOS/Commerce.iOS.csproj
samples/Commerce/WinUI/Commerce.macOS/Commerce.macOS.csproj
src/Uno.Extensions.Navigation.Toolkit/Uno.Extensions.Navigation.Toolkit.UI.csproj
src/Uno.Extensions.Navigation.Toolkit/Uno.Extensions.Navigation.Toolkit.WinUI.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Droid/MyExtensionsApp.Droid.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows.Desktop/MyExtensionsApp.Windows.Desktop.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.iOS/MyExtensionsApp.iOS.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.macOS/MyExtensionsApp.macOS.csproj
src/extensions/ExtensionsSampleApp/ExtensionsSampleApp.UWP/ExtensionsSampleApp.UWP.csproj

GitHub Issue (If applicable): #199 
- Bugfix
ToggleSwitch is not taking the correct Material Style for Wasm and Skia
ToggleSwitch is taking the correct Material Style for Wasm and Skia

fix: Remove ToogleSwitch workaround for wasm/skia as it's not needed anymore with latest Uno.Material

---

samples/Commerce/Commerce.Shared/Views/CartPage.xaml
samples/Commerce/Commerce.Shared/Views/DealsPage.xaml
samples/Commerce/Commerce.Shared/Views/ProductDetailsPage.xaml
samples/Commerce/Commerce.Shared/Views/ProductsPage.xaml
src/extensions/ExtensionsSampleApp/ExtensionsSampleApp.Shared/UnoCommerce/DealsPage.xaml
src/extensions/ExtensionsSampleApp/ExtensionsSampleApp.Shared/UnoCommerce/ProductDetailsPage.xaml

GitHub Issue (If applicable): #201 
- Bugfix
Images don't have the correct Stretch (UniformToFill)
Images use the correct Stretch for the wanted design (Uniform)

fix: Change Image Stretch UniformToFill to Uniform in order to match latest Uno Figma plugin changes (PR #321)

---

samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Playground.Shared.projitems
samples/Playground/Playground/Playground/Playground.Shared/Playground.Shared.shproj
samples/Playground/Playground/Playground/Playground.Shared/Views/AlternatePage.xaml
samples/Playground/Playground/Playground/Playground.Shared/Views/AlternatePage.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/MainPage.xaml
samples/Playground/Playground/Playground/Playground.Shared/Views/MainPage.xaml.cs
src/Uno.Extensions.Navigation.UI/DependencyObjectExtensions.cs
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
src/Uno.Extensions.Navigation.UI/IRouteNotifier.cs
src/Uno.Extensions.Navigation.UI/IRouteUpdater.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
src/Uno.Extensions.Navigation.UI/Region.cs
src/Uno.Extensions.Navigation.UI/Regions/NavigationRegion.cs
src/Uno.Extensions.Navigation.UI/RouteChangedEventArgs.cs
src/Uno.Extensions.Navigation.UI/RouteExtensions.cs
src/Uno.Extensions.Navigation.UI/RouteNotifier.cs
src/Uno.Extensions.Navigation.UI/RouteResolver.cs
src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs
src/Uno.Extensions.Navigation/Route.cs
src/Uno.Extensions.Navigation/Schemes.cs

GitHub Issue (If applicable): #275 
- Feature
- 
Navigation is setup in app.xaml.cs using the NavigationHost method to define the root element of the application.
The NavigationHost method is still supported. However, it's now possible to attach navigation to any page by adding a ContentControl and setting the Region.Host property eg
```csharp
<ContentControl uen:Region.Host="Shell" />
```
The string is the name of the route to load by default. The Host property can be set to "" in order to use the first route in the routemap table.

feat: Detach Navigation from App Startup

---

samples/Commerce/Commerce.Shared/App.xaml.cs
samples/Commerce/UWP/Commerce.Wasm/LinkerConfig.xml
samples/Commerce/WinUI/Commerce.Wasm/LinkerConfig.xml
src/Uno.Extensions.Hosting.UI/AppHostingEnvironment.cs
src/Uno.Extensions.Hosting.UI/GlobalUsings.cs
src/Uno.Extensions.Hosting.UI/UnoHost.cs
src/Uno.Extensions.Hosting/IHasAddressBar.cs
src/Uno.Extensions.Navigation.UI/BrowserAddressBarService.cs
src/Uno.Extensions.Navigation.UI/HostBuilderExtensions.cs
src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs
src/Uno.Extensions.Navigation/NavigationConfig.cs
src/Uno.Extensions.Templates/content/unoapp-extensions-net6/MyExtensionsApp.Wasm/LinkerConfig.xml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/App.xaml.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/LinkerConfig.xml

GitHub Issue (If applicable): #318
LinkerConfig file for extensions template wasn't picking up the netstandard class library that was added for viewmodels, services etc
LinkerConfig includes the netstandard library
Also, removed excess linkerconfig assemblies from commerce sample

chore: Trimming/Updating LinkerConfig for commerce app and templates 

---

samples/Commerce/Commerce.Shared/App.xaml.cs
src/Uno.Extensions.Hosting.UI/AppHostingEnvironment.cs
src/Uno.Extensions.Hosting.UI/GlobalUsings.cs
src/Uno.Extensions.Hosting.UI/UnoHost.cs
src/Uno.Extensions.Hosting/IHasAddressBar.cs
src/Uno.Extensions.Navigation.UI/BrowserAddressBarService.cs
src/Uno.Extensions.Navigation.UI/HostBuilderExtensions.cs
src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs
src/Uno.Extensions.Navigation/NavigationConfig.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/App.xaml.cs

GitHub Issue (If applicable): #262
- Feature
Currently consuming application has to get a reference to the IRouteNotifier and use that to update the browser address bar
This change adds a new browser address bar service, so that the RouteChanged event can be subscribed to once the application has started. 
The hosting environment implements IHasAddressBar on WASM, and the implementation allows the address bar to be upaded.

feat: Adding address bar updating to Navigation 

---

samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Playground.Shared.projitems
samples/Playground/Playground/Playground/Playground.Shared/Playground.Shared.shproj
samples/Playground/Playground/Playground/Playground.Shared/Views/BasicFlyout.xaml
samples/Playground/Playground/Playground/Playground.Shared/Views/BasicFlyout.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml
samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml.cs
src/Uno.Extensions.Navigation.UI/DispatcherQueueExtensions.cs
src/Uno.Extensions.Navigation.UI/DispatcherQueueHelpers.cs
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs

GitHub Issue (If applicable): #323
- Bugfix
Launching flyout from background thread (eg from a reactive command) causes exception when child navigators are created 
Flyouts use the Window.DispatcherQueue and child navigation switches to UI thread to retrieve the region navigators

fix: Wrapping UI related actions with dispatcher

---

samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml.cs
src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs

GitHub Issue (If applicable): #368
- Bugfix
Tap outside of flyout doesn't return result to navigation
Tap outside of flyout returns a "None" result to navigation

fix: Attaching event handler to closed event so that navigation returns correctly

---

src/Uno.Extensions.Reactive.UI/GlobalUsings.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.CollectionView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/CollectionChangedFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/FlatCollectionChangedFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/SelectionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/BasicView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/FlatView.cs
src/Uno.Extensions.Reactive.UI/_Compat/EventRegistrationToken.cs
src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs

Fix type load issue of evtRegToken on Win-WinUI
On Windows - WinUI, BindableCollection fails due to a type load exception of the EvtRegTokenTable missing
🙃

fix: Fix type load issue of evtRegToken on Win-WinUI

---

src/Uno.Extensions.Reactive.Tests/Operators/Given_FeedToListFeedAdapter.cs
src/Uno.Extensions.Reactive/Core/ListFeed.Extensions.cs
src/Uno.Extensions.Reactive/Operators/FeedToListFeedAdapter.cs

Make sure to go in None state if source is null or empty
If source feed produces a `Some(null)` or `Some(Empty)`, the  `ListFeed` stays in `Some` 
When source feed produces a `Some(null)` or `Some(Empty)`, the `FeedToListFeedAdapter` converts its to a `None`

fix: Make sure to go in None state if source is null or empty

---

samples/Playground/Playground/Playground/Playground.Shared/Views/NavigationViewPage.xaml
src/Uno.Extensions.Navigation.UI/Controls/ActionRequestHandlerBase.cs

- Bugfix
Exception is raised when the Binding path for the Navigation Data attached property is null
Null reference is correctly handled

fix: Null ref when no binding path

---

samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/NavContentPage.xaml
src/Uno.Extensions.Navigation.UI/Navigator.cs

- Bugfix
Navigating to tabs within a navigation view item causes infinite loop due to responsenavigator not being cleared
Responsenavigator is cleared before navigating to tabs

fix: Overflow when navigating to nested regions

---

src/Uno.Extensions.Logging/Uno.Extensions.Logging.UWP.csproj
src/Uno.Extensions.Logging/Uno.Extensions.Logging.WinUI.csproj

- Bugfix
Logging in wasm wasn't working because the uno-runtime specific libraries weren't being included in the Logging.UWP and Logging.WinUI packaged
Referencing Uno.UI and Uno.WinUI fixes the issue as the uno-runtimes folder is created and populated as part of creating the nuget package

fix: Wasm logging not working

---

samples/Playground/Playground/Playground/Playground.Shared/App.xaml.host.cs
samples/Playground/Playground/Playground/Playground.Shared/Strings/en/Resources.resw
samples/Playground/Playground/Playground/Playground.Shared/Strings/fr/Resources.resw
samples/Playground/Playground/Playground/Playground.Shared/ViewModels/HomeViewModel.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml
samples/Playground/Playground/Playground/Playground.Shared/appsettings.development.json
samples/Playground/Playground/Playground/Playground.Shared/appsettings.json
src/Uno.Extensions.Localization/LocalizationService.cs
src/Uno.Extensions.Localization/LocalizationSettingsExtensions.cs
src/Uno.Extensions.Localization/Uno.Extensions.Localization.csproj
src/Uno.Extensions.Navigation.UI/GlobalUsings.cs
src/Uno.Extensions.Navigation.UI/MessageDialogViewMap.cs
src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
src/Uno.Extensions.Navigation.UI/common.props
src/Uno.Extensions.Navigation/GlobalUsings.cs
src/Uno.Extensions.Navigation/Uno.Extensions.Navigation.csproj
src/Uno.Extensions.Navigation/ViewMap.cs

- Feature
Unable to localize strings used in messagedialog with navigation
Added LocalizableMessageDialogViewMap

feat: Adding support for localizing message dialog

---

src/Uno.Extensions.Serialization/ServiceCollectionExtensions.cs

GitHub Issue (If applicable): #407
- Bugfix
null values are written when serializing object to json
null values are ignored

fix: Ignoring null values when serializing json

---

samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml
src/Uno.Extensions.Navigation.UI/NavigatorExtensions.cs
src/Uno.Extensions.Navigation.UI/RouteResolver.cs
src/Uno.Extensions.Navigation/NavigationRequestExtensions.cs
src/Uno.Extensions.Navigation/NavigatorExtensions.cs
src/Uno.Extensions.Navigation/RouteExtensions.cs
src/Uno.Extensions.Navigation/RouteInfo.cs

- Feature
Navigation request has to include the dialog qualifier ! for messagedialog, contentdialog and flyout
Qualifier can be omitted for known view types (eg MessageDialog, ContentDialog and Flyout)

feat: Applying dialog qualifier for appropriate view types

---

src/Uno.Extensions.Logging/HostBuilderExtensions.cs

- Bugfix
Remove the default nullable for Action<ILoggingBuilder> parameter to avoid ambiguous call for HostBuilderExtensions.UseLogging methods

fix: Remove the default nullable for Action<ILoggingBuilder> parameter to avoid ambiguous call for HostBuilderExtensions.UseLogging methods

---

samples/Playground/Playground/Playground/Playground.Shared/App.xaml.host.cs
samples/Playground/Playground/Playground/Playground.Shared/ViewModels/HomeViewModel.cs
samples/Playground/Playground/Playground/Playground.Shared/ViewModels/VMViewModel.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/CodeBehindPage.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/FlyoutsPopupsDrawerPage.xaml.cs
src/Uno.Extensions.Localization/LocalizationService.cs
src/Uno.Extensions.Localization/LocalizationSettingsExtensions.cs
src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
src/Uno.Extensions.Navigation/NavigationResponse.cs
src/Uno.Extensions.Navigation/NavigationResponseExtensions.cs
src/Uno.Extensions.Navigation/NavigatorExtensions.cs

…ole dialogresult
- Feature
ShowMessageDialogAsync returns a DialogAction
ShowMessageDialogAsync returns the DialogAction.Id (or Label if Id not provided) and can be cast to the appropriate entity type - cleans up using messagedialog to get a result

feat: Adjusting messagedialog to return dialogresult.Id instead of whole DialogResult

---

samples/Playground/Playground/Playground/Playground.Shared/ViewModels/VMViewModel.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/CodeBehindPage.xaml.cs
samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml
samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml.cs
src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
src/Uno.Extensions.Navigation/NavigatorExtensions.cs

- Feature
ShowMessageDialogAsync required the AsResult extension and then SomeOrDefault just to get the returned value
GetDataAsync doesn't support specifying a route string
ShowMessageDialogAsync returns the selected value
GetDataAsync has an overload that takes a route string

feat: Simplifying messagedialog and extending GetDataAsync

---

src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.UI.WinUI.csproj

Fix packaging of the template of the FeedView on Windows
The `FeedView` does not have a default template on windows
It does

fix(feed): Fix packaging of the template of the FeedView on Windows

---

src/Uno.Extensions.Navigation.UI/Controls/NavigationViewRequestHandler.cs

GitHub Issue (If applicable): #475
- Bugfix
Navigation is trigged on selectionchanged even when selecteditem is null
Navigation only triggered when selecteditem is not null
Also, navigation is triggered on bind if selecteditem is not null (default selection)

fix: Only navigate if data (ie selected item) is not null

---

src/Uno.Extensions.Reactive.Tests/Operators/Given_CombineFeed.cs
src/Uno.Extensions.Reactive.UI/GlobalUsings.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/CollectionChangedFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/SelectionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/BasicView.cs
src/Uno.Extensions.Reactive.UI/_Compat/EventRegistrationToken.cs
src/Uno.Extensions.Reactive.UI/common.props

Fix `TypeLoadException` in ToDo app
We can get a `TypeLoadException` when using the reactive.WinUI packages as we tried to rely on framework's  `EventRegsitrationTokenTable` which might be missing on some runtime.
We use our own implementation everywhere except UWP

fix(feed): Use our own EvtRegToken for all platforms where it's possible

---

src/Uno.Extensions.Localization/LocalizationSettings.cs

Fix issue with ToDo app where LocalizationSettings can't be set due to set_CurrentCulture method not found exception

fix: Changing CurrentCulture to use set instead of init

---

src/Uno.Extensions.Reactive.Tests/Core/Given_CompositeRequestSource.cs
src/Uno.Extensions.Reactive.Tests/Core/Given_NoneRequestSource.cs
src/Uno.Extensions.Reactive.Tests/Core/Given_RequestSource.cs
src/Uno.Extensions.Reactive.Tests/Core/TestRequest.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableViewModelBase.cs
src/Uno.Extensions.Reactive/AssemblyInfo.cs
src/Uno.Extensions.Reactive/Core/Axes/MessageAxisExtensions.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/IContextRequest.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/IRequestSource.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSource.Composite.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSource.None.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSource.cs
src/Uno.Extensions.Reactive/Core/IMessageBuilder.cs
src/Uno.Extensions.Reactive/Core/Internal/FeedHelper.cs
src/Uno.Extensions.Reactive/Core/Internal/IStateStore.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageAxisUpdate.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.CurrentMessage.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.UpdateTransaction.Message.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.UpdateTransaction.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.cs
src/Uno.Extensions.Reactive/Core/Internal/SourceContext.cs
src/Uno.Extensions.Reactive/Core/Internal/StateImpl.cs
src/Uno.Extensions.Reactive/Core/Internal/StateStore.None.cs
src/Uno.Extensions.Reactive/Core/Internal/StateStore.cs
src/Uno.Extensions.Reactive/Core/MessageBuilder.TParent.cs
src/Uno.Extensions.Reactive/Core/MessageBuilder.cs
src/Uno.Extensions.Reactive/Operators/SelectAsyncFeed.cs
src/Uno.Extensions.Reactive/Sources/AsyncFeed.cs

Base work for https://github.com/unoplatform/uno.extensions/issues/410 and https://github.com/unoplatform/uno.extensions/issues/372
Create a "control/command channel" from the view to the source feed.
View only consume the data coming from the business sources
Consumer is now able to send request to the feeds that it is subscribed to

feat(feeds): Add ability for a SourceContext to send reqests to feeds subscribed using that context

---

samples/Playground/Playground/Playground/Playground.Shared/App.xaml.host.cs
src/Uno.Extensions.Http/ServiceCollectionExtensions.cs

GitHub Issue (If applicable): #N/A
- Feature
Only a single httphandler can be added as an innerhandler
Multiple levels of innerhandlers can be set

feat: Allowing for httphandler chaining

---

src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.Immutable.cs
src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.ImmutableNonIList.cs
src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.List.cs
src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.ListOfT.cs
src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.Utils.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.Change.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.ChangesBuffer.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.ListRef.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.SourceEnumerator.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.T.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Add.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Move.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Remove.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.cs
src/Uno.Extensions.Reactive/Operators/FeedToListFeedAdapter.cs
src/Uno.Extensions.Reactive/Operators/WhereListFeed.cs
src/Uno.Extensions.Reactive/Utils/ListExtensions.cs

related to https://github.com/unoplatform/uno.extensions/issues/372
Make the CollectionAnalyzer trully generic and fix support of ImmutableList<T> which are not IList

Make the CollectionAnalyzer trully generic and fix support of ImmutableList<T> which are not IList

---

src/Uno.Extensions.Reactive.Testing/ConstraintParts/Changed.cs
src/Uno.Extensions.Reactive.Testing/ConstraintParts/Items.cs
src/Uno.Extensions.Reactive.Testing/ConstraintParts/ItemsChanged.cs
src/Uno.Extensions.Reactive.Testing/ConstraintParts/Pagination.cs
src/Uno.Extensions.Reactive.Testing/Fluent/FluentAssertionExtensions.cs
src/Uno.Extensions.Reactive.Tests/Sources/Given_PaginatedListFeed.cs
src/Uno.Extensions.Reactive/Core/Axes/MessageAxes.cs
src/Uno.Extensions.Reactive/Core/Axes/MessageAxis.cs
src/Uno.Extensions.Reactive/Core/Axes/MessageAxisExtensions.cs
src/Uno.Extensions.Reactive/Core/Axes/PaginationInfo.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/CoercingRequestManager.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/IPaginatedSource.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/PageRequest.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/PageToken.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSourceExtensions.cs
src/Uno.Extensions.Reactive/Core/ContextRequests/SequentialRequestManager.cs
src/Uno.Extensions.Reactive/Core/ListFeed.T.cs
src/Uno.Extensions.Reactive/Core/ListFeed.cs
src/Uno.Extensions.Reactive/Sources/Page.cs
src/Uno.Extensions.Reactive/Sources/PageInfo.cs
src/Uno.Extensions.Reactive/Sources/PaginatedListFeed.cs

related to https://github.com/unoplatform/uno.extensions/issues/372
Add PaginatedListFeed
Pagination has to be handle at app level
We now have ability to declare de paginated ListFeed using `ListFeed.Paginated(GetPage)`

Add PaginatedListFeed

---

src/Uno.Extensions.Reactive.Tests/Sources/Given_PaginatedListFeed.cs
src/Uno.Extensions.Reactive/Core/Axes/PaginationInfo.cs
src/Uno.Extensions.Reactive/Core/ListFeed.T.cs
src/Uno.Extensions.Reactive/Core/ListFeed.cs
src/Uno.Extensions.Reactive/Sources/PageRequest.cs
src/Uno.Extensions.Reactive/Sources/PaginatedListFeed.cs

related to #372 
Rename Page to PageRequest to avoid name clash with Xaml.Page + Rename TotalCount to CurrentCount

refactor(feeds): Rename Page to PageRequest to avoid name clash

---

src/Uno.Extensions.Navigation.Toolkit/Navigators/DrawerControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ContentControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ContentDialogNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/SelectorNavigator.cs
src/Uno.Extensions.Navigation.UI/Regions/RegionExtensions.cs
src/Uno.Extensions.Navigation.UI/ResponseNavigator.cs
src/Uno.Extensions.Navigation/INavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHomePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHomePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHomeViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceProductsPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceProductsViewModel.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.UITest/Constants.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/Apps/Commerce/Given_Apps_Commerce.cs

GitHub Issue (If applicable): #590 
- Bugfix
CanNavigate check doesn't switch to UI thread - can cause issues if navigation is triggered from background thread
CanNavigate is now async, which means that where appropriate Navigators can use IDispatcher to switch to the UI thread.
- [X ] Tested code with current [supported SDKs](../README.md#supported)
- [N/A ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ N/A] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [X ] …

fix: Navigation thread issue due to accessing control properties from background thread

---

src/Uno.Extensions-uwp.slnf
src/Uno.Extensions.Navigation.Toolkit/Uno.Extensions.Navigation.Toolkit.UI.csproj

GitHub Issue (If applicable): #563
- Bugfix
Build error in UWP app after adding a reference to Uno.Extensions.Navigation.Toolkit.UI
No build error when adding a reference to Uno.Extensions.Navigation.Toolkit.UI 

fix: Fixing build error when UWP app references Navigation.Toolkit

---

src/Uno.Extensions.Authentication/Custom/CustomAuthenticationProvider.cs
src/Uno.Extensions.Authentication/Custom/CustomAuthenticationSettings.cs
src/Uno.Extensions.Authentication/CustomAuthenticationBuilderExtensions.cs
src/Uno.Extensions.Authentication/TokenCacheExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationServiceHostInit.cs

GitHub Issue (If applicable): (internal)
- Feature
Hard to serialize an entity into tokencache as no access to service provider
There is an overload that provides access to the service provider, making it possible to request an ISerializer
Also helper methods for Get/Set entity into the IDictionary

feat: Adding helpers for serializing entities into tokencache

---

src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/PaginationFacet.cs

On WinUI only the two first pages are loaded
The ListView invokes the `LoadMoreItemsAsync` only once.
🙃

fix(reactive): Fix threading issue in pagination

---

src/Uno.Extensions.Core/Uno.Extensions.Core.csproj

GitHub Issue (If applicable): (internal)
- Bugfix
App crashes on ios/android unexpectedly
Reverts changes that were accidentally committed, which adds back the runtime identifiers in the core library

fix: Addressing crashing on ios/android

---

src/Directory.Build.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UITests/Constants.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UITests/TestBase.cs

GitHub Issue (If applicable): #640 
- Bugfix
Can't run UITests from Test Explorer in VS because it tries to run them headless
UITests run when selected in Test Explorer
This update also adds min platform version for the net6 targets which is now required with latest VS preview

fix: UITests to not run in headless mode in debug

---

src/Uno.Extensions.Navigation/NavigatorExtensions.cs

GitHub Issue (If applicable): # (internal)
- Feature
Not able to pass data into GetDataAsync method
Data can be passed to the GetDataAsync methods

feat: Adding data parameter to GetDataAsync

---

build/ci/.azure-pipelines.Packages.yml
build/ci/.azure-pipelines.Windows.yml
build/ci/templates/update-vs-components.yml
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs

- Bugfix
Noticeable delay when switching views (eg in navview or tabs) due to waiting for elements to load during navigation
FrameworkElementExtensions.DisableLoadWaiting can be set to true in order to prevent element load waiting
NOTE: this is a temporary fix, with a full workaround pending

fix: Disable waiting for elements to load during navigation

---

src/Uno.Extensions.Core/Uno.Extensions.Core.csproj
src/Uno.Extensions.Reactive/Uno.Extensions.Reactive.csproj

- Bugfix
TestHarness.Mobile won't compile, complaining about missing folder for android-x64
All TestHarness projects compile

fix: Address build error when compiling net6 mobile target for testharness

---

src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs
src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationSettings.cs
src/Uno.Extensions.Authentication.UI/WebAuthenticationBuilderExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Web/WebAuthenticationHostInit.cs

- Feature
Unable to access service or service provider in prepareloginstarturi method
Able to access either or both service and service provider in all callback methods

feat: Adding a number of additional callbacks with different parameters to web authentication

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Tests/AppInfoTests.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Tests/GlobalUsings.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Tests/MyExtensionsApp.Tests.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UITests/MyExtensionsApp.UITests.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/wwwroot/staticwebapp.config.json
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj

- Feature
Need to add a config.json file to the wwwroot folder in order to host the wasm app as a static web app (azure)
The Uno.Extensions template comes with a staticwebapp.config.json file preconfigured for Azure static web app deployment

feat: Making it easier to deploy uno extensions app to static web app

---

src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs

fix(feeds): Fix support of CT in commands generation (CT cannot be provided by the view)
When a method has a `T` parameter and a `CT` parameter, the generator tries to generate a command than can be invoked with a tuple like `(T param, CancelleationToken ct)` which is invalid.
The `CT` cannot be provided from the view, so we remove that overload.

fix(feeds): Fix support of CT in commands generation

---

build/ci/.azure-pipelines.Android.yml
src/Uno.Extensions.Reactive.Testing/FeedRecorderExtensions.cs
src/Uno.Extensions.Reactive.Tests/Core/Given_MessageBuilder.cs
src/Uno.Extensions.Reactive.Tests/Core/Given_StateImpl.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableViewModelBase.cs
src/Uno.Extensions.Reactive/Core/Axes/MessageAxis.cs
src/Uno.Extensions.Reactive/Core/ChangeCollection.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.UpdateTransaction.Message.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.UpdateTransaction.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.cs
src/Uno.Extensions.Reactive/Core/Message.cs
src/Uno.Extensions.Reactive/Core/MessageBuilder.TParent.cs
src/Uno.Extensions.Reactive/Core/MessageBuilder.cs
src/Uno.Extensions.Reactive/Utils/DictionaryExtensions.cs

State cannot be updated by VM once a value has been published by the View
When the View pushes a value to a Feed/State, it flags that value so we are able to avoid to raise back a NPC on the "subscriber" side.
The issue is that since we removed the `Input`, the VM is no longer flagging itself as source of the values it is publishing, so the previous value is kept.
So if the View pushes a value, and then the VM updates it, the source flagged remains the View, so the NPC is not raised.
The "source" axis is now flagged as "transient", and values of transient axes are automatically flushed by MessageBuilders.

fix(feeds): State cannot be updated by VM once a value has been published by the View

---

src/Uno.Extensions.Reactive.Testing/FeedRecorder.cs
src/Uno.Extensions.Reactive.Testing/FeedRecorderExtensions.cs
src/Uno.Extensions.Reactive.Tests/Core/Given_StateImpl.cs
src/Uno.Extensions.Reactive.Tests/Factories/Given_ListFeedFactories.Caching.Sources.cs
src/Uno.Extensions.Reactive.Tests/Factories/Given_StateFeedFactories.Caching.Sources.cs
src/Uno.Extensions.Reactive.Tests/Factories/Given_StateFeedFactories.Integration.Sources.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_CombineFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableViewModelBase.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Input.cs
src/Uno.Extensions.Reactive/Core/IListState.cs
src/Uno.Extensions.Reactive/Core/IState.cs
src/Uno.Extensions.Reactive/Core/Internal/ByIndexCursor.cs
src/Uno.Extensions.Reactive/Core/Internal/IStateStore.cs
src/Uno.Extensions.Reactive/Core/Internal/ListStateImpl.cs
src/Uno.Extensions.Reactive/Core/Internal/MessageManager.CurrentMessage.cs
src/Uno.Extensions.Reactive/Core/Internal/SourceContext.cs
src/Uno.Extensions.Reactive/Core/Internal/StateImpl.cs
src/Uno.Extensions.Reactive/Core/Internal/StateStore.None.cs
src/Uno.Extensions.Reactive/Core/Internal/StateStore.cs
src/Uno.Extensions.Reactive/Core/Internal/StateUpdateKind.cs
src/Uno.Extensions.Reactive/Core/ListFeed.T.cs
src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
src/Uno.Extensions.Reactive/Core/ListState.T.cs
src/Uno.Extensions.Reactive/Core/MessageBuilder.TParent.cs
src/Uno.Extensions.Reactive/Core/MessageBuilder.cs
src/Uno.Extensions.Reactive/Core/State.Extensions.cs
src/Uno.Extensions.Reactive/Operators/CombineFeedHelper.cs
src/Uno.Extensions.Reactive/Operators/FeedToListFeedAdapter.cs
src/Uno.Extensions.Reactive/Operators/UpdateFeed.cs

Add ability to create a paginated ListState
We can only create a Paginated feed
We can create a paginated (only by index) ListState

feat(feeds): Add ability to create a paginated ListState

---

src/Uno.Extensions.Authentication.Msal/MsalAuthenticationProvider.cs
src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs
src/Uno.Extensions.Authentication.UI/GlobalUsings.cs
src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs
src/Uno.Extensions.Authentication/BaseAuthenticationProvider.cs
src/Uno.Extensions.Authentication/Custom/CustomAuthenticationProvider.cs
src/Uno.Extensions.Authentication/GlobalUsings.cs
src/Uno.Extensions.Http/CookieManager.cs

- Feature
No logging around the authentication provider methods: login, refresh and logout
All providers have access to a Logger and the back provider logs information about requests for login, refresh and logout

feat: Added logging for all Authentication Providers

---

src/Uno.Extensions.Authentication/TokenCacheExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationTestBackendCookieHostInit.cs

GitHub Issue (If applicable): #697
- Bugfix
CookieHandler saves tokens using the SaveTokenAsync extension which saves a new dictionary with the updated access and refresh tokens added to it. This will clear out any other tokens
CookieHandler gets the current dictionary of tokens from the cache and updates it with the new access and refresh tokens. This way the additional data isn't lost

fix: Preventing additional tokens from being cleaned out when refreshing cookies

---

doc/Overview/Reactive/in-apps.md
src/Uno.Extensions.Reactive.UI/View/FeedView.Subscription.cs
src/Uno.Extensions.Reactive.UI/View/FeedView.cs
src/Uno.Extensions.Reactive.UI/View/FeedView.xaml
src/Uno.Extensions.Reactive.UI/View/FeedViewRefreshState.cs
src/Uno.Extensions.Reactive.UI/View/FeedViewVisualStateSelector.cs

feat(feeds): Add ability to avoid loading state when refreshing
The loading visual state is triggered when a feed is being refreshed
You can request to ignore it!

feat(feeds): Add ability to avoid loading state when refreshing

---

src/Uno.Extensions.Authentication/BaseAuthenticationProvider.cs
src/Uno.Extensions.Authentication/GlobalUsings.cs
src/Uno.Extensions.Authentication/Handlers/BaseAuthorizationHandler.cs
src/Uno.Extensions.Authentication/Headers.cs
src/Uno.Extensions.Authentication/HostBuilderExtensions.cs
src/Uno.Extensions.Http/CookieManager.cs
testing/TestHarness/TestBackend/Controllers/CustomAuthController.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationHomePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationHomeTestBackendPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationHomeTestBackendViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationHomeViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationTestBackendCookieHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/ICustomAuthenticationTestBackendEndpoint.cs

GitHub Issue (If applicable): #694
- Bugfix
See #694 - no way to prevent refresh token logic running for authentication endpoints
Authentication endpoints, login, refresh etc, should be attributed with Header(Headers.NoRefresh) to flag that the refresh logic shouldn't be executed

feat: Preventing recursive refresh token

---

src/Uno.Extensions.Navigation/NavigationRequestExtensions.cs

- Bugfix
When navigating in XAML the incorrect number of parameters are passed when attempting to invoke the generic ToRequest method
The correct parameters are passed.

fix: Exception when attempting to navigate from XAML

---

src/Uno.Extensions.Authentication/BaseAuthenticationProvider.cs

- Bugfix
Exceptions during login callback aren't being captured and are bubbling up out of the LoginAsync method (it should just return false)
LoginAsync returns false

fix: Capturing exceptions during login

---

src/Uno.Extensions.Configuration/Reloader.cs
src/Uno.Extensions.Configuration/WritableOptions.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOneViewModel.cs

GitHub Issue (If applicable): #695
- Bugfix
There's no locking around file access for either read or write
Added semaphore around reading and writing to prevent concurrent access to same files

fix: Preventing read/write lock on writable settings

---

build/ci/.azure-pipelines.Packages.yml
build/tests.runsettings

Fix reactive test not running on CI
Reactive test assembly is ignored as it targets net6.0 (while test engine is looking only for .net 4.0 assemblies)

chore(ci): Fix reactive test not running on CI

---

src/Uno.Extensions.Authentication.Msal/MsalAuthenticationProvider.cs
src/Uno.Extensions.Authentication.UI/GlobalUsings.cs
src/Uno.Extensions.Authentication.UI/HostBuilderExtensions.cs
src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs
src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationSettings.cs
src/Uno.Extensions.Authentication.UI/Web/WebConfiguration.cs
src/Uno.Extensions.Authentication.UI/WebAuthenticationBuilderExtensions.cs
testing/TestHarness/TestHarness.Core/TestSections.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Web/WebAuthenticationMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Web/WebAuthenticationSettingsHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Web/appsettings.webauthsettings.json
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems

- Feature
WebAuth parameters such as loginstarturi have to be set in code. The static values should be able to be set in appsettings
- WebAuth parameters can be specified in appsettings.json. Default section name is Web and maps to the WebConfiguration record
```
internal record WebConfiguration
{
public bool PrefersEphemeralWebBrowserSession { get; init; }
public string? LoginStartUri { get; init; }
public string? LoginCallbackUri { get; init; }
public string? AccessTokenKey { get; init; }
public string? RefreshTokenKey { get; init; }
public string? IdTokenKey { get; init; }
public IDictionary<string, string>? OtherTokenKeys { get; init; }
public string? LogoutStartUri { get; init; }
public string? LogoutCallbackUri { get; init; }
}
```
- Added …

feat: Adding configuration to web authentication

---

src/Uno.Extensions.Authentication/HostBuilderExtensions.cs
src/Uno.Extensions.Authentication/TokenCache.cs
src/Uno.Extensions.Authentication/TokenStorageProvider.cs
src/Uno.Extensions.Core/DependencyInjection/NamedInstance.cs
src/Uno.Extensions.Core/DependencyInjection/NamedInstanceReference.cs
src/Uno.Extensions.Core/DependencyInjection/ServiceCollectionExtensions.cs
src/Uno.Extensions.Core/GlobalUsings.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/ApplicationDataKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/EncryptedApplicationDataKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/KeyChainKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/KeyStoreKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/PasswordVaultKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/ServiceCollectionExtensions.cs
src/Uno.Extensions.Storage/GlobalUsings.cs
src/Uno.Extensions.Storage/IStorage.cs
src/Uno.Extensions.Storage/KeyValueStorage/IKeyValueStorage.cs
src/Uno.Extensions.Storage/KeyValueStorage/InMemoryKeyValueStorage.cs
src/Uno.Extensions.Storage/KeyValueStorage/KeyValueStorageIndex.cs

- Feature
Extra code around registration of IKeyValueStorage implementations that's not necessary
- Multiple IKeyValueStorage implementations are registered for each platform
- IKeyValueStorage now includes an IsEncrypted property indicating whether data is encrypted (ie safe to use for credentials etc)
- For each platform a Default instance is registered with the DI container. 
- The Default instance is used when registering the instance of the TokenCache

feat: Reworking logic around keyvaluestorage

---

src/Uno.Extensions.Authentication/BaseAuthenticationProvider.cs
src/Uno.Extensions.Authentication/Handlers/BaseAuthorizationHandler.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationLoginViewModel.cs

- Feature
If there is an exception during login it is swallowed with a false being returned. This makes it impossible to do conditional logic based on the type of error eg network, credentials 
Exceptions in the login method are now bubbled up - the caller of LoginAsync/LogoutAsync is responsible for handling these exceptions if they occur

feat: Removing try-catch around login/logout/refresh logic

---

testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationHomeViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationMultiHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationSettingsHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationWelcomeViewModel.cs

- Bugfix
Msal using appsettings not working in test harness
Msal sample in test harness is now working

fix: Test case for msal wasn't loading

---

.gitignore
doc/Learn/Tutorials/Authentication/HowTo-Authentication.md
doc/Learn/Tutorials/Configuration/HowTo-WritableConfiguration.md
doc/Learn/Tutorials/DependencyInjection/HowTo-CommunityToolkit.md
doc/Learn/Tutorials/DependencyInjection/HowTo-DependencyInjectionSetup.md
doc/Learn/Tutorials/Hosting/HowTo-HostingSetup.md
doc/Learn/Tutorials/Navigation/Advanced/HowTo-AdvancedPageNavigation.md
doc/Learn/Tutorials/Navigation/Advanced/HowTo-ResponsiveShell.md
doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseContentControl.md
doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseNavigationView.md
doc/Learn/Tutorials/Navigation/Advanced/HowTo-UsePanel.md
doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseTabBar.md
doc/Learn/Tutorials/Navigation/HowTo-DisplayItem.md
doc/Learn/Tutorials/Navigation/HowTo-DisplayMessageDialog.md
doc/Learn/Tutorials/Navigation/HowTo-NavigateBetweenPages.md
doc/Learn/Tutorials/Navigation/HowTo-NavigateInCode.md
doc/Learn/Tutorials/Navigation/HowTo-NavigateInXAML.md
doc/Learn/Tutorials/Navigation/HowTo-SelectValue.md
doc/Learn/Tutorials/Navigation/HowTo-ShowFlyout.md
doc/Overview/DependencyInjection/DependencyInjectionOverview.md
doc/Overview/Validation/ValidationOverview.md
doc/Reference/Navigation/Navigation.md
doc/toc.yml

docs: Updates to AdvNav how-to series

---

src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.CommandConfigGenerator.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs

fixes https://github.com/unoplatform/uno.extensions/issues/728
Fix possible invalid generated code when using ValueType parameter
We check for null using pattern matching, including for `ValueType` and `Nullable<T>`
* We don't check for null for `ValueType`
* We don't use pattern matching anymore (not allowed for `Nullable<T>`, and required an higher version of C# than we should)

fix(feeds): Fix possible invalid generated code when using ValueType parameter

---

src/Uno.Extensions.Hosting.UI/HostBuilder.cs
src/Uno.Extensions.Hosting/IServiceInitialize.cs
src/Uno.Extensions.Localization/HostBuilderExtensions.cs
src/Uno.Extensions.Localization/LocalizationService.cs
testing/TestHarness/TestHarness.Core/TestSections.cs
testing/TestHarness/TestHarness.Shared/BaseTestSectionPage.cs
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationMainPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Localization/appsettings.locale.json
testing/TestHarness/TestHarness.Shared/Strings/en-AU/Resources.resw
testing/TestHarness/TestHarness.Shared/Strings/fr/Resources.resw
testing/TestHarness/TestHarness.Shared/TestFrameHost.xaml.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj

closes: #721 
- Bugfix
Two character language code used instead of Culture name
PrimaryLanguageOverride set too late in app startup sequence
Added a new page to the TestHarness for Localization
PrimaryLanguageOverride  is set in a service initialization method immediately after the IHost has been created

fix: Correcting language override to use full culture name and added Localization page to TestHarness

---

src/Uno.Extensions.Authentication/AuthenticationService.cs
src/Uno.Extensions.Authentication/Handlers/BaseAuthorizationHandler.cs
src/Uno.Extensions.Authentication/TokenCache.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno.extensions/issues/745
- Bugfix
ITokenCache.Cleared event being raised even when there's no tokens in the cache
Cleared event is only raised when there are existing tokens in the cache that are being cleared

fix: Prevent Cleared event being raised when there aren't any tokens

---

src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.Change.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.ChangesBuffer.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.ListRef.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.T.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Add.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Event.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Move.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Remove.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Replace.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Same.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionChangeSet.T.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionChangeSet.cs
src/Uno.Extensions.Reactive/Operators/FeedToListFeedAdapter.cs
src/Uno.Extensions.Reactive/Sources/PaginatedListFeed.cs

Avoid boxing in CollectionAnalyzer
Diff analyzer is working with `object?` which will box `ValueType` and requires us to have a specific path for them. Doing this we are also loosing the nullable annotions and prevents us to add helpers for tracking in `ListFeed<T>`
We are using generic everywhere and using `object?` as `T` when we don't have type like for `CollectionChangedEventArgs`.

fix(feeds): Avoid boxing in CollectionAnalyzer

---

src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
testing/TestHarness/TestBackend/Controllers/CustomAuthController.cs
testing/TestHarness/TestBackend/TestBackend.csproj
testing/TestHarness/TestHarness.Core/DummyJsonEndpointConstants.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/AuthenticationShellViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/ICustomAuthenticationDummyJsonEndpoint.cs

- Bugfix
Attempting to navigate to the same page with clear backstack eg -/Login when already on Login page, should cause the page to be refreshed. This doesn't happen and the navigation request is effectively ignored
A new instance of the viewmodel for the current page is created and data bound. This doesn't reload the page, it just recreates the viewmodel.
Note: This PR also makes changes to the test harness to make it easier to test what happens when incorrect credentials are provided for authentication scenarios.
- [ X ] Tested code with current [supported SDKs](../README.md#supported)
- [ N/A ] Docs have been added/updated which fit [documentation …

fix: Making sure login view is refreshed when navigation with clear backstack

---

src/Uno.Extensions.Navigation/DataMap.cs
src/Uno.Extensions.Navigation/NavigationDataProvider.cs
src/Uno.Extensions.Navigation/ServiceCollectionExtensions.cs
src/Uno.Extensions.Navigation/ViewMap.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno.extensions/issues/751
- Feature
DataMap<T> has to be used to register data types for navigation
Registers data typed using untyped DataMap 
Registers result data type

feat: Making it easier to register navigation data types

---

src/Uno.Extensions.Navigation.UI/Navigators/SelectorNavigator.cs
src/Uno.Extensions.Navigation/RouteExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHomePage.xaml

- Bugfix
If qualifiers are added to a region name, selecting the region fails
Qualifiers should be ignored when setting a region
- [X ] Tested code with current [supported SDKs](../README.md#supported)
- [N/A ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [X ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [X ] Contains **NO** breaking changes
- [N/A ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
Internal Issue (If …

fix: Makes sure that any qualifiers are trimmed when locating selectable region

---

src/Uno.Extensions.Http.Refit/ServiceCollectionExtensions.cs
src/Uno.Extensions.Http/ServiceCollectionExtensions.cs
testing/TestHarness/TestHarness.Core/TestSections.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsMainPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/appsettings.httpendpoints.json
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitMainPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/IHttpRefitDummyJsonEndpoint.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/appsettings.httprefit.json
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj

- Bugfix
- Register HttpClient for a view model eg services.AddClient<MainViewModel>()
- Accept HttpClient as part of MainViewModel  constructor (eg MainViewModel(HttpClient client) )
- HttpClient should be populated with endpoint info from config files
- HttpClient has not BaseAddress set
- HttpClient has BaseAddress set based on config files
- Test cases for Http and Refit

fix: Fixing AddClient for when service instance is specified without an interface

---

doc/Overview/ExtensionsOverviewAndGettingStarted.md

The `-i` is obsolete and produce warnings.
When install the uno-extension template using the 
`dotnet new -i Uno.Extensions.Templates` the tooling prints a warning message. 
No warning message and everyone was happy (:

updated the dotnet command

---

src/Uno.Extensions.Reactive.Testing/ConstraintParts/Items.cs
src/Uno.Extensions.Reactive.Testing/ConstraintParts/ItemsChanged.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_FeedToListFeedAdapter.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/DataStructure.cs
src/Uno.Extensions.Reactive/Collections/ItemComparer.T.cs
src/Uno.Extensions.Reactive/Collections/ItemComparer.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.T.cs
src/Uno.Extensions.Reactive/Core/ListFeed.T.Internal.cs
src/Uno.Extensions.Reactive/Core/ListFeed.T.cs
src/Uno.Extensions.Reactive/Operators/FeedToListFeedAdapter.cs
src/Uno.Extensions.Reactive/Operators/WhereListFeed.cs
src/Uno.Extensions.Reactive/Sources/PaginatedListFeed.cs

linked to https://github.com/unoplatform/uno.extensions/issues/688
Entity tracking in list feeds
We rely only on `Equals` to track entities in messages of ListFeed. This cause the UI to animate remove + add when we update an entity in a `ListState`
We are using the generated key equality to properly track entities

feat(feeds): Entity tracking in list feeds

---

src/Uno.Extensions.Reactive.Generator/KeyEquality/KeyEqualityGenerationContext.cs
src/Uno.Extensions.Reactive.Generator/KeyEquality/KeyEqualityGenerationTool.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_KeyEquatableRecord_Then_Generate.cs

Add support of the DataAnnotations.KeyAttribute
We support only the Uno's KeyAttrbute
We support both

feat: Add support of the DataAnnotations.KeyAttribute

---

samples/Playground/Playground.Shared/ViewModels/AdHocViewModel.cs
src/Uno.Extensions.Authentication.Msal/MsalAuthenticationProvider.cs
src/Uno.Extensions.Configuration/ReloadService.cs
src/Uno.Extensions.Storage.UI/FileStorage.cs
src/Uno.Extensions.Storage/IStorage.cs
src/Uno.Extensions.Storage/StorageExtensions.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.Shared/appsettings.localizationconfiguration.json

GitHub Issue (If applicable): https://github.com/unoplatform/uno.extensions/issues/753
- Bugfix
Attempting to open a package file using IStorageFile.ReadPackageFileAsync raises an internal exception if the file doesn't exist - particularly bad on startup when application looks for files that need to contribute to configuration
File exists check is made for each platform before attempting to open the file

fix: Avoiding exceptions loading files on android, ios and winui

---

doc/Overview/KeyEquality/concept.md
doc/Overview/KeyEquality/rules.md
doc/Overview/Reactive/listfeed.md

fixes: https://github.com/unoplatform/uno.extensions/issues/688
Add docuemntation about the key equality concept
No doc
Doc!

docs(keyEquality): Add docuemntation about the key equality concept

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/Android/MainActivity.Android.cs

With the Toolkit containing the [SafeArea](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/SafeArea.html?tabs=none) control/behavior, we should change the `WindowSoftInputMode` on Android to `AdjustNothing` so that the system does not clash with the SafeArea's logic when the [SoftInput](https://platform.uno/docs/articles/external/uno.toolkit.ui/doc/controls/SafeArea.html?tabs=none#using-insetmasksoftinput-for-on-screen-keyboards) flag is set on SafeArea.

chore: SoftInput.AdjustNothing for droid template

---

src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs

GitHub Issue (If applicable): #797
- Feature
Switching tabs collapses current tab and sets visible new tab, causing a white flicker particularly the first time navigation to a tab
Switching tabs adjusts opacity (currently setting to a fixed value of 0 or 1) to allow new tabs an opportunity to render before they become visible

feat: Adjusting logic for switching views in grid during navigation

---

samples/Playground/Playground.Shared/App.xaml.cs
src/Uno.Extensions.Navigation.Toolkit/GlobalUsings.cs
src/Uno.Extensions.Navigation.Toolkit/ServiceCollectionExtensions.cs
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs

GitHub Issue (If applicable): #843 
- Feature
Navigate on app startup to either login or home depending on logged in status is handled in the constructor of shellviewmodel
InitializeNavigation now has an additional parameter that is a callback, which takes IServiceProvider and INavigator and returns a Task. This should be used to do initial navigation and can optionally do other actions, such as checking for auth, before calling navigate method on the INavigator instance. The IServiceProvider can be queried for any registered services

feat: Adding initialNavigate callback

---

samples/Playground/Directory.Packages.props
samples/Playground/Playground.Droid/Playground.Droid.csproj
samples/Playground/Playground.Droid/Properties/AndroidManifest.xml
src/Uno.Extensions.Navigation.Toolkit/common.props
src/crosstargeting_override.props.sample
src/tfms-ui-all.props
src/tfms-ui-uwp.props
src/tfms-ui-winui.props

- Feature
Extensions target android11
Extensions target android12 (Uno 4.6.0 will drop monoandroid11.0)

feat: Update to Android 12, dropping Android 11

---

src/tfms-ui-all.props
src/tfms-ui-winui.props

- Bugfix
We're seeing duplicate output folders
Removing the .0 on the end of the tfms to correct the folder path

fix: Correcting TFMs

---

src/Uno.Extensions.Core/PlatformHelper.cs

- Bugfix
NRE when accessing static property
No NRE thrown

fix: Null ref when accessing static property not on wasm

---

src/Directory.Packages.props
src/Uno.Extensions.Core.Generators/Common/GenContext/GenerationContext.cs

Downgrade minimum version of roslyn required to run generators as it's causing some issue on macOS and Linux build servers
Generators fails to run on some build agents due to roslyn being at v 4.1

chore: Downgrade minimum version of roslyn required to run generators

---

src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs

- Feature
ViewModels need to end with VM or ViewModel
ViewModels can end with VM, ViewModel or Model to allow for a shift towards reactive models instead of viewmodels

feat: Including Model in view model suffix

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.props
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/App.xaml.host.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/Views/MainPage.xaml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/Views/SecondPage.xaml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Business/Models/Entity.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Presentation/MainModel.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Presentation/MainViewModel.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Presentation/SecondModel.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Presentation/SecondViewModel.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Presentation/ShellModel.cs

- Feature
Reactive is enabled by default
Additional template option to toggle reactive on/off

feat: Adding reactive flag

---

src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Presentation/MainModel.cs

- Feature
Template uses classes for viewmodels and models
Updating extensions template to use record when reactive enabled

feat: Switching to use records for models

---

src/Uno.Extensions.Core/Diagnostics/PerformanceTimer.cs
src/Uno.Extensions.Core/GlobalUsings.cs
src/Uno.Extensions.Navigation.UI/IRouteUpdater.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Regions/RegionExtensions.cs
src/Uno.Extensions.Navigation.UI/RouteNotifier.cs
src/Uno.Extensions.Navigation/NavigationRequest.cs
testing/TestHarness/Directory.Build.props
testing/TestHarness/TestHarness.Shared/BaseHostInitialization.cs
testing/TestHarness/TestHarness.Shared/BaseTestSectionPage.cs

- Feature
No way to time how long navigation takes
Define UNO_EXT_TIMERS in csproj or Directory.Build.info to enable performance timers

feat: Adding performance timers to navigation

---

src/Uno.Extensions.Reactive/Core/ListState.T.cs
src/Uno.Extensions.Reactive/Core/ListState.cs

Add ability to create a ListState from a ListFeed (on the model of State.FromFeed)
Not helper for that
🙃

feat: Add ListState.FromFeed

---

src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableImmutableList.cs

Possible null ref when instantiating `BindableImmutableList`.
In ctor of `Bindable` we apply the initial value, but the inheriting object might **internally** override the `GetChanges`. This drives to invoke `virtual` method in ctor and in the case of the `BindableImmutableList`, invoke it before the `_analyzer` field is initialized.
As this method can be override only in internal code, and the `Bindable` can be used by application code (at least generated code), we fixed it only in the `BindableImmutableList` by using the default analyzer of `ListFeed<T>`.

fix: Fix possible null in Bindable init

---

src/Uno.Extensions.Reactive/Presentation/Bindings/BindableEnumerable.cs

Possible null ref when initialiazing BindableImmutableList
Continuation of https://github.com/unoplatform/uno.extensions/pull/922

fix: Possible null ref when initialiazing BindableImmutableList

---

src/tfms-ui-all.props
src/tfms-ui-net6-only.props
src/tfms-ui-winui.props

- Feature
Includes net5windows tfm as well as net6windows
Only includes net6windows

feat: Remove net5windows tfm

---

samples/Playground/Directory.Build.props
samples/Playground/Playground.Shared/Views/XamlPage.xaml
samples/Playground/Playground.Shared/Views/XamlPage.xaml.cs
src/Directory.Build.props
src/Directory.Build.targets
src/Uno.Extensions.Navigation.Toolkit/Controls/TabBarItemRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/ActionRequestHandlerBase.cs
src/Uno.Extensions.Navigation.UI/Controls/ButtonBaseRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/ItemsRepeaterRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/NavigationViewItemRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/TapRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Navigation.cs
src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.props
testing/TestHarness/Directory.Build.props
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationRegisterHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationTwoPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationTwoViewModel.cs

GitHub Issue (If applicable): https://github.com/unoplatform/uno.toolkit.ui/issues/395
- Feature
No handling for ItemsRepeater
Handler added for ItemsRepeater which will walk the visual tree to work out the item to send as Data with the navigation request

feat: [Navigation] Adding handler for ItemsRepeater

---

samples/Playground/Directory.Build.props
src/Directory.Build.props
src/Uno.Extensions.Reactive.UI/AssemblyInfo.cs
src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.UI.WinUI.csproj
src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.UI.csproj

- Feature
Enables XAML Trimming capabilities for Reactive.

perf: Enable XAML trimming for reactive

---

samples/Playground/Playground.Shared/App.xaml.cs
src/Uno.Extensions.Hosting.UI/ApplicationExtensions.cs
src/Uno.Extensions.Hosting.UI/IApplicationBuilder.cs
src/Uno.Extensions.Navigation.UI/ApplicationBuilderExtensions.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/App.xaml.cs

n/a
- Bugfix
ShowAsync is a parameterless option for the NavigateAsync extension in the Navigation library
NavigateAsync is available with/without specifying an initial navigation callback.
ShowAsync is an extension in the Hosting Library which simply sets the Shell and initializes the host.

fix: ShowAsync should be part of Hosting

---

src/Uno.Extensions.Reactive.Tests/Presentation/Bindings/Given_BindableImmutableList.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/Bindable.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableConfig.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableEnumerable.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableImmutableList.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindablePropertyInfo.cs

fixes https://github.com/unoplatform/uno.extensions/issues/978
Fix possible null ref in list feed init
We are invoking a `virtual` method while in the ctor
Sub-classes (internal) can now prevent this call and are responsible to it at the end of their own ctor.

fix(reactive): Fix possible null ref in list feed init

---

src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs
src/Uno.Extensions.Reactive.UI.Tests/Presentation/Bindings/Collections/Given_BindableCollection_Selection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/SelectionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/ISelectionService.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/SelectionService.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionIndexRange.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionInfo.cs
src/Uno.Extensions.Reactive/Utils/SelectionHelper.cs
src/Uno.Extensions.RuntimeTests.Core/UIHelper.cs
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj

closes https://github.com/unoplatform/uno.extensions/issues/902
Add support of multi selection
`BindableCollection` supports only single-select
`BindableCollection` now also implements `ISelectionInfo`

feat(reactive): Add support of multi-selection in feeds

---

src/Uno.Extensions.Reactive.UI.Tests/Presentation/Bindings/Collections/Given_BindableCollection_Edition.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/DataLayer.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/DataLayerChangesBuffer.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/DataLayerUpdate.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/LeafStrategy.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/CollectionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/EditionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/IBindableCollectionViewSource.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/EditionService.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/IEditionService.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/BasicView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/FlatView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/MapView.cs

closes https://github.com/unoplatform/uno.extensions/issues/370
Add support for collection edition
Collection send to teh are read-only
You can now edit them, changes will be reflected in the `ListState`

feat(reactive): Add support for collection edition

---

src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.CollectionView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/SelectionService.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/BasicView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/FlatView.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionIndexRange.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionInfo.cs
src/Uno.Extensions.Reactive/Utils/SelectionHelper.cs

Linked to https://github.com/unoplatform/uno/issues/10742
Fix multi selection support by forwarding ISelectionInfo impl on wrapping types
Multi select is not working properly depending of how the collection is used
🙃

fix(feeds): Fix multi selection support by forwarding ISelectionInfo impl on wrapping types

---

src/Uno.Extensions.Navigation.UI/Navigators/NavigationViewNavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewMainPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems

GitHub Issue (If applicable): #1033 
- Feature
MenuItems can be data bound by setting MenuItemsSource
Region.Name has to be set in the item template to define the regions that can be navigated to

feat: Adding support for navigation when menuitems are data bound

---

src/Uno.Extensions.Core.Generators/Common/BuildingBlocks/Property.cs
src/Uno.Extensions.Reactive.Generator/Bindables/BindableGenerator.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableFromFeedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableFromFeedProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromFeedOfListField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromFeedOfListProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromListFeedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromListFeedProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/MappedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/MappedMethod.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/PropertyFromFeedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/PropertyFromFeedProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenTool_2.cs
src/Uno.Extensions.Reactive.Testing/FeedUITests.cs
src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.Utils.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs
src/Uno.Extensions.Reactive.Tests/Generator/_ConflictingNsAndTypes.cs

Fix missing some global:: prefixes in generated code
Missing some global:: prefixes in generated code
🙃

fix: Fix missing some global:: prefixes

---

src/Uno.Extensions.Templates/Uno.Extensions.Templates.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.sln
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj

- closes #1036
- Refactoring
DataContracts, Unit Test and UI Tests get included with blank template
- DataContracts project is excluded from the solution
- WeatherForecast model is part of the Server project when using Blank Template Type
- Serilog is disabled on the server when using a Blank Template Type
- Unit Tests project is excluded from the solution
- UI Tests project is excluded from the solution

feat: Removes test projects and data contract project from blank template

---

src/Uno.Extensions.Reactive.UI.Tests/Presentation/Bindings/Collections/Given_BindableListFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.CollectionView.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/BranchStrategy.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/LeafStrategy.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/CollectionChangedFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/CollectionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/FlatCollectionChangedFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/PaginationFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/BasicView.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableConfig.cs

fixes https://github.com/unoplatform/uno.chefs/issues/102
Fix Count property (and other properties) not updated in Bindable<Collection|LisFeed>
The `BindableCollection` does not implement `INotifyPropertyChanged`
🙃

fix(reactive): Fix Count property not updated in Bindable<Collection|LisFeed>

---

src/Uno.Extensions.Navigation.UI/Navigators/NavigationViewNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/SelectorNavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHostInit.cs

closes: #1033
- Bugfix
NavigationView menu items could be data bound but you couldn't data bind the SelectedItem property
SelectedItem can be data bound to set the initial value and twoway bound so the underlying viewmodel can be updated when selection changes

fix: Allowing SelectedItem to be data bound

---

src/Directory.Packages.props
src/Uno.Extensions.Navigation.UI.Markup/AssemblyInfo.cs
src/Uno.Extensions.Reactive.UI.Markup/AssemblyInfo.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj

n/a
- Dependency Update
- Markup packages reference older build of C# Markup which is not binary compatible with the current version
- Template is missing the pre-generated Extensions packages
- Updates to the latest Markup package
- Adds references to the Extensions pre-generated packages in the template

Update Markup References

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/Properties/launchSettings.json

n/a
- Bugfix
launchSettings.json is missing from WASM target
launchSettings.json has been added for WASM target and inspect uri has been added for Server when it is hosting the WASM head

Add missing launchSettings.json for WASM template

---

samples/Playground/Directory.Packages.props
src/Directory.Packages.props
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
src/Uno.Extensions.Storage.UI/FileStorage.cs
src/Uno.Extensions.Storage.UI/Uno.Extensions.Storage.WinUI.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
testing/TestHarness/Directory.Packages.props
testing/TestHarness/TestHarness.Shared/App.xaml.cs
testing/TestHarness/TestHarness.Wasm/LinkerConfig.xml

GitHub Issue (If applicable): #927
- Bugfix
Nested files packages with the application can't be accessed using IStorage
Nested files are accessible using IStorage

fix: Using StorageHelpers to determine if file exists in uno app package

---

src/Uno.Extensions.Navigation.UI/MessageDialogViewMap.cs
src/Uno.Extensions.Navigation.UI/Navigators/ContentControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs
src/Uno.Extensions.Navigation/MappedViewMap.cs
src/Uno.Extensions.Navigation/ViewMap.cs

GitHub Issue (If applicable): #1081 
- Feature
Uses Activator to create instances of FrameView and other view types
Views specified in mapping are registered with DI using empty constructor, eliminating need to use Activator

feat: Remove use of activator to create ui elements

---

src/Uno.Extensions.Navigation.UI/Controls/ItemsRepeaterRequestHandler.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml

GitHub Issue (If applicable): #1065
- Bugfix
Button click also triggers Tapped on ItemsRepeater, which means that navigation will pick up both Navigation.REquest on Button and on ItemsRepeater
Navigation only picks up on the Request set on the Button

fix: Preventing tapped event for when event is on an enabled button

---

src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.nocpm.props
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.props

- Bugfix
RuntimeIdentifier should only be set if not passed in as part of build
RuntimeIdentifier property group is conditional
(same as https://github.com/unoplatform/uno/blob/510d75bd0ead90399208905f28d7c6dbfa13ab23/src/SolutionTemplate/UnoSolutionTemplate.WinUI.netcore/Mobile/UnoQuickStart.Mobile.csproj#L44)

fix: Making RuntimeIdentifier conditional

---

samples/Playground/Playground.Shared/ViewModels/ThemeSwitchViewModel.cs
src/Uno.Extensions.Toolkit.UI/ThemeService.cs

GitHub Issue (If applicable): #1107
- Bugfix
IsDark being accessed from background thread 
IsDark is accessed from UI thread in SetThemeAsync. 
Also added check to make sure initializeasync has completed before setthemeasync proceeds

fix: Correct handling of threads and initialization

---

build/ci/.azure-pipelines.TemplateValidation.yml
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json

- ongoing changes for #1113
- Refactor
Option named `uiMarkup`
VSCode option is disabled by default
Option renamed `markup`
VSCode option is true by default
Cleans up IDE host file as these values are set by the template.json

[Template] Rename uiMarkup to markup

---

samples/Playground/Playground.Shared/ViewModels/ThemeSwitchViewModel.cs
src/Uno.Extensions.Core.UI/Dispatcher.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
src/Uno.Extensions.Navigation/NavigationRequest.cs
src/Uno.Extensions.Toolkit.UI/ThemeService.cs
src/Uno.Extensions.Toolkit/IThemeService.cs
testing/TestHarness/TestHarness.Mobile/TestHarness.Mobile.csproj
testing/TestHarness/TestHarness.Shared/App.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank1Page.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank1Page.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank1ViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2Page.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2Page.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2ViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank3Page.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank3Page.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/BlankViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarListPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarListPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarListViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarMainPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.Skia.WPF/TestHarness.Skia.WPF.csproj

GitHub Issue (If applicable): #976 
- Bugfix
Navigation switches to background thread - this causes thread switching delays
Navigation continues on whatever thread it's started - it will still switch to UI thread as required

fix: Eliminate noticeable delay during navigation due to thread switching

---

build/ci/.azure-pipelines.TemplateValidation.yml
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.sln
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/AppStart.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/Infrastructure/DebugHandler.cs

- ongoing changes for #1113 
- Bugfix
- Refactor
Logging and Serilog are two independent boolean flags on the template
The Serilog option has been dropped, and the Logging option refactored to a choic `None`, `Default`, & `Serilog`.
Previously unchanged template conditions `#if (logging)` have been refactored to use `#if (useLogging)` .

[Template] Refactor logging option to choice

---

samples/Playground/Directory.Packages.props
src/Directory.Packages.props
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
testing/TestHarness/Directory.Packages.props

GitHub Issue (If applicable): #1136 
- Bugfix
Uno 4.7.30 doesn't handle renaming app.xaml
App.xaml can be renamed

chore(deps): Updating uno version to handle changes to app.xaml in templates

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.vscode/launch.json

- backport from Uno template unoplatform/uno/pull/11200
- Bugfix
VSCode Launch config uses pwa-chrome
VSCode Launch config uses chrome

fix: Wasm VSCode launch config

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json

- #1113
- Refactor
UI & Unit tests each have their own boolean flag
there is now just a `tests` option with a multi-select for `ui` and/or `unit`

use multi-select option for tests

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Base/AppHead.xaml.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj

- closes #1105
- Refactor
When Logging is set to none on the recommended preset there is no native logging hook.
When Logging is set to none on the recommended preset the default platform level logging from the blank preset is included.
- Fixes condition with OS Log so that MacCatalyst is properly wired up
- Removes unnecessary condition for including the OSLog package as it is installable for the entire Mobile project but only has binaries for iOS & MacCatalyst.

Add fallback logging on recommended preset

---

src/Uno.Extensions.Navigation.UI/Controls/ItemsRepeaterRequestHandler.cs
testing/TestHarness/TestHarness.Shared/App.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml
testing/TestHarness/TestHarness.UITest/Constants.cs

GitHub Issue (If applicable): #Internal
- Bugfix
If a UserControl is placed at the root of the DataTemplate for ItemsRepeater, navigation fails to pick up the correct data item to send with navigation
Correct data item is selected
- [N/A] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [Internal] Associated with an issue (GitHub or internal)

fix: Return correct data item when itemrepeater tapped

---

testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexDialog.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyout.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyout.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutTwoPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutTwoPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutTwoViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsHostInit.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj

GitHub Issue (If applicable): #N/A
- Feature
Nothing in TestHarness that shows how to do a complex flyout (ie with multiple pages)
Dialogs -> Flyouts -> ComplexFlyout shows how to load a flyout that supports navigating between two pages

feat: Adding UI for testing more complex dialogs

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/Resources.lang-en-us.resw

GitHub Issue (If applicable): #1184
- Bugfix
App created with extensions template (localization enabled) throws exception and then fails to load viewmodels on WinUI target
Workaround is to include a resource file in the WinUI target

fix: Temporary work around for ResourceMap issue

---

src/Uno.Extensions.Reactive.UI.Tests/Presentation/Bindings/Collections/Given_BindableCollection_Events.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/DataLayerUpdate.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/CollectionFacet.cs

fixes https://github.com/unoplatform/uno.extensions/issues/1161
fixes https://github.com/unoplatform/uno.chefs/issues/292
fixes https://github.com/unoplatform/uno.chefs/issues/311
Misc issues with `BindableCollection`:
1. Collection changed events was not raised on initial load when created from a BG thread
2. Property changed event was not raised under certain circonstances
1. For perf consideration, we assume those events was useless and was ignored. While valid when init from the UI thread, this is invalid when the collection is initialized from a BG thread.
2. We missed a case when we added support the `PropertyChanged` event!
1. We always raise events
2. 🙃

Fix issues with bindable collection

---

src/Directory.Build.props
src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyout.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsHostInit.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems

GitHub Issue (If applicable): #1188 
- Bugfix
NavigationResponse never completes because flyout waits for content to be loaded (which won't happen since flyout is closed)
Flyout only waits for content to load if it's not already closed.

fix: Ensure flyout navigationresponse completes

---

src/Uno.Extensions.Validation/Validator.cs
testing/TestHarness/TestHarness.Shared/Converters/StringToBoolConverter.cs
testing/TestHarness/TestHarness.Shared/Ext/Validation/ValidationOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Validation/ValidationOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Models/Validation/FluentValidatorUser.cs
testing/TestHarness/TestHarness.Shared/Models/Validation/SimpleEntity.cs
testing/TestHarness/TestHarness.Shared/Models/Validation/SimpleObservableUser.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj

- Feature
Current sample for Validator does not use Mvvm or provide any kind of UX when a string is validated. Simple validator is also missing a validation for when the object is not able to validate, not errors was found and it is of type INotifyDataErrorInfo.
Current sample for Validator does support real-time validation and Mvvm. Also  when simple validator fails to validate, no errors was found and type of the validating object is INotifyDataErrorInfo it falls in MVVMToolkit validator.

feat: included mvvm support to current validation sample

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.DataContracts/MyExtensionsApp.DataContracts.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj

n/a
- Bugfix
- Maintenance
Support targets for .NET 6 & .NET 7
Adds support for .NET 8 preview
Fixes typo where we create `net6.0-android;net7.0-maccatalyst` with `net6.0` selected as the target framework

Add .NET 8 preview as a template option

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/Program.cs

GitHub Issue (If applicable): #1205
- Feature
- [X ] Framebuffer template does not contain the latest keyboard handling

fix: Add keybindings

---

doc/Learn/Tutorials/Navigation/HowTo-DisplayMessageDialog.md

The title argument needs to be set, otherwise the WASM implementation throws an ArgumentNullException
With the provided example, in WASM an ArgumentNullException is thrown due to the title being null.
The example works also in WASM

docs(message-dialog): added title argument

---

src/Uno.Extensions.Authentication/TokenCache.cs
src/Uno.Extensions.Storage/KeyValueStorage/KeyValueStorageExtensions.cs
testing/TestHarness/TestHarness.Shared/BaseHostInitialization.cs

GitHub Issue (If applicable): #1221 
- Bugfix
All key-values are returned (and set) in the authentication  
Only tokens that relate to auth are stored/retrieved

fix: Limiting access to keys in shared storage

---

src/Directory.Build.targets
src/Uno.Extensions.Core/Uno.Extensions.Core.csproj
src/Uno.Extensions.Reactive/Uno.Extensions.Reactive.csproj

n/ae
- Bugfix
Generators have a ProjectReference and a None Include to pack as an analyzer
This is now handled by a build task that will process a GeneratorProjectReference. It ensures the generator is built with the output in the IntermediateOutputPath (obj) so that we can more easily ensure that the resources exist to reference / pack.

fix: ensure analyzers are packed correctly

---

src/Uno.Extensions.Reactive.UI/Themes/Generic.xaml
src/Uno.Extensions.Reactive.UI/View/FeedView.cs

FeedView does not have a default style
We need to copy the style in all apps
🙃

fix(reactive): Fix FeedView does not have a default style

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json

- closes #1242
- Refactoring
Template has hidden symbol for isVsix
Template uses new tag for Visual Studio 17.5+ so that Visual Studio will properly treat it as a solution template and not a project template.

Visual Studio should treat template as a solution

---

build/ci/.azure-pipelines.TemplateValidation.yml
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/App.recommended.cs

- #1113
- Refactoring
Navigation Options are:
- Default - This uses Uno.Extensions.Navigation for a simple navigation from one page to another page
- Frame - This uses Frame navigation the same as the Uno Blank app
Navigation Options
- Default - (Unchanged)
- Blank - This is Frame with a new name

Rename Frame Navigation Option -> Blank

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json

- closes #1252 
- Bugfix
DataContracts project is created with the Blank preset
DataContracts is not created with the Blank preset unless you have enabled DependencyInjection and Http explicitly

fix: DataTemplates project included with Blank preset

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json

- closes #1256 
- Bugfix
The template shows up in VS now that it has the editorTreatAs tag
The template uses the ide.host.json to declare vs as an unsupported host

add IDE host back to explicitly disable VS

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Base/base.props

n/a
- Bugfix
The generated icon cuts off part of the Uno logo in the generated app icon
The generated icon shows the full Uno logo

fix: resizetizer app icon size

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json

GitHub Issue (If applicable): https://github.com/unoplatform/uno.studio/issues/143
- Bugfix
Creating solution in VS is causing issues with editorTreatAs not being respected when using wizard. 
There's also an exception raised when the slnf file exists
Both sln and slnf are not used when isVsix symbol is set to true

fix: Add back isVsix symbol

---

build/ci/.azure-pipelines.TemplateValidation.yml
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.DataContracts/Serialization/WeatherForecastContext.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.DataContracts/WeatherForecast.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/Apis/WeatherForecastApi.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/Controllers/WeatherForecastController.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/GlobalUsings.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/Program.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj

- closes #1264
- Feature
The server project provides a standard Controller for the WeatherForecast API
By default you now get a Minimal Api with the same Open Api support you get from the existing Controller. You can additionally disable minimal API's to get the existing controller. This also updates the WeatherForecast model to use DateOnly for .NET 7.0+. We cannot use DateOnly for .NET 6.0 due to the library having to use netstandard2.1 instead of being able to use net6.0.

[Template] Minimal API

---

build/ci/.azure-pipelines.TemplateValidation.yml
src/Uno.Extensions.Templates/Uno.Extensions.Templates.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj

- closes #1268
- Bugfix
Template copies the app.manifest from the Windows project to the source for Gtk/Linux
Template correctly copies the Package.appxmanifest instead

Package.appxmanifest missing when Windows head is not present

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/AppResources.xaml

GitHub Issue (If applicable): #1276 
- Bugfix
Build warning
No build warning

fix: Correcting XAML referencing for material and toolkit to avoid build warnign

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.UITests/Given_MainPage.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj

GitHub Issue (If applicable): #1270 
- Bugfix
Missing IsUiAutomationMappingEnabled property on wasm target which prevents IDs being assigned so that UITests can locate elements
Corrected Given_MainPage so that template conditions are invoked
UITests work

fix: Correct csproj for Wasm to get UITests to work

---

src/Uno.Extensions.Reactive.UI/View/FeedView.xaml

- Bugfix
Add proper DefaultFeedViewStyle Key to have both an explicit and implicit style. 
So in an app, you would be able to base a custom FeedView style on the default without having to repeat everything that's in the default template. 

fix: Add proper DefaultFeedViewStyle Key and use it as Implicit

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/MainPage.xaml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/SecondPage.xaml

GitHub Issue (If applicable): #1303 
- Bugfix
BackgroundBrush is used for all themese
Appropriate theme brush used

feat: Adjusting background brush for specified theme

---

src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/MyExtensionsApp.1.csproj

GitHub Issue (If applicable): #1050 #1307 
- Bugfix
Resources for XAML elements aren't being loaded from resw (works on WinUI but not other platforms)
Resources for XAML elements are loaded from resw

fix: localization for XAML elements

---

src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/App.recommended.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/AppResources.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/MyExtensionsApp.1.csproj
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/MainPage.xaml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/MainPage.xaml.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/SecondPage.xaml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/SecondPage.xaml.cs
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/Shell.xaml
src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/Shell.xaml.cs

GitHub Issue (If applicable): #1305 
- Feature
Toolkit is include with recommended preset and not for blank
Toolkit is its own symbol that can be used to override the default value (off for blank, on for recommnded)

feat: Make toolkit optional

---

src/Uno.Extensions.Navigation.UI/Controls/SelectorRequestHandler.cs

GitHub Issue (If applicable): #1331 
- Bugfix
Navigation is triggered on selection changed even when selected item is null
No navigation when selected item is null

fix: Preventing nav on null item selection

---

src/Directory.Build.props
src/Uno.Extensions.Reactive.Testing/ConstraintParts/Items.cs
src/Uno.Extensions.Reactive.Testing/ConstraintParts/ItemsChanged.cs
src/Uno.Extensions.Reactive.UI.Tests/Presentation/Bindings/Collections/Given_BindableCollection_Selection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/BranchStrategy.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/LeafStrategy.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/SelectionFacet.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/SelectionService.cs
src/Uno.Extensions.Reactive/Collections/Facades/Differential/DifferentialImmutableList.cs
src/Uno.Extensions.Reactive/Collections/Facades/Differential/MoveNode.cs
src/Uno.Extensions.Reactive/Collections/RichNotifyCollectionChangedEventArgs.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.ChangesBuffer.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer.Core.cs
src/Uno.Extensions.Reactive/Collections/Tracking/CollectionAnalyzer._Replace.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionInfo.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableImmutableList.cs
src/Uno.Extensions.Reactive/Utils/SelectionHelper.cs

fixes https://github.com/unoplatform/uno.extensions/issues/1233
* In Single selection mode the `ListView.SelectedItem` is not updated when it's being updated by the model
* On Windows the mutli-selection mode is not working properly
* When multi-select, the selection ranges are not coerced properly

fix(mvux): Fix misc selection issues

---

src/Uno.Extensions.Navigation.UI/Controls/NavigationFlyout.xaml
src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs

GitHub Issue (If applicable): 
closes: #1340 
closes: #1341 
- Bugfix
- Uses Material style for flyout
- ModalFlyoutStyle isn't used because the registration is overwritten by Navigationflyout
NavigationFlyout only registered if no Flyout has already been registered
Material style isn't explicitly referenced (will be picked up by implicit style if Material is used)

fix: Correct flyout behaviour with navigation

---

src/Uno.Extensions.Navigation.UI/Controls/SelectorRequestHandler.cs

GitHub Issue (If applicable): closes #1344
- Bugfix
Navigation uses SelectedItem
Navigation uses AddedItems in the SelectionChanged handler

fix: Switch from SelectedItem to using SelectionChanged args

---

.editorconfig

This sets the _.editorconfig_ new VS grammar check language to en-us.
See: https://devblogs.microsoft.com/visualstudio/visual-studio-spell-checker-preview-now-available/

chore: Updating .editorconfig with VS grammar check language

---

src/Uno.Extensions.Navigation.UI/Controls/SelectorRequestHandler.cs
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/ToDo/ToDoTaskListPage.xaml

GitHub Issue (If applicable): #1344 #1365
- Bugfix
If AddedItems is empty navigation isn't done, even if SelectedItems has a value
Fallback to SelectedItems if AddedItems is null
Also, prevents multiple handlers so ItemClick is used if IsItemClickEnabled set to true

fix: Correct selection change for when addeditems is null

---

src/Uno.Extensions.Localization.UI/ResourceLoaderStringLocalizer.cs
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Localization/LocalizationOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Strings/en-AU/Resources.resw
testing/TestHarness/TestHarness.Shared/Strings/en/Resources.resw
testing/TestHarness/TestHarness.Shared/Strings/fr/Resources.resw

GitHub Issue (If applicable): #681
- Bugfix
Keys with dots aren't resolved because resource contains / instead of .
Fallback for resource keys with . to replace with /

fix: Handling keys that have dots

---

samples/Playground/Directory.Packages.props
samples/Playground/Playground.Shared/App.xaml.cs
samples/Playground/Playground.Shared/ViewModels/ShellViewModel.cs
samples/Playground/Playground.Shared/ViewModels/ThemeSwitchViewModel.cs
samples/Playground/Playground.Windows/Playground.Windows.csproj
src/Directory.Packages.props
src/Uno.Extensions.Navigation.Toolkit/ApplicationBuilderExtensions.cs
src/Uno.Extensions.Navigation.Toolkit/WindowExtensions.cs
src/Uno.Extensions.Navigation.UI/ApplicationBuilderExtensions.cs
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
src/Uno.Extensions.Navigation.UI/IRootViewInitializer.cs
src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
testing/TestHarness/Directory.Packages.props

GitHub Issue (If applicable): closes #1399
- Bugfix
Extended splash screen shows on Android 12+ before content of app
Extended splash screen doesn't show

fix: Fixing issue with Android 12+ startup where loading indicator shows briefly

---

doc/Reference/Reactive/listfeed.md

Display looks like this:
but it should look like this:
(From [the State ](https://platform.uno/docs/articles/external/uno.extensions/doc/Reference/Reactive/state.html#set))
formatted correctly

docs: fix formatting of  [!CAUTION] callout so it displays correctly

---

build/ci/scripts/wasm-uitest-run.sh

Adjust chrome for wasm tests to support SIMD for bootstrapper 8.x

ci: Update chrome for wasm tests

---

src/Directory.Build.targets
src/Uno.CrossTargeting.props
src/Uno.Extensions.Logging/HostBuilderExtensions.cs
src/crosstargeting_override.props.sample

GitHub Issue (If applicable): #1476
- Bugfix
Skia/Wasm target packages are netstandard2.0, meaning that #if NET6 conditional includes aren't valid
Skia/Wasm targets net6.0

fix: Updating Skia/Wasm target packages to net6

---

src/Uno.Extensions.Navigation.Toolkit/Controls/TabBarItemRequestHandler.cs
src/Uno.Extensions.Navigation.Toolkit/GlobalUsings.cs
src/Uno.Extensions.Navigation.UI/Controls/ActionRequestHandlerBase.cs
src/Uno.Extensions.Navigation.UI/Controls/ButtonBaseRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/ControlRequestHandlerBase.cs
src/Uno.Extensions.Navigation.UI/Controls/FrameView.xaml.cs
src/Uno.Extensions.Navigation.UI/Controls/IRequestBinding.cs
src/Uno.Extensions.Navigation.UI/Controls/IRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/ItemsRepeaterRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/NavigationFlyout.xaml
src/Uno.Extensions.Navigation.UI/Controls/NavigationFlyout.xaml.cs
src/Uno.Extensions.Navigation.UI/Controls/NavigationRequestBinder.cs
src/Uno.Extensions.Navigation.UI/Controls/NavigationViewItemRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/NavigationViewRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/RequestBinding.cs
src/Uno.Extensions.Navigation.UI/Controls/SelectorRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Controls/TapRequestHandler.cs
src/Uno.Extensions.Navigation.UI/Navigation.cs
src/Uno.Extensions.Navigation/NavigationRequestExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/ToDo/ToDoTaskListPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationFivePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationFiveViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationRegisterHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationSixPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationSixViewModel.cs

GitHub Issue (If applicable): fixes: #1368
- Bugfix
Route creation was setting data to be Options<Data> when it's a back request (or with - prefix). This meant that data wasn't being correctly applied when creating new view models
Routes only contain raw data, with Options<Data> being created, if required, by the NavigationRequest (see https://github.com/unoplatform/uno.extensions/pull/1495/files#r1201776822)
Also includes code refactor and documentation for public types/methods
Also adds logging to various types/methods

fix: Data should be attached to request without Options wrapper

---

src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationProvider.cs
src/Uno.Extensions.Configuration/ConfigBuilderExtensions.cs
src/Uno.Extensions.Configuration/ConfigurationBuilderExtensions.cs
src/Uno.Extensions.Configuration/ReloadService.cs
src/Uno.Extensions.Configuration/Reloader.cs
src/Uno.Extensions.Configuration/WritableOptions.cs
src/Uno.Extensions.Hosting.UI/AppHostingEnvironment.cs
src/Uno.Extensions.Hosting.UI/HostEnvironmentExtensions.cs
src/Uno.Extensions.Hosting.UI/UnoHost.cs
src/Uno.Extensions.Hosting/HostEnvironmentExtensions.cs
src/Uno.Extensions.Hosting/IAppHostEnvironment.cs
src/Uno.Extensions.Logging.Serilog/HostBuilderExtensions.cs
src/Uno.Extensions.Storage.UI/FileStorage.cs
src/Uno.Extensions.Storage/IStorage.cs
testing/TestHarness/TestHarness.Skia.Gtk/TestHarness.Skia.Gtk.csproj

GitHub Issue (If applicable): #1494
- Bugfix
See #1494
App data folder should be created if doesn't exist
Configuration (settings) isn't loaded if app data folder doesn't exist

fix: Preventing crash when app data folder doesn't exist

---

src/Directory.UnoMetadata.targets
src/Uno.Extensions.Storage.UI/FileStorage.cs

GitHub Issue (If applicable): #1510 
- Bugfix
Exception raised when creating instance of FileStorage
Exception was becuase ILogger was used instead of ILogger<FileStorage>

fix: Make ILogger dependency concrete

---

src/Directory.Build.props

- n/a
- Other
The metadata props downloads the correct icon file and we also pack the old icon file
We only use the metadata props to download and use the correct icon file

Remove duplicate icon file from nuget package

---

src/Directory.Build.props
src/Uno.Extensions.Logging.Serilog/Uno.Extensions.Logging.Serilog.csproj
src/Uno.Extensions.Logging/Uno.Extensions.Logging.UWP.csproj
src/Uno.Extensions.Logging/Uno.Extensions.Logging.WinUI.csproj

- closes #1513 
- Bugfix
The check for IsIOS includes both iOS & MacCatalyst
The check for IsIOS only includes iOS
Android, iOS, MacCatalyst, MacOS now use netX agnostic check to prevent issues as we update from net6 in the future.

Fixing build props for IsIOS

---

doc/Learn/Tutorials/DependencyInjection/HowTo-DependencyInjectionSetup.md

docs(DI): Clarify DI docs

---

src/Uno.Extensions.Configuration/AppConfiguration.cs
src/Uno.Extensions.Storage.UI/GlobalUsings.cs
src/Uno.Extensions.Storage.UI/HostBuilderExtensions.cs
src/Uno.Extensions.Storage.UI/ServiceCollectionExtensions.cs
src/Uno.Extensions.Storage/IDataFolderProvider.cs
src/Uno.Extensions.Storage/KeyValueStorage/KeyValueStorageConfiguration.cs
src/Uno.Extensions.Storage/KeyValueStorage/KeyValueStorageConfigurationExtensions.cs
src/Uno.Extensions.Storage/KeyValueStorage/KeyValueStorageExtensions.cs
src/Uno.Extensions.Storage/KeyValueStorage/KeyValueStorageSettings.cs
src/Uno.Extensions.Storage/StorageExtensions.cs

GitHub Issue (If applicable): #1519

chore: Adding docs for storage

---

src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs

GitHub Issue (If applicable): #1482
Closes #1482.
- Test
This adds a test case demonstrating enabling a specific method for command generation while implicit commands disabled.

test(mvux): implicit commands off and explicit command on test method

---

doc/Overview/Mvux/Overview.md

docs(mvux): MVUX Overview rewrite

---

src/Uno.Extensions.Navigation.Generators/ForceBindingsUpdateGenTool_1.cs

GitHub Issue (If applicable): #1534 
- Bugfix
Null reference on WinUI in certain cases when calling Update when Bindings is null
Null check prevents calling Update when Bindings is null
- [ X ] Tested code with current [supported SDKs](../README.md#supported)
- [ N/A ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ N/A ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ X ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests …

fix: Adding null check before calling Update on Bindings

---

README.md

docs: Update broken URLs on README

---

doc/Overview/Mvux/FeedView.md
doc/Overview/Mvux/Feeds.md
doc/Overview/Mvux/ListFeeds.md
doc/Overview/Mvux/ListStates.md
doc/Overview/Mvux/Overview.md
doc/Overview/Mvux/States.md
doc/Overview/Mvux/Tutorials/HowTo-ListFeed.md
doc/Overview/Mvux/Tutorials/HowTo-PushListFeed.md
doc/Overview/Mvux/Tutorials/HowTo-SimpleFeed.md
doc/Overview/Mvux/Tutorials/HowTo-SimpleState.md

GitHub Issue (If applicable): #1559
Documentation updates for MVUX

docs: Tweaks to MVUX documentation

---

src/Directory.Build.props

- Bugfix
Implicit using not working (missing package.targets file from all packages)
Implicit using works
- [N/A ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [N/A] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [N/A] Updated the [Release …

fix: Correcting packaging issue

---

src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs
testing/TestHarness/Directory.Packages.props
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsBasicFlyout.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml.cs
testing/TestHarness/TestHarness.UITest/Constants.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/Dialogs/Given_FlyoutDialog.cs

GitHub Issue (If applicable): #1480
- Bugfix
Flyout remains open when cancellation token cancelled
Flyout closes when token cancelled

fix: Closing flyout on cancellation

---

src/Uno.Extensions.Core.Generators/PropertySelectorGenerator.cs
src/Uno.Extensions.Core.Tests/PropertySelector/Given_PS0003.cs
src/Uno.Extensions.Core.Tests/Utils/GenerationTestHelper.cs

GitHub Issue (If applicable): closes #1625

perf: Reduce the amount of GetSymbolInfo calls for PropertySelectorGenerator

---

testing/TestHarness/Directory.Packages.props
testing/TestHarness/TestHarness.Core/TestHarness.Core.csproj
testing/TestHarness/TestHarness.Legacy.Skia.Gtk/TestHarness.Legacy.Skia.Gtk.csproj
testing/TestHarness/TestHarness.Legacy.Skia.Linux.FrameBuffer/TestHarness.Legacy.Skia.Linux.FrameBuffer.csproj
testing/TestHarness/TestHarness.Legacy.Skia.WPF.Host/TestHarness.Legacy.Skia.Wpf.Host.csproj
testing/TestHarness/TestHarness.Legacy.Skia.WPF/TestHarness.Legacy.Skia.WPF.csproj
testing/TestHarness/TestHarness.Legacy.UWP/TestHarness.Legacy.Uwp.csproj
testing/TestHarness/TestHarness.Legacy.Wasm/TestHarness.Legacy.Wasm.csproj
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataCookbooksPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataEntityPickerFlyout.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataRecipesPage.xaml

GitHub Issue (If applicable): #N/A
- Bugfix
Legacy test harness targets not building
Legacy test harness targets are building

fix: Correcting legacy targets

---

.gitignore
doc/Learn/Tutorials/Http/HowTo-EndpointOptions.md
doc/Learn/Tutorials/Http/HowTo-Http.md
doc/Learn/Tutorials/Http/HowTo-Refit.md
doc/Overview/Http/HttpOverview.md
doc/toc.yml
src/Uno.Extensions.Http.Refit/ServiceCollectionExtensions.cs
src/Uno.Extensions.Http/ServiceCollectionExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/CustomEndpointOptions.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/HttpEndpointsHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Endpoints/appsettings.httpendpoints.json
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/HttpRefitHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Http/Refit/appsettings.httprefit.json
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems

GitHub Issue (If applicable): closes: #1590
- Feature
Additional settings for httpclient need to be done through a custom appsettings section
Additional settings for httpclient can be added to existing endpoint section using a sub-class of EndpointOptions to access the information in code
- [X ] Tested code with current [supported SDKs](../README.md#supported)

feat: Adding support for custom endpointoptions

---

src/Uno.Extensions.Navigation.UI/RouteExtensions.cs
src/Uno.Extensions.Navigation/NavigatorExtensions.cs
src/Uno.Extensions.Navigation/RouteExtensions.cs

GitHub Issue (If applicable): #1652
- Bugfix
If data is provided when using NavigateBackWithResultAsync, the data will be used to determine navigation path, instead of going back
Redirection isn't done based on data if the request is not empty (which includes if navigating back)

fix: Prevent redirect for data when navigating back with data

---

src/Uno.Extensions.Navigation.UI/IRouteUpdater.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
src/Uno.Extensions.Navigation.UI/Regions/NavigationRegion.cs
src/Uno.Extensions.Navigation.UI/ResponseNavigator.cs
src/Uno.Extensions.Navigation.UI/RouteChangedEventArgs.cs
src/Uno.Extensions.Navigation.UI/RouteNotifier.cs
src/Uno.Extensions.Navigation/NavigationResponse.cs
testing/TestHarness/TestHarness.Shared/BaseHostInitialization.cs

GitHub Issue (If applicable): #1675
- Feature
Hard using either IRouteNotifier or NavigationResponse to access the INavigator of the newly created view. Particulalry useful for dialogs where having a reference to the INavigator allows it to be closed.
IRouteNotifier RouteChangedEventArgs now includes INavigator that represents where the view changed. NavigationResponse also has a reference to the INavigator that changed the route.

feat: Added INavigator to both NavigationResponse as well as IRouteNotifier

---

samples/Playground/Directory.Build.props

build: Disable XAML fuzzy matching

---

src/Uno.Extensions.Maui.UI/build/Package.targets

GitHub Issue (If applicable): #https://github.com/unoplatform/uno.extensions-private/issues/79
- Bugfix
Global usings for unsupported tfms (eg net7.0) will cause a build error
Only add global usings for ios, android and winui

fix: Only including using when on supported tfm

---

samples/MauiEmbedding/Directory.Build.props
samples/MauiEmbedding/MauiEmbedding-vsmac.slnf

- ♻️ Housekeeping 
- vsmac.slnf doesn't have the MauiProjects added, so it fails to build the related samples
- The msbuild task generates a class that causes errors on iOS

Fix projects to build nicely 

---

samples/MauiEmbedding/MauiEmbedding/Presentation/MauiColorsPage.xaml
src/Uno.Extensions.Maui.UI/MauiThickness.cs

- Changed implementation
The behavior will not change, just the implementation.

Prefer to use Maui's converter.

---

samples/Playground/Playground.Shared/App.xaml.cs
samples/Playground/Playground.Shared/AppHost.cs
samples/Playground/Playground.Shared/Services/SimpleStartupService.cs
src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
src/Uno.Extensions.Navigation.UI/NavigationHostedService.cs

GitHub Issue (If applicable): #1732 
- Bugfix
Region.Logger isn't set if startup takes too long
Region.Logger is always set before nav takes place

fix: Ensuring Region.Logger is set before navigation proceeds

---

src/Uno.Extensions.Maui.UI/Internals/MauiContentHost.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/MauiHost.cs
src/Uno.Extensions.Maui.UI/Uno.Extensions.Maui.WinUI.csproj

- closes unoplatform/uno.extensions-private#102
- Feature
There is no good way to inject "Application Level Resources" into Maui Embedding
We now have an extension method on the MauiAppBuilder to provide a Maui ResourceDictionary which can be injected into the MauiContentHost providing all of the resources which you might normally put in a Maui Application, thus eliminating the need to inject these into each custom user control.

Provide Maui Resource Dictionary

---

build/ci/templates/dotnet-install-windows.yml
src/Uno.Extensions.Reactive/Core/Feed.cs
src/Uno.Extensions.Reactive/Sources/PageResult.cs

Add ability to project to paginated by cursor list feed
We can have paginated list by cursor without parameter or by index with (or without) parameter, but we cannot have a paginated list by cursor with parameter.
We can!

feat: Add ability to project to paginated by cursor list feed

---

samples/MauiEmbedding/Directory.Packages.props
samples/Playground/Directory.Packages.props
src/Directory.Packages.props
src/Uno.Extensions.Navigation.UI.Markup/Uno.Extensions.Navigation.WinUI.Markup.csproj
src/Uno.Extensions.Reactive.Tests/Given_ListFeed.cs
src/Uno.Extensions.Reactive.Tests/Sources/Given_DynamicFeed.cs
src/Uno.Extensions.Reactive.UI.Markup/Uno.Extensions.Reactive.WinUI.Markup.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Windows/Uno.Extensions.RuntimeTests.Windows.csproj
testing/TestHarness/Directory.Packages.props

GitHub Issue (If applicable): N/A (canary build error)
- Bugfix
Toolkit has incremented WinAppSdk to v1.1.5 which results in a break due to version mismatch
Minimum WinAppSdk dependency ix 1.1.5
- [N/A] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [N/A] Associated with an issue (GitHub or internal)

fix: Bump WinAppSdk reference version

---

src/Uno.Extensions.Reactive.UI.Tests/Given_FeedView.cs
src/Uno.Extensions.Reactive.UI/View/FeedView.cs
src/Uno.Extensions.Reactive/Core/MessageEntry.cs
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Shared/App.xaml.cs
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Windows/Properties/launchsettings.json
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Windows/Uno.Extensions.RuntimeTests.Windows.csproj

closes https://github.com/unoplatform/uno.extensions/issues/1666
FeedView not initializing properly is not visible on first load
`FeedView` subscribes to its `Source` on loaded, no matter if the template has yet been applied or not. This drives the `FeedView` to invoke some `GoToState` which does nothing, and will not do it again when template is being applied.
We wait to have both being loaded and have a template applied before subscribing to the `Source`. 
Note: This also make sure to not load some data if useless, which is the expected default behavior so far.
- [ x Tested code with current [supported SDKs](../README.md#supported)

fix: FeedView not initializing properly is not visible on first load

---

src/Uno.Extensions.Reactive.UI.Tests/Generator/Given_VMWithCommands.cs
src/Uno.Extensions.Reactive/Utils/FeedUIHelper.cs

closes https://github.com/unoplatform/uno.extensions/issues/1622
Ensure that feed parameters shares the same context as the Model
In old versions of reactive it might happen that context used for command's "feed parameters" was not the same as the model itself.
Add tests to enforce no regression

test(mvux): Ensure that feed parameters shares the same context as the Model

---

src/Uno.Extensions.Maui.UI/Internals/ServiceCollectionExtensions.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Reactive.Tests/Sources/Given_DynamicFeed.cs

GitHub Issue (If applicable): #https://github.com/unoplatform/uno.extensions-private/issues/105
- Bugfix
Material styles don't show in WinUI target for Uno app when UseMauiEmbedded is called
Maui initializers are removed so the Material resources are available in Uno app (Windows)

fix: Disable maui initializers on windows

---

src/Directory.Build.targets
src/Uno.Extensions.Core/Uno.Extensions.Core.csproj
src/Uno.Extensions.Navigation/Uno.Extensions.Navigation.csproj
src/Uno.Extensions.Reactive/Uno.Extensions.Reactive.csproj

`DownloadAndSetPackageIcon` can be run twice for the same project.

build: Adjust generator packaging to not require double build

---

src/Uno.Extensions.Reactive.Tests/Core/Given_TokenSet.cs
src/Uno.Extensions.Reactive/Core/Axes/TokenSet.cs
src/Uno.Extensions.Reactive/Sources/Dynamic/Dependencies/Feed/FeedDependency.T.cs
src/Uno.Extensions.Reactive/Sources/Dynamic/Dependencies/Pagination/PaginationDependency.cs

closes https://github.com/unoplatform/uno.extensions/issues/1757
Pagination with parameter can produce empty `TokenSet` for which comparison is not valid.
On first page an empty token set is return, causing the `ListView` to not wait properly for pagination result, driving to infinitely re-request more items.
Empty `TokenSet` are always consider as "lower than" any non empty token set.

fix: Fix projected pagination cycling

---

src/Uno.Extensions.Maui.UI/Internals/MauiEmbeddingInitializer.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.android.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.apple.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.windows.cs
src/Uno.Extensions.Maui.UI/MauiHost.cs

- n/a
- Refactoring
The MauiContext is created on the fly from the MauiApp
The Application is initialized with a Maui Handler / MauiContext. This follows the pattern Maui uses internally and allows us to grab the correct context off of the Application. Makes more direct use of IPlatformApplication.

Initialize Application Handler

---

src/Uno.Extensions.Core.Generators/Compat/CompatibilityTypesGenerationContext.cs
src/Uno.Extensions.Core.Generators/Compat/CompatibilityTypesGenerationTool.cs

linked to https://github.com/unoplatform/uno.extensions/issues/1674
Add generator for few more compatibility types
Some compat types are not generated
They are!

feat(compatTypes): Add generator for few more compatibility types

---

samples/MauiEmbedding/MauiEmbedding/App.cs
src/Uno.Extensions.Maui.UI/Internals/EmbeddedWindowHandler.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.android.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.apple.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.windows.cs
src/Uno.Extensions.Maui.UI/MauiHost.cs
src/Uno.Extensions.Maui.UI/Uno.Extensions.Maui.WinUI.csproj

- closes unoplatform/uno.extensions-private#106
- Bugfix
While we initialize the IApplication with a Handler, there is no Window set and the MainPage also remains uninitialized.
We now make sure the Application.MainPage is also set on a Window and that the Window is added to the IApplication.Windows. Both then receive a Handler with the MauiContext

Initializing Application Window and Main Page

---

src/Uno.Extensions.Maui.UI/MauiEmbedding.cs

- n/a
- Bugfix
We set the page in the window constructor... this can generate an exception where the Window Handler is not yet initialized.
Set the Page on the Window after the Window Handler is set.

set the page after initializing the Handler

---

src/Uno.Extensions.Navigation.UI/Navigation.cs

We can change this to set the `NavigationRequestBinder` even the value is null (this PR). It looks like null or empty/whitespace string is treated the same way anyway, and will be picked up here:
https://github.com/unoplatform/uno.extensions/blob/a7151a1a06fe65fd2ebf4ebc3cf267d197d4a48c/src/Uno.Extensions.Navigation/NavigationRequestExtensions.cs#L13-L14

fix: Enable region navigation for null request

---

samples/MauiEmbedding/MauiEmbedding.MauiControls/SyncfusionDemoPage.xaml.cs
src/Directory.Build.props
src/Uno.Extensions.Core.Generators/buildTransitive/Uno.Extensions.Core.props
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.windows.cs
src/Uno.Extensions.Maui.UI/MauiHost.cs

- Bugfix
Maui Loaded event isn't raised
Maui Loaded event is raised on elements

fix: Set Parent to be Window

---

src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/MauiHost.cs

- Bugfix
Android context not being correctly set on MauiContext causing issues with alertmanager
Android context correctly set

fix: Setting Activity in Android context

---

src/Uno.Extensions.Maui.UI/MauiEmbedding.apple.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/Properties/Resources.Designer.cs
src/Uno.Extensions.Maui.UI/Properties/Resources.resx

- Bugfix
UIWindow isn't accessible
UIWindow is added to the maui context service container

fix: Adding UIWindow to the service container

---

src/Uno.Extensions.Maui.UI/MauiEmbedding.android.cs

- closes #1876 
- Bugfix
The Android Platform is initialized with the Android App as part of the Maui Embedding Initialization after the MainActivity has been created.
The Android Platform is initialized using the current Activity so that the Platform.CurrentActivity will have an initial value.

Ensure Platform.CurrentActivity is set

---

src/Uno.Extensions.Maui.UI/build/Package.props

- Feature
No custom namespaces for conditional xaml based on whether running on maui target or not
Can use maui and not_maui namespace prefixes to show different content depending on whether running on a maui target or not

feat: Adding maui and not_maui namespace definitions

---

src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationProvider.cs
src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs
src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs
src/Uno.Extensions.Configuration/ConfigBuilderExtensions.cs
src/Uno.Extensions.Configuration/ServiceCollectionExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Oidc/OidcAuthenticationHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Oidc/appsettings.oidc.json
testing/TestHarness/TestHarness.Windows/Package.appxmanifest

GitHub Issue (If applicable): https://github.com/unoplatform/uno.extensions/issues/1574
- Bugfix
Auth providers (MSAL, Web, OIDC) should load configuration sections that match the name provided during configuration. This is not the case, resulting in the last read settings being applied to all providers of a given type.
For example if there are mulitple OIDC auth registrations, currently they will all get the settings for the last registration.
Auth providers (MSAL, Web, OIDC) should load configuration sections that match the name provided during configuration.
Multiple auth registrations for the same type should get independent setttings
- [N/A] Docs have been added/updated which fit …

fix: Registering settings by name

---

src/Uno.Extensions.Core.Generators/Common/GenTool/CodeGenToolExtensions.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableFromFeedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableFromFeedProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromFeedOfListField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromFeedOfListProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromListFeedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromListFeedProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/PropertyFromFeedField.cs
src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/PropertyFromFeedProperty.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenTool_2.cs
src/Uno.Extensions.Reactive.Tests/IntegrationTests/Given_HotReload.cs
src/Uno.Extensions.Reactive/Core/HotReload/HotReloadService.cs
src/Uno.Extensions.Reactive/Operators/HotSwapFeed.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableViewModelBase.HotReload.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableViewModelBase.cs
src/Uno.Extensions.Reactive/Presentation/Commands/Command.cs
src/Uno.Extensions.Reactive/Sources/Dynamic/Dependencies/Feed/FeedDependency.cs
src/Uno.Extensions.Reactive/Sources/Dynamic/DynamicFeed.cs
src/Uno.Extensions.Reactive/Sources/Dynamic/FeedSession.T.cs
src/Uno.Extensions.Reactive/Utils/Logging/LogExtensions.cs

Fix MVUX hot reload support
Needs to restart the app too often
* Generate property instead of fields (supported by hot-reload)
* Generate the missing CreateNew... attribute on Model

fix: Fix MVUX hot reload support

---

src/Uno.Extensions.Reactive/Config/ModuleFeedConfiguration.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceSettingsPage.xaml.cs

Make the HR to be enabled on MVUX if app is built in DEBUG
We assume that the first module initialized is the app head, but it might not be the case
We check the module assembly name with the entry assembly name

fix: Make the HR to be enabled on MVUX if app is built in DEBUG

---

doc/.markdownlint.json

- Other... Please describe: Adding linter support for the documentation
Adding support for the Markdown linter and enabling the Code Block to remove the warning with the indentation.
This is the default configuration :
```
{
"default": true,
"MD013": false,
}
```
adding 
```
"no-hard-tabs": {"code_blocks": false}
```
Will disable checking for hard tabs on code blocks.
| Before | After |
| :--:  | :---: |
| <img width="1696" alt="mk-linter-before" src="https://github.com/unoplatform/uno.extensions/assets/1900897/192bc8cd-04ee-494e-b96d-b1ba2336c171">|<img width="1701" alt="mk-linter-after" src="https://github.com/unoplatform/uno.extensions/assets/1900897/7ae45668-82c3-4fb5-9543-115b5ae9d9bc">|
Important: …

chore: add markdown linter rules for code blocks

---

src/Uno.Extensions-packageonly.slnf
src/Uno.Extensions.Maui.WinUI.Markup/Uno.Extensions.Maui.WinUI.Markup.csproj
src/Uno.Extensions.Navigation.UI/MappedRouteResolver.cs
src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/NavigatorExtensions.cs
src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
testing/TestHarness/Directory.Packages.props
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFivePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFivePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFiveViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFourPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFourPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveSixPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveSixPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveSixViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreeViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveTwoPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveTwoPage.xaml.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.UITest/Constants.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/Reactive/Given_Reactive.cs

GitHub Issue (If applicable): closes #2032
- Bugfix
Implicit routes don't work with mvux
Navigating to implicit route clears frame backstack
Implicit routes work with mvux and navigating to an implicit route doesn't clear backstack

fix: Navigation to implicit route clears backstack

---

doc/Overview/Mvux/States.md

It currently doesn't render correctly:

docs: Fix "TIP" rendering

---

src/Uno.Extensions.Authentication.Oidc/HostBuilderExtensions.cs
src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs
src/Uno.Extensions.Authentication.Oidc/WebAuthenticatorBrowser.cs
src/Uno.Extensions.Authentication.UI/HostBuilderExtensions.cs
src/Uno.Extensions.Authentication.UI/WinUIEx_WebAuthenticator.cs
src/Uno.Extensions.Core/PlatformHelper.cs
testing/TestHarness/TestHarness.Shared/App.xaml.cs

WinUIEx WebAuthenticator is out of date
Oidc provider creates instance of WebBrowser
WebAuthenticator updated with latest code from WinUIExe
Oidc provider has IBrowser injected

feat: Updating WebAuthbrowser to latest form winuiex

---

src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive/Core/IListState.cs
src/Uno.Extensions.Reactive/Core/IState.T.cs
src/Uno.Extensions.Reactive/Core/Internal/ListStateImpl.cs
src/Uno.Extensions.Reactive/Core/Internal/StateImpl.cs
src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
src/Uno.Extensions.Reactive/Core/State.Extensions.cs
src/Uno.Extensions.Reactive/Operators/ListFeedSelection.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableViewModelBase.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/Input.cs

Uniformize public async API
* Rely only on IDE for async handling
* Enforce code quality by forcing usage of `CancellationToken`
* Suffix all method with `Async`
* Make `CancellationToken` optional

feat: Uniformize public async API

---

src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOneViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveTwoPage.xaml
testing/TestHarness/TestHarness.UITest/Ext/Navigation/Reactive/Given_Reactive.cs

GitHub Issue (If applicable): fixes: https://github.com/unoplatform/uno.extensions/issues/2097
- Bugfix
When navigating back both page instance and attached viewmodel are cached, and are used when navigating back to the same page
Page and viewmodel are disposed, so the next back operation will cause new instance of page and viewmodel to be created

fix: free viewmodel and prevent caching of page on back

---

src/Uno.Extensions.Maui.WinUI.Markup/AssemblyInfo.cs
src/Uno.Extensions.Maui.WinUI.Markup/MauiHostMarkupExtensions.cs
src/Uno.Extensions.Maui.WinUI.Markup/Uno.Extensions.Maui.WinUI.Markup.csproj

- Build error when using Uno.Extensions.Maui.Markup
- Bugfix
Building with the Markup library results in errors like:
```
2>C:\samples\reference\TubePlayer\TubePlayer\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\GlobalStaticResources.cs(49,5,49,54): error CS0433: The type 'GlobalStaticResources' exists in both 'Uno.Extensions.Maui.WinUI.Markup, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' and 'Uno.Extensions.Maui.WinUI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
2>C:\samples\reference\TubePlayer\TubePlayer\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\GlobalStaticResources.cs(50,5,50,54): error CS0433: …
```

Only provide extensions for the Source type

---

src/Uno.Extensions.Navigation/build/Package.targets

- Bugfix
This change aligns `AdditionalFiles` with `_InjectAdditionalFiles` from Uno source generators, which may duplicate content based on the absence of `SourceItemGroup`.
This would cause hot reload to fail silently because of duplicate `AdditionalFiles` entries.

fix: Add AdditionalFiles metadata to ensure proper deduplication

---

src/Uno.Extensions.Navigation/build/Package.targets

This change avoids a de-deduplication issue in uno sourcegen tasks, and allows for hot reload to work until uno deduplication is fixed.

fix: restrict AdditionalFiles to wasdk only

---

src/Uno.Extensions.Navigation.UI/Navigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/ClosableNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/DialogNavigator.cs
src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/ContentDialogsPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/ContentDialogsPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/ContentDialogsSecondPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/ContentDialogsSecondPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsBasicFlyout.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexDialog.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexDialogFirstPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyout.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsComplexFlyoutTwoPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsFlyoutsViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsMainPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsSimpleDialog.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/DialogsSimpleViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/Dialogs/LocalizedDialogsPage.xaml.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
testing/TestHarness/TestHarness.UITest/Ext/Navigation/Dialogs/Given_ContentDialog.cs

GitHub Issue (If applicable): closes #1394
- Feature
No easy way to navigate from inside a dialog/flyout to a route in the main window of the application. This should close the dialog/flyout
If the route can't be navigated to within the dialog (eg the route isn't part of the routemap for the route already open in the dialog/route), the navigation request is forwarded to the navigator that initially opened the dialog/flyout. The Dialog/Flyout is also closed

feat: Adding ClosableNavigator to close dialog/flyout when attempting to navigate to unsupported route

---

src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Windows/Uno.Extensions.RuntimeTests.Windows.csproj

VS Code w/Dev Kit **cannot** load Uno.Extension.sln successfully outside of Windows
VS Code w/Dev Kit can load Uno.Extension.sln successfully

chore: allow loading Uno.Extensions.sln into VS Code / DevKit

---

build/ci/.azure-pipelines.yml
src/Uno.Extensions.Hosting.UI/ApplicationBuilder.cs
src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2147
- Bugfix
(see issue)
Fix: command line arguments are correctly added to configuration via hosting - this enables testing of startup navigation by setting commandline in launchsettings eg
Fix: correct calculation of navigated route to only include segments that appeared in the original route

fix: Correcting calculation of navigated route

---

src/Uno.Extensions.Navigation.UI/RouteInfoExtensions.cs
src/Uno.Extensions.Navigation.UI/RouteResolver.cs
src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarHomePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarHomeViewModel.cs

GitHub Issue (If applicable): closes #2129
- Bugfix
Generated route maps aren't always being added to the Mappings in memory cache
Generated route maps are added to cache

fix: Adding caching for generated route maps

---

samples/Playground/Playground/appsettings.json
src/Uno.Extensions.Configuration/ConfigBuilderExtensions.cs
src/Uno.Extensions.Hosting.UI/AppHostingEnvironment.cs
src/Uno.Extensions.Navigation.UI/BackButtonService.cs
src/Uno.Extensions.Navigation.UI/BrowserAddressBarService.cs
src/Uno.Extensions.Navigation.UI/GlobalUsings.cs
src/Uno.Extensions.Navigation.UI/HostBuilderExtensions.cs
src/Uno.Extensions.Navigation.UI/NavigatorExtensions.cs
src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs
src/Uno.Extensions.Navigation.UI/common.props
src/Uno.Extensions.Navigation/NavigationConfig.cs
src/Uno.Extensions.Navigation/NavigationConfiguration.cs

GitHub Issue (If applicable): fixes #1998, #2038
- Bugfix
- Feature
No support for back button to drive navigation
Updating address bar adds to browser history, which is meaningless if use navigates back within the app (which will continue to add items instead of removing them)
Address bar support is consistent with the SystemNavigationManager implementation - single item that is updated if there is somewhere to navigate back to
Added back button integration for browser
- back button is enabled if navigation can go back (ie in a frame within the nav hierarchy)
- back button is enabled if there's a previous site (eg you navigate from another site to the wasm application)
Both address bar updating and back button usage can be controlled using the …

fix: Correcting browser history and adding back button integration

---

doc/Learn/Mvux/Overview.md

We are moving away from bare links for hyperlinks as it is causing layout issues for the website.
(But a related issue is opened here to find a solution for this: https://github.com/unoplatform/uno/issues/15049)

docs: Update Overview.md weather app link to avoid website alignment issue

---

doc/Learn/Markup/VisualStateManager.md

docs: Fix VisualStateManager next steps link

---

build/ci/.azure-pipelines.Packages.yml
build/ci/.azure-pipelines.Wasm.yml
build/ci/.azure-pipelines.Windows.yml

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2172 also closes https://github.com/unoplatform/Uno.Figma/issues/2385
- Bugfix
Incorrect usage of gitversion value
Correcting gitversion variable

fix: Correcting gitversion

---

src/Uno.Extensions.Storage.UI/HostBuilderExtensions.cs

GitHub Issue (If applicable): closes #https://github.com/unoplatform/uno.templates/issues/578
- Bugfix
Serialization should be registered with hostbuilder when storage is registered (since it uses ISerializer). 
Serialization is now registered prior to registering storage 

fix: Make sure serialization is registered when registering storage

---

src/Uno.Extensions.Core/PlatformHelper.cs

GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/discussions/15635
- Bugfix
Dllimported method GetCurrentPackageFullName is invoked on all platforms other than WASM. It should only be invoked on Windows
Platform check ensures GetCurrentPackageFullName is only called on Windows

fix: Adding platform check before invoking dllimport method

---

doc/Learn/Mvux/Tutorials/HowTo-Records.md
doc/Learn/Mvux/WorkingWithRecords.md
doc/Learn/Mvux/toc.yml

Guidance to write proper records with MVUX.

docs: Guidance how to write records

---

src/Directory.Packages.props
src/Uno.Extensions.Maui.UI/build/Package.targets
src/Uno.Extensions.Maui.WinUI.Markup/MauiHostMarkupExtensions.cs

- n/a
- Bugfix
MAUI namespaces may be implicitly added. C# Markup API's use `.Bind(`
MAUI namespaces are removed from implicit namespaces. C# Markup has been updated to use new `.Binding(` methods.

Maui Namespaces

---

src/Uno.Extensions.Configuration/ConfigBuilderExtensions.cs
testing/TestHarness/Directory.Packages.props
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Web/WebAuthenticationSettingsHostInit.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Web/appsettings.webauthsettings.json
testing/TestHarness/TestHarness.Windows/TestHarness.Windows.csproj

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/discussions/2193
- Bugfix
Where there are multiple configurations for a given type, or they're referenced by name, the configuration doesn't return valid information
Configuration sections are correctly registered by name

fix: Configuration information not passed to Authentication providers by name

---

doc/Learn/Mvux/ListFeeds.md

Fixing these code formatting issues:
Also replacing the appearances of *list-feed* with `ListFeed`

docs: fix MVUX ListFeed coding styles

---

doc/Learn/Markup/Binding101.md
doc/Learn/Markup/Converters.md
doc/Learn/Markup/DependencyPropertyBuilder.md
doc/Learn/Markup/SourceUsage.md

Updated the documentation with new binding updates.

chore: new binding updates

---

doc/Learn/Authentication/HowTo-Authentication.md
doc/Learn/Storage/HowTo-RequiredEntitlements.md
doc/Learn/Storage/StorageOverview.md
doc/Learn/Storage/toc.yml
doc/toc.yml
src/Uno.Extensions.Storage.UI/KeyValueStorage/KeyChainKeyValueStorage.cs

GitHub Issue (If applicable): closes #2126
On Apple platforms authentication can fail if the required entitlements are not present for the app. However there's no useful logs nor any documentation about what's required to make it work.
At runtime logs will include an URL to the related documentation using https://aka.platform.uno/missing-keychain-entitlement
This document explains what is needed and how to set this up for the application.

docs: Add required entitlements for iOS and Catalyst

---

src/Uno.Extensions.Authentication.MSAL/build/Package.targets
testing/TestHarness/TestHarness.Windows/TestHarness.Windows.csproj

GitHub Issue (If applicable): workaround for #https://github.com/unoplatform/uno/issues/14555
- Bugfix
Referencing Auth.MSAL causes build error (as per https://github.com/unoplatform/uno/issues/14555)
No exception during build

fix: Moving windows/webview2 workaround to auth MSAL library targets

---

src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs

GitHub Issue (If applicable): related to https://github.com/unoplatform/uno.extensions/discussions/2193
- Feature
No logging when unable to start login or logout flow for web auth
Warning logs when unable to start login or logout flow

feat: Adding logging when unable to launch login or logout flows

---

src/Uno.Extensions.Navigation.Toolkit/ExtendedSplashScreenExtensions.cs

Related to https://github.com/unoplatform/uno.toolkit.ui/pull/1061
- Bugfix
Reference to removed Splashscreen property on ExtendedSplashScreen
Reference has been removed in line with toolkit changes

fix: Removing reference to splashscreen as removed from toolkit

---

src/Uno.Extensions.Maui.UI/MauiEmbedding.android.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.apple.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.windows.cs
src/Uno.Extensions.Maui.UI/MauiHost.cs
src/Uno.Extensions.Maui.UI/Uno.Extensions.Maui.WinUI.csproj
src/Uno.Extensions.Maui.UI/build/Package.targets

- n/a
- Bugfix
Workaround conflicts with Uno.Sdk
Workaround is disabled with Uno.Sdk

Disable WinAppSdk workaround with Uno.Sdk

---

doc/Learn/Markup/Styles.md

- unoplatform/uno#14947
Adding section to explain how to add Style Setters for properties that do not have a generated Extension

Add docs for Style<T> where no extension exists

---

doc/Learn/Markup/Overview.md
doc/Learn/Markup/Resources.md
doc/Learn/Markup/Styles.md

GitHub Issue (If applicable): internal

docs: Reference Tech Bites videos in C# markup docs 

---

src/Uno.Extensions.Core.Generators/Compat/CompatibilityTypesGenerationContext.cs
src/Uno.Extensions.Core.Generators/Compat/CompatibilityTypesGenerationTool.cs
src/Uno.Extensions.Core.Generators/buildTransitive/Uno.Extensions.Core.props
src/Uno.Extensions.Reactive.Messaging/StateExtensions.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_StateRefresh.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
src/Uno.Extensions.Reactive/Core/IState.cs
src/Uno.Extensions.Reactive/Core/Internal/FeedSubscription.cs
src/Uno.Extensions.Reactive/Core/Internal/ListStateImpl.cs
src/Uno.Extensions.Reactive/Core/Internal/StateImpl.cs
src/Uno.Extensions.Reactive/Operators/ListFeedSelection.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/Input.cs

Add ability to refresh an IState
No way to programmatically refresh an IState
🙃

feat: Add ability to refresh an IState

---

samples/Playground/Directory.Build.props
src/Directory.Build.props
src/Uno.Extensions.Reactive.Tests/Core/Axes/Given_SelectionInfo.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/SelectionFacet.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionIndexRange.cs
src/Uno.Extensions.Reactive/Core/Axes/SelectionInfo.cs
src/Uno.Extensions.Reactive/Utils/SelectionHelper.cs
testing/TestHarness/Directory.Build.props

closes https://github.com/unoplatform/uno/discussions/15654
Fix selection not working properly
* `ICollectionView.CurrentItem` when selecting item right after the currently selected one, causing circular selection
* Invalid coercing of the item index ranges
* Invalid check to determine if an item is currently selected or not
🙃

fix(mvux): Fix selection not working properly

---

src/Uno.Extensions.Configuration/ServiceCollectionExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Oidc/OidcAuthenticationLoginPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Authentication/Oidc/OidcAuthenticationLoginViewModel.cs
testing/TestHarness/TestHarness.UITest/Ext/Authentication/Oidc/Given_Oidc.cs

GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno.extensions/issues/2224
- Bugfix
Configuration for unnamed sections aren't being loaded
Configuration works for both named and unnamed sections

fix: Correct configuration loading for unnamed sections

---

src/Uno.Extensions.Core/Option.T.cs
src/Uno.Extensions.Reactive.Messaging/MessengerExtensions.cs
src/Uno.Extensions.Reactive.Testing/ConstraintParts/ItemsConstraint.cs
src/Uno.Extensions.Reactive.Tests/Given_Feed.cs
src/Uno.Extensions.Reactive.Tests/Given_ListFeed.cs
src/Uno.Extensions.Reactive.Tests/Messaging/Given_Messaging.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_CoreFeedOperators.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_CoreListFeedOperators.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_CoreListStateOperators.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_CoreStateOperators.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_StateForEach.cs
src/Uno.Extensions.Reactive.Tests/Sources/Given_DynamicFeed.cs
src/Uno.Extensions.Reactive/Core/Feed.Extensions.cs
src/Uno.Extensions.Reactive/Core/Feed.cs
src/Uno.Extensions.Reactive/Core/IState.T.cs
src/Uno.Extensions.Reactive/Core/ListFeed.Extensions.cs
src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
src/Uno.Extensions.Reactive/Core/State.Extensions.cs
src/Uno.Extensions.Reactive/Operators/StateForEach.cs
src/Uno.Extensions.Reactive/Sources/Dynamic/DynamicFeed.cs
src/Uno.Extensions.Reactive/Utils/OptionExtensions.cs

closes https://github.com/unoplatform/uno.extensions/discussions/2170
linked https://github.com/unoplatform/uno/discussions/15349
Improve nullable support
* We cannot await a `Feed<Nullable<ValueType>>` + `Nullable<ValueType>` is globally not well supported
* Some operator names are confusing
* All method that is constrained by `where T : notnull` now have an overload for `Nullable<ValueType>`
* We standardized the naming "Value" (`T`); "Data" (`Option<T>`) and "Message" (`Message<T>`) operators on feeds

feat(mvux): Improve nullable support

---

src/Uno.Extensions.Reactive.Testing/FeedUITests.cs
src/Uno.Extensions.Reactive.Testing/TestDispatcher.cs
src/Uno.Extensions.Reactive.Tests/Utils/Dispatching/Given_DispatcherLocal.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
src/Uno.Extensions.Reactive/Utils/Dispatching/DispatcherLocal.cs
src/Uno.Extensions.Reactive/Utils/Events/EventManager.THandler.cs

closes https://github.com/unoplatform/uno/discussions/15654
Fix possible concurrency issue when changing ListState values before ui thread get it
If the source collection of the `BindableCollection` is switch while the UI thread is getting the current collection, then we miss some updates on it. This drives the UI to not get all collection changes events causing possible sync issues between UI and model.
lock

fix(mvux): Fix possible concurrency issue when changing ListState too fast

---

samples/MauiEmbedding/Directory.Packages.props
samples/Playground/Directory.Packages.props
src/Directory.Build.targets
src/Directory.Packages.props
src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.WinUI.csproj
src/Uno.Extensions.Authentication.Oidc/Uno.Extensions.Authentication.Oidc.WinUI.csproj
src/Uno.Extensions.Authentication.UI/Uno.Extensions.Authentication.WinUI.csproj
src/Uno.Extensions.Core.UI/Uno.Extensions.Core.WinUI.csproj
src/Uno.Extensions.Hosting.UI/Uno.Extensions.Hosting.WinUI.csproj
src/Uno.Extensions.Http.UI/Uno.Extensions.Http.WinUI.csproj
src/Uno.Extensions.Localization.UI/Uno.Extensions.Localization.WinUI.csproj
src/Uno.Extensions.Logging/Uno.Extensions.Logging.WinUI.csproj
src/Uno.Extensions.Maui.UI/Uno.Extensions.Maui.WinUI.csproj
src/Uno.Extensions.Maui.WinUI.Markup/Uno.Extensions.Maui.WinUI.Markup.csproj
src/Uno.Extensions.Navigation.Toolkit/Uno.Extensions.Navigation.Toolkit.WinUI.csproj
src/Uno.Extensions.Navigation.UI.Markup/Uno.Extensions.Navigation.WinUI.Markup.csproj
src/Uno.Extensions.Navigation.UI/Uno.Extensions.Navigation.WinUI.csproj
src/Uno.Extensions.Reactive.UI.Markup/Uno.Extensions.Reactive.WinUI.Markup.csproj
src/Uno.Extensions.Reactive.UI.Tests/Uno.Extensions.Reactive.WinUI.Tests.csproj
src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.WinUI.csproj
src/Uno.Extensions.Storage.UI/Uno.Extensions.Storage.WinUI.csproj
src/Uno.Extensions.Toolkit.UI/Uno.Extensions.Toolkit.WinUI.csproj

- closes #2060
- Bugfix
Windows fails due to the version of Microsoft.Graphics.Win2D getting linked out
Windows should be fine now as we directly have a dependency on the updated version of Microsoft.Graphics.2D

fixing issue with error on WinUI due to Win2D graphics

---

doc/Learn/Markup/Binding101.md
doc/Learn/Markup/DependencyPropertyBuilder.md
doc/Learn/Markup/HowTo-CustomMarkupProject-Theme.md
doc/Learn/Markup/HowTo-CustomMarkupProject-Toolkit.md
doc/Learn/Markup/HowTo-CustomMarkupProject-VisualStates.md

Changing `.Assign(out var fe)` usage for `.Name(out var fe)` in docs.

docs: Change Assign usage for Name

---

samples/MauiEmbedding/Directory.Build.props
samples/MauiEmbedding/Directory.Packages.props
samples/MauiEmbedding/MauiEmbedding.MauiControls/CustomEntry.cs
samples/MauiEmbedding/MauiEmbedding.MauiControls/MauiEmbedding.MauiControls.csproj
samples/MauiEmbedding/MauiEmbedding.Mobile/MauiEmbedding.Mobile.csproj
src/Directory.Packages.props
src/Uno.Extensions.Hosting.UI/ApplicationBuilder.cs
src/Uno.Extensions.Maui.UI/MauiEmbedding.apple.cs
src/Uno.Extensions.Navigation.UI/Navigators/ContentDialogNavigator.cs
src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs
src/maui-embedding.props
testing/TestHarness/Directory.Packages.props

GitHub Issue (If applicable): closes #2240 
- Bugfix
UIWindow not found using the old _window field. 
v5.2 of Uno adds multi-window support along with refactoring inner logic for Window management. 
the internal NativeWindow property now returns the UIWindow required for Maui Embedding

chore: Fixing reference to UIWindow

---

src/Directory.Packages.props
testing/TestHarness/Directory.Packages.props

- related #2246 
- Other... Please describe: Dependency Security Vulnerability
Targets MSAL 4.55.0 with security vulnerability
https://github.com/advisories/GHSA-x674-v45j-fwxw
Updates to latest patched version

chore: bump MSAL due to security vulnerability

---

src/Uno.Extensions.Reactive.UI/Utils/Dispatching/DispatcherQueueProvider.cs

Backport commit **289de0d88187dc6aa3983f8721df81e15e080c9f** that fixes #2274

[Backport Issue #2274] chore: Fix dispatcher callback cast exception on windows

---

src/Uno.Extensions.Maui.UI/build/Package.props
src/Uno.Extensions.Maui.UI/build/Package.targets

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/discussions/16645
- Bugfix
This change will ensure that the EnableMsixTooling property is modified properly, in the targets file (when OutputType is set) and only when we're not using the Uno.Sdk (which sets this value properly by itself).

fix: Only override the EnableMsixTooling for libraries

---

src/Uno.Extensions.Localization.UI/ResourceLoaderStringLocalizer.cs

GitHub Issue (If applicable): closes unoplatform/uno#16627
- Bugfix
`IStringLocalizer` not resolving on non-windows platforms
^ fixed
the null-coalesce is working poorly on these two

fix: ResourceLoaderStringLocalizer not resolving

---

src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.Immutable.cs
src/Uno.Extensions.Reactive.Tests/Collections/Tracking/Given_CollectionAnalyzer.ImmutableNonIList.cs
src/Uno.Extensions.Reactive.Tests/Presentation/Bindings/Given_Bindable.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/Bindable.cs
src/Uno.Extensions.Reactive/Utils/ReferenceEqualityComparer.cs

closes #https://github.com/unoplatform/uno/discussions/16581#discussioncomment-9531425
Fix invalid equality comparision of value types in bindable
`ValueType` are compared using ref-equality of boxed value ...
If this happen during the init of the bindable we might miss some `PropertyChanged` events and don't display the initial value of the backing `State`.
If `ValueType` we use the `EqualityComparer.Default`.

fix(mvux): Fix invalid equality comparision of value types in bindable

---

doc/Learn/Authentication/HowTo-MsalAuthentication.md

GitHub Issue (If applicable): #2356

docs: add warning for msal ClientId

---

src/Uno.Extensions.Navigation.UI/Navigators/NavigationViewNavigator.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundPage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundPage.xaml.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataBoundViewModel.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHomePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarHomeViewModel.cs

GitHub Issue (If applicable): closes #2300
- Bugfix
`FooterMenuItems` are not included in `NavigationMenuItems`, which wouldn't allow `FooterMenuItems` to work properly with `Navigation`.
Adding `FooterMenuItems`  to `NavigationMenuItems`

fix: Include FooterMenuItems to NavigationMenuItems

---

src/Uno.Extensions.Core.UI/Settings.cs
src/Uno.Extensions.Core/ISettings.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/ApplicationDataKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/KeyValueStorage/EncryptedApplicationDataKeyValueStorage.cs
src/Uno.Extensions.Storage.UI/ServiceCollectionExtensions.cs
testing/TestHarness/TestHarness.Shared/Ext/Core/Storage/StorageHostInit.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2241
- Bugfix
Accessing ApplicationData when running unpackaged on Windows throws an exception
ISettings is used as a fallback for when ApplicaitonData isn't available

fix: Using simple settings as alternative for key-value store when ApplicationData isn't available

---

doc/GettingStarted.md
doc/Learn/Authentication/HowTo-Authentication.md
doc/Learn/Navigation/Advanced/HowTo-AdvancedPageNavigation.md
doc/Learn/Navigation/Advanced/HowTo-UseNavigationView.md
doc/Learn/Navigation/Advanced/HowTo-UseTabBar.md
doc/Learn/Navigation/HowTo-DisplayItem.md
doc/Learn/Navigation/HowTo-DisplayMessageDialog.md
doc/Learn/Navigation/HowTo-NavigateBetweenPages.md
doc/Learn/Navigation/HowTo-NavigateInCode.md
doc/Learn/Navigation/HowTo-NavigateInXAML.md
doc/Learn/Navigation/HowTo-SelectValue.md

Many of Navigation docs still use references from older templates.
Updating examples and references with latest template changes

docs: Updating navigation docs to match latest template

---

src/Uno.Extensions.Reactive.UI/View/FeedView.Refresh.cs

closes https://github.com/unoplatform/uno.extensions/issues/2444
Fix possible cross threading exception in refresh command
Refresh command may remain `CanExecute = false` after a first execution
🙃

fix(mvux): Fix possible cross threading exception in refresh command

---

src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs

MVUX command executed on old model when hot-reloading
On HR we are keeping the previous instance of the command that captures the previous model instance
We always update the instance of the command

fix(hr): Fix MVUX command executed on old model when hot-reloading

---

src/Uno.Extensions.Hosting.UI/AppHostingEnvironment.cs
src/Uno.Extensions.Hosting/IHasAddressBar.cs
src/Uno.Extensions.Navigation.UI/BrowserAddressBarService.cs
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml
testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml.cs
testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj
testing/TestHarness/TestHarness.UITest/Ext/Navigation/PageNavigation/Given_PageNavigation.cs

- Bugfix
When navigating back to the first/main page the url doesn't update.
The URL now updates properly.

fix: Check if navigating back is possible to update state

---

src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs
src/Uno.Extensions.Authentication/TokenCacheExtensions.cs

GitHub Issue (If applicable): closes #2465 
- Feature
IdToken isn't being saved to token cache
IdToken is being saved to token cache

feat: Saving IdToken

---

README.md
samples/Playground/Playground/App.xaml.cs
samples/Playground/Playground/DebugHttpHandler.cs

GitHub Issue (If applicable): closes #2485
Document dropping support for UWP and migration to uno.sdk
Note: The actual breaking changes were in https://github.com/unoplatform/uno.extensions/pull/2437

docs: Dropping uwp and referencing uno.sdk

---

src/Uno.Extensions.Authentication.MSAL/GlobalUsings.cs
src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationBuilderExtensions.cs
src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationSettings.cs
src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.WinUI.csproj
src/Uno.Extensions.Authentication.MSAL/build/Package.targets
testing/TestHarness/TestHarness/Ext/Authentication/Msal/MsalAuthenticationHostInit.cs
testing/TestHarness/TestHarness/Ext/Authentication/Msal/MsalAuthenticationMultiHostInit.cs

fix: stub out msal methods on non-supported platforms

---

src/Uno.Extensions.Reactive.UI.Tests/Presentation/Bindings/Collections/Given_BindableCollection_Selection.cs
src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/SelectionFacet.cs

GitHub Issue (If applicable): closes #2473 
- Bugfix

fix: initialize Windows localSelection

---

doc/Learn/Markup/UnoThemes.md
doc/Learn/Maui/ThirdParty-GrapeCity.md
doc/Learn/Mvux/Advanced/Selection.md
doc/Learn/Mvux/ListFeeds.md

GitHub Issue (If applicable): part of https://github.com/unoplatform/private/issues/504, https://github.com/unoplatform/uno/issues/15048

docs: Fix Broken Links

---

src/Uno.Extensions.Reactive.Generator/Bindables/Inputs/BindableInput.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenTool_1.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenTool_2.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenTool_3.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenerator.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenerator_1.cs
src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenerator_2.cs
src/Uno.Extensions.Reactive.Generator/FeedsGenerator.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_BasicViewModel_Then_Generate.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_RecordWithList_Then_GenerateListOfBindable.cs
src/Uno.Extensions.Reactive.Tests/Generator/Given_ViewModel_Then_GenerateBindable.cs
src/Uno.Extensions.Reactive.Tests/IntegrationTests/Given_HotReload.cs
src/Uno.Extensions.Reactive.Tests/Presentation/Bindings/Given_BindableViewModelBase.cs
src/Uno.Extensions.Reactive/Config/BindableGenerationToolAttribute.cs

GitHub Issue (If applicable): closes #2460 
- Bugfix
Generated classes for MVUX would follow the pattern of XYZModel -> BIndableXYZModel
New generated classes will follow this new pattern XYZModel -> XYZViewModel

feat: update MVUX naming convention for generated classes

---

src/Uno.Extensions.Authentication.MSAL/build/Package.targets

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17910
- Bugfix

fix: Apply WebView2 workaround only if explicitly requested

---

src/Uno.Extensions.Storage.UI/FileStorage.cs

GitHub Issue (If applicable): closes #2423
- Bugfix
Warnings generated from initial template due to missing files
Downgraded warnings to information

chore: Adjusting warning

---

src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
src/Uno.Extensions.Navigation/RouteExtensions.cs
testing/TestHarness/TestHarness.Core/TestSections.cs
testing/TestHarness/TestHarness.UITest/Constants.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/RoutesNavigation/Given_RoutesNavigation.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/HomePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/HomePage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/ItemsPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/ItemsPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/ListTemplate.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/ListTemplate.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/MyControlView.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/MyControlView.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/RoutesNavigationHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/RoutesNavigationMainPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/RoutesNavigationMainPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/RoutesNavigationRegisterHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/SamplePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/SamplePage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/SecondPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/SecondPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/RoutesNavigation/ShellViewModel.cs

GitHub Issue (If applicable): closes #2382 
- Bugfix

fix: App blanks out when navigating to invalid route

---

src/Uno.Extensions.Reactive.Tests/Uno.Extensions.Reactive.Tests.csproj
src/Uno.Extensions.Reactive/Config/BindableGenerationToolAttribute.cs

- Bugfix
Set the default version for the BindableGenerationTool to the previous version (Version 2) to allow backward compatibility.

Fix(mvux) set name tool generation version

---

src/Uno.Extensions.Navigation.UI/Controls/FrameView.xaml.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/PageNavigation/Given_PageNavigation.cs
testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml.cs

GitHub Issue (If applicable): closes #2522
- Bugfix
`FrameView` would inherit DataContext from parents and propagate it to child pages.
Set `FrameView.DataContext` to `null` to avoid DataContext inheritance and propagation.

fix: Prevent FrameView DataContext propagation

---

doc/Learn/Mvux/Advanced/Selection.md
doc/Learn/Mvux/ListStates.md
doc/Learn/Mvux/States.md
src/Uno.Extensions.Reactive.Messaging/ListStateExtensions.cs
src/Uno.Extensions.Reactive.Messaging/MessengerExtensions.cs
src/Uno.Extensions.Reactive.Messaging/StateExtensions.cs
src/Uno.Extensions.Reactive.Tests/Messaging/Given_Messaging.cs
src/Uno.Extensions.Reactive.Tests/Operators/Given_StateForEach.cs
src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
src/Uno.Extensions.Reactive/Core/State.Extensions.cs
src/Uno.Extensions.Reactive/Core/State.T.cs
src/Uno.Extensions.Reactive/Operators/StateForEach.cs

GitHub Issue (If applicable): closes #2461 
- Feature
- Add `ForEach` operator Fluent friendly for `IState`
- Add `ForEach` operator Fluent friendly for `IListState`
- Add `Observe` operator Fluent friendly
- Add `ForEachData` operator Fluent friendly
- Marked `ForEachAsync` Obsolete in favor of `ForEach`
- Marked `ForEachDataAsync` Obsolete in favor of `ForEachData`

feat: Implement FluentAPI

---

doc/Learn/Mvux/toc.yml

The "MVUX -> Advanced Topics -> Messaging " is not showing on the docs Menu

docs: fix messaging not showing from menu

---

src/Uno.Extensions.Reactive.Tests/Operators/Given_StateForEach.cs

- Other... Please describe:
Workaround for a test that is failing in the CI.

chore: workaround for flaky test

---

doc/Learn/Mvux/Advanced/Messaging.md

docs: update reactive messaging

---

doc/Learn/Navigation/HowTo-Regions.md
doc/Learn/Navigation/toc.yml

GitHub Issue (If applicable): closes #2159
New page "How To: Define Regions"

docs: Regions and Navigators

---

doc/Learn/Navigation/Advanced/HowTo-IRouteNotifier.md
doc/Learn/Navigation/toc.yml

GitHub Issue (If applicable): closes #1679
Add docs to the Advanced section of Navigation regarding `IRouteNotifier` and how to access `INavigator` through the `RouteChanged` event.

docs: HowTo IRouteNotifier

---

testing/TestHarness/TestHarness.UITest/Ext/Authentication/Custom/Given_Custom.cs

chore: Add comment about CustomAuthenticationProvider test

---

src/tfms-ui-maui.props
src/tfms-ui-winui.props

Avoids error:
> ##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.6.240829007\buildTransitive\Microsoft.WindowsAppSDK.targets(76,9): Error : This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref 10.0.19041.38 or later.
>     Please update to .NET SDK 6.0.134, 6.0.426, 8.0.109, 8.0.305 or 8.0.402 (or later).
>     Or add a temporary Microsoft.Windows.SDK.NET.Ref reference which can be added with:
```xml
<PropertyGroup>
<WindowsSdkPackageVersion>10.0.19041.38</WindowsSdkPackageVersion>
</PropertyGroup>
```

chore: Add WindowsSdkPackageVersion workaround

---

testing/TestHarness/TestHarness.UITest/Ext/Navigation/Apps/Chefs/Given_Apps_Chefs.cs
testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsFavoriteRecipesPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHomeModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHomePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsLoginPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsWelcomePage.xaml

GitHub Issue (If applicable): https://github.com/unoplatform/uno.chefs/issues/1151
- Other... Please describe:
- Adds navigation in TestHarness for the layout bug following navigation from Chefs.
- Adds a UI test that reproduces the behavior.

chore: add chefs FavoriteRecipes failing navigation scenario to the TestHarness

---

testing/TestHarness/Directory.Packages.props

canaries are failing due to a missing packageversion

chore: add missing packageversions

---

testing/TestHarness/Directory.Packages.props

canaries are failing due to downgrade, add package reference so that it can be updated

chore: Add Uno.Extensions.Logging.OSLog to TestHarness

---

doc/Learn/Mvux/Advanced/Messaging.md

GitHub Issue (If applicable): closes #2556 

docs mvux messaging observe overloads

---

doc/Learn/Mvux/Advanced/Pagination.md
doc/Learn/Mvux/Advanced/Selection.md
doc/Reference/Reactive/feed.md
doc/Reference/Reactive/listfeed.md
doc/Reference/Reactive/state.md

Some links pointing to MVUX content are dead.

docs: fix MVUX dead links

---

doc/Learn/Mvux/FeedView.md

docs: Reactive FeedView updates

---

Uno.Extensions.sln
doc/Learn/Authentication/HowTo-OidcAuthentication.md
samples/Playground/Directory.Packages.props
src/Directory.Packages.props
src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationBuilderExtensions.cs
src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs
src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationSettings.cs
src/Uno.Extensions.Authentication.Oidc/WebAuthenticatorBrowser.cs
testing/TestHarness/Directory.Packages.props

Fixes https://github.com/unoplatform/uno.extensions/issues/2588
Fixes https://github.com/unoplatform/uno.extensions/issues/2590
This PR will allow the application to update the native `OidcClientOptions` for advanced scenario, like settings which are either advanced or not supported by the version for which Uno Extensions is build (which is the case for `DisablePushedAuthorization` setting).
A new `UpdateOidcClientOptions()` on the builder let the application interact directly with the setting object.
The application can now rely on the auto-discovery of the Redirect URI by the Web Auth Broker. It's opt-in, except for Wasm because it was already using it - to stay backward compatible.

[Oidc-Auth] Allow native OidcClientOptions settings + Redirect URI auto-discovery

---

src/Directory.Packages.props

This is required in order to prevent version conflicts with uno.sdk which is rolling back winappsdk version to the latest version currently supported by the Store
See: https://github.com/microsoft/WindowsAppSDK/issues/4480 is resolved

fix: Reduce winappsdk version dependency

---

SamplePackages.props
global.json
samples/MauiEmbedding/Directory.Packages.props
samples/MauiEmbedding/MauiEmbedding/MauiEmbedding.csproj
samples/Playground/Directory.Build.props
samples/Playground/Directory.Packages.props
samples/Playground/Playground/Playground.csproj
src/Uno.Extensions.Maui.UI/build/Package.targets
src/maui-embedding.props
testing/TestHarness/Directory.Packages.props
testing/TestHarness/TestHarness/TestHarness.csproj

In order to keep the samples apps and testing app dependency versions separate from the Uno.Sdk version used by the Extension library, we have moved to using Uno.Sdk.Private for the SDK of the samples/testing projects.
This PR adds that to the global.json and cleans up the package versions being used across the apps in the solution

build: use uno.sdk.private for samples/testing

---

src/Directory.Packages.props
src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationProvider.cs
src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.WinUI.csproj
src/Uno.Extensions.Authentication.MSAL/build/Package.targets

fix: Add msal fix for MSALClientException

---

build/ci/stage-build-packages.yml
build/ci/stage-build-windows.yml
src/Directory.Packages.props
testing/TestHarness/Directory.Packages.props

Fixes a build issue with System.Xaml missing in the XAML pass 1.

fix: Bump msal for fix winappsdk issue

---

doc/Learn/ThemeService/HowTo-UseThemeService.md

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/19077

docs: Adjust registration specifics for `ThemeService`

---

doc/Learn/KeyEquality/rules.md
doc/Learn/KeyEquality/toc.yml

KeyEquality docs are not showing on the side menu. It was missing the toc.yml file.

docs: improve KeyEquality docs

---

doc/Learn/Authentication/HowTo-MsalAuthentication.md
doc/Learn/UpdatingExtensions.md
doc/toc.yml
src/Directory.Packages.props
src/Uno.Extensions.Authentication.MSAL/HostBuilderExtensions.cs
src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationProvider.cs
src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.WinUI.csproj
src/Uno.Extensions.Hosting.UI/ApplicationBuilder.cs
src/Uno.Extensions.Hosting.UI/IApplicationBuilder.cs
testing/TestHarness/TestHarness/BaseHostInitialization.cs
testing/TestHarness/TestHarness/BaseTestSectionPage.cs
testing/TestHarness/TestHarness/Ext/Authentication/Msal/MsalAuthenticationHostInit.cs
testing/TestHarness/TestHarness/Ext/Authentication/Msal/MsalAuthenticationMultiHostInit.cs
testing/TestHarness/TestHarness/Ext/Authentication/Msal/MsalAuthenticationSettingsHostInit.cs
testing/TestHarness/TestHarness/IHostInitialization.cs

GitHub Issue (If applicable): closes #2654
- Feature

feat: Add back support for MSAL auth through WAM

---

src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs
testing/TestHarness/TestHarness.Core/TestSections.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/AddressBar/Given_AddressBar.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomeModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomePage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarMainPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarMainPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/Constants.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/ShellViewModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/appsettings.addressbar.json
testing/TestHarness/TestHarness/TestHarness.csproj

GitHub Issue (If applicable): closes #2607
- Bugfix
When specifying a route on the addressbar (e.g., https://url/Main) the first navigation is triggered in two ways. This behavior can be observed on lines 36 and 44 in the following file: [FrameworkElementExtensions.cs](https://github.com/unoplatform/uno.extensions/blob/main/src/Uno.Extensions.Navigation.UI/FrameworkElementExtensions.cs). This way the `initialNavigation` navigates to `""` which eventually navigates to "Main" because it's the default route and `start` navigates to "Main" because it was the route specified, causing a double navigation.
We check if the route navigated to is the same to the one provided via addressbar, if so we don't navigate.
Please check if your PR fulfills the …

fix: Navigate once when starting app with same route as navigated

---

doc/Learn/Mvux/ListStates.md
src/Uno.Extensions.Reactive.Tests/Operators/Given_CoreListStateOperators.cs
src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs

GitHub Issue (If applicable): closes #2582 
- Feature
To update an item, we need to do something like ListState.UpdateAllAsync(t => t.KeyEquals(newT), newT);

feat: (mvux) Add new UpdateItemasync Extension Method

---

doc/GettingStarted.md
doc/Learn/Authentication/AuthenticationOverview.md
doc/Learn/Configuration/ConfigurationOverview.md
doc/Learn/Hosting/HostingOverview.md
doc/Learn/Hosting/HowTo-HostingSetup.md
doc/Learn/Http/HttpOverview.md
doc/Learn/Localization/LocalizationOverview.md
doc/Learn/Logging/LoggingOverview.md
doc/Learn/Navigation/NavigationOverview.md
doc/Learn/Serialization/SerializationOverview.md
doc/Learn/Storage/StorageOverview.md
doc/Learn/Validation/ValidationOverview.md
doc/Learn/includes/existing-app.md

GitHub Issue (If applicable): closes #2655

docs: Improve Installing Extensions docs

---

src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/AddressBar/Given_AddressBar.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomeModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarSecondModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarSecondPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarSecondPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarUserService.cs

GitHub Issue (If applicable): closes #2672
- Bugfix

fix: Include Data to navigation for addressbar

---

testing/TestHarness/TestHarness.UITest/Ext/Navigation/Dialogs/Given_ContentDialog.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/Dialogs/Given_FlyoutDialog.cs
testing/TestHarness/TestHarness/Ext/Navigation/Dialogs/ContentDialogsPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/Dialogs/ContentDialogsPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/Dialogs/DialogsFlyoutsPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/Dialogs/DialogsHostInit.cs

Fixes Given_ContentDialog and Given_FlyoutDialog failing tests on #2494

chore: Adjust tests for android

---

src/Uno.Extensions.Configuration/HostBuilderExtensions.cs
src/Uno.Extensions.Configuration/ServiceCollectionExtensions.cs
src/Uno.Extensions.Configuration/WritableOptions.cs

closes #2719
Cover cases for serialization in writableoptions to ensure usage of source gen

fix: ensure writableoptions uses source gen serialization

---

version.json

closes #2719
Cover cases for serialization in writableoptions to ensure usage of source gen
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/5.3, based on #2727

Version bump after 5.3 release branch

---

doc/GettingStarted.md
doc/Learn/Markup/HowTo-CustomMarkupProject-Theme.md
src/Uno.Extensions.Hosting.UI/ApplicationBuilder.cs
testing/TestHarness/TestHarness/App.xaml.cs

GitHub Issue (If applicable): part of https://github.com/unoplatform/uno-private/issues/922
- Bugfix
`Window.Current` is used
`Window.Current` is avoided on Uno.WinUI

fix: Adjust `Window.Current` usages

---

build/ci/stage-build-uitests-wasm.yml

Related doc - https://devblogs.microsoft.com/devops/upcoming-updates-for-azure-pipelines-agents-images/
Since UI Tests - WebAssembly has been failing recently we couldn't merge any PR's

fix: Deprecated vmImage

---

doc/Reference/Navigation/NavigationRegion.md
src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.WinUI.csproj
src/Uno.Extensions.Authentication.Oidc/Uno.Extensions.Authentication.Oidc.WinUI.csproj
src/Uno.Extensions.Authentication.UI/Uno.Extensions.Authentication.WinUI.csproj
testing/TestHarness/TestHarness/Ext/Navigation/NavigationView/NavigationViewHomePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/NavigationView/NavigationViewHomePage.xaml.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2652
- Bugfix
`NavigationView.SettingsItem` + UENavigation is not documented
Added docs and updated sample

docs: `NavigationView.SettingsItem` with Navigation Extensions

---

src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
src/Uno.Extensions.Navigation/RouteExtensions.cs
testing/TestHarness/TestHarness.Core/TestSections.cs
testing/TestHarness/TestHarness.UITest/Ext/Navigation/AddressBar/Given_AddressBar.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarCoffeeModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarCoffeePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarCoffeePage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomeModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarHomePage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarJSImports.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarMainPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarNestedDefaultHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarNestedHostInit.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarRootModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarRootPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarRootPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarSecondPage.xaml
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/AddressBarSecondPage.xaml.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/DefaultShellViewModel.cs
testing/TestHarness/TestHarness/Ext/Navigation/AddressBar/ShellViewModel.cs

GitHub Issue (If applicable): closes #2772
- Bugfix
The `Combine` method was modifying the original `Route.Data` dictionary directly.  
Since `Route` is a `record`, using `with` is expected to create a new instance without affecting the original.  
However, because `Combine` updated the internal dictionary by reference, it caused unexpected side effects - the original `Route` was being changed indirectly.
The new `Combine` method creates a new dictionary and copies entries from both `data` and `childData`.  
This way, the original inputs stay untouched, and using `with` actually returns a clean, independent `Route` instance, as expected.

fix: Clear nav query params when navigating

---

version.json

BREAKING CHANGE: The Uno SDK Dependency has been updated to 6.0, which includes breaking changes.
This is an automated version bump of the  **main** branch after the creation of the release branch release/stable/6.0, based on #2788

Version bump after 6.0 release branch

---

src/Uno.Extensions.Navigation/NavigatorExtensions.cs

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/20838
- Bugfix
ShowMessageDialogAsync() currently allows for `content` and `title` to be null. However, when reaching [the creation of the `MessageDialog` in uno](https://github.com/unoplatform/uno/blob/6884f4b4aeda24d1aada7ca59e3fefc3a23fbe3d/src/Uno.UWP/UI/Popups/MessageDialog.cs#L30-L45) there is a null argument exception.
In effort to keep allowing the user to leave `content` and `title` null, we can simply resolve them as empty strings in Extensions.

fix: ShowMessageDialogAsync nullables

---

src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenTool_3.cs
src/Uno.Extensions.Reactive.Tests/IntegrationTests/Given_HotReload.cs
src/Uno.Extensions.Reactive/Core/Internal/StateStore.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableViewModelBase.HotReload.cs
src/Uno.Extensions.Reactive/Presentation/Bindings/BindableViewModelBase.cs

closes https://github.com/unoplatform/studio/issues/86
Fix ablity to HR when adding/removing feed properties in model
State is propagated only considering the original model properties
State is propagated incrementally from each model, using a global cache of properties to ensure proper re-use / update

fix(MVUX): Fix ablity to HR when adding/removing feed properties in model

---

build/ci/cspell.json

Added "MESCIUS" the word list
GitHub Issue (If applicable): (https://github.com/unoplatform/uno.extensions/pull/2730)
GrapeCity changed its name to MESCIUS and we need to update that name change across docs. Starting with adding MESCIUS to cspell list
MESCIUS added to word list

docs: Add MESCIUS to cspell dictionary

---

build/ci/templates/nuget-publish-dev.yml

Updated condition to allow publishing for both `master` and `release/stable/*` branches for the Uno Internal Dev Feed, while continuing to skip pull request builds. As manual release review check is done before this step for `release/stable/*` branches anyway: 
https://github.com/unoplatform/uno.extensions/blob/ff7a19140bd736ab16edafdc237efbaee69afec0/build/ci/publish/publish-nuget-prod-dev.yml#L4

ci: Adjust condition for the "Publish to Uno Dev Feed" step and for using correct default branch
