- samples/Commerce/Commerce.Shared/Views/CartPage.xaml
- samples/Commerce/Commerce.Shared/Views/FilterFlyout.xaml
ninja-fix: temporary workaround for [x] button not appearing (foreground not set)
> fix: back navigation from cart flyout

- samples/Commerce/Commerce.Shared/Views/DealsPage.xaml
- samples/Commerce/Commerce.Shared/Views/FilterFlyout.xaml
- samples/Commerce/Commerce.Shared/Views/ProductDetailsPage.xaml
- samples/Commerce/Commerce.Shared/Views/ProductsPage.xaml
> fix: Stop setting ShowAsMonochrome to False for NavigationBar Buttons

- samples/Commerce/Commerce.Shared/Styles/NavigationBar.xaml
- samples/Commerce/UWP/Commerce.Droid/Commerce.Droid.csproj
- samples/Commerce/UWP/Commerce.Skia.Gtk/Commerce.Skia.Gtk.csproj
- samples/Commerce/UWP/Commerce.Skia.WPF/Commerce.Skia.WPF.csproj
- samples/Commerce/UWP/Commerce.UWP/Commerce.Uwp.csproj
- samples/Commerce/UWP/Commerce.Wasm/Commerce.Wasm.csproj
- samples/Commerce/UWP/Commerce.iOS/Commerce.iOS.csproj
- samples/Commerce/UWP/Commerce.macOS/Commerce.macOS.csproj
- samples/Commerce/WinUI/Commerce.Droid/Commerce.Droid.csproj
- samples/Commerce/WinUI/Commerce.Skia.Gtk/Commerce.Skia.Gtk.csproj
- samples/Commerce/WinUI/Commerce.Skia.WPF/Commerce.Skia.WPF.csproj
- samples/Commerce/WinUI/Commerce.Wasm/Commerce.Wasm.csproj
- samples/Commerce/WinUI/Commerce.Windows.Desktop/Commerce.Windows.Desktop.csproj
- samples/Commerce/WinUI/Commerce.iOS/Commerce.iOS.csproj
- samples/Commerce/WinUI/Commerce.macOS/Commerce.macOS.csproj
- src/Uno.Extensions.Navigation.Toolkit/Uno.Extensions.Navigation.Toolkit.UI.csproj
- src/Uno.Extensions.Navigation.Toolkit/Uno.Extensions.Navigation.Toolkit.WinUI.csproj
> fix: update toolkit for new modal-aware navbar

- samples/Commerce/Commerce.Shared/ViewModels/ShellViewModel.cs
- samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml.cs
- src/Uno.Extensions.Navigation.Toolkit/Controls/TabBarItemRequestHandler.cs
- src/Uno.Extensions.Navigation.UI/Controls/ActionRequestHandlerBase.cs
- src/Uno.Extensions.Navigation.UI/Controls/NavigationViewItemRequestHandler.cs
- src/Uno.Extensions.Navigation.UI/Controls/SelectorRequestHandler.cs
- src/Uno.Extensions.Navigation.UI/NavigationRequestExtensions.cs
- src/Uno.Extensions.Navigation.UI/Navigator.cs
- src/Uno.Extensions.Navigation.UI/NavigatorExtensions.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ContentControlNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/DialogNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/PopupNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/SelectorNavigator.cs
- src/Uno.Extensions.Navigation.UI/ResponseNavigator.cs
- src/Uno.Extensions.Navigation.UI/RouteConstants.cs
- src/Uno.Extensions.Navigation.UI/RouteExtensions.cs
- src/Uno.Extensions.Navigation.UI/RouteResolver.cs
- src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs
- src/Uno.Extensions.Navigation/Route.cs
- src/Uno.Extensions.Navigation/Schemes.cs
GitHub Issue (If applicable): #277 
- Bugfix
The term Scheme is used to refer to first part of route for navigation
Qualifier is used in place of scheme
> feat: Renaming Scheme to Qualifier

- samples/Commerce/Commerce.Shared/App.xaml.cs
- samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions-net6/MyExtensionsApp.Shared/App.xaml.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/App.xaml.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/App.xaml.cs
Small fix to remove unnecessary async keyword
Also removes block of code for updating address bar (WASM), which is now part of the navigation extensions
> fix: Addressing async void method

- samples/Playground/Playground/Playground/Playground.Shared/Models/Widget.cs
- samples/Playground/Playground/Playground/Playground.Shared/ViewModels/AdHocViewModel.cs
- samples/Playground/Playground/Playground/Playground.Shared/Views/AdHocPage.xaml
- src/Uno.Extensions.Serialization/ISerializer.cs
- src/Uno.Extensions.Serialization/IStreamSerializer.cs
- src/Uno.Extensions.Serialization/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Serialization/SystemTextJsonStreamSerializer.cs
GitHub Issue (If applicable): #325 
- Feature
ISerializer is untyped
ISerializer<T> is typed, so eliminates casting step in usage
> feat: Adding generic version of ISerializer

- samples/Commerce/Commerce.Shared/App.xaml.cs
- samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
- samples/Playground/Playground/Playground/Playground.Shared/ViewModels/SimpleViewModel.cs
- samples/Playground/Playground/Playground/Playground.Shared/Views/DialogsPage.xaml.cs
- samples/Playground/Playground/Playground/Playground.Shared/Views/SimpleDialog.xaml
- src/Uno.Extensions.Navigation.Toolkit/Navigators/TabBarNavigator.cs
- src/Uno.Extensions.Navigation.UI/IWindow.cs
- src/Uno.Extensions.Navigation.UI/IWindowProvider.cs
- src/Uno.Extensions.Navigation.UI/Navigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ContentControlNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ContentDialogNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/DialogNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/NavigationViewNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/PopupNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/SelectorNavigator.cs
- src/Uno.Extensions.Navigation.UI/ResponseNavigator.cs
- src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs
- src/Uno.Extensions.Navigation.UI/WindowProvider.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UI/App.xaml.cs
N/A
- Code style update (formatting)
> fix: Adjusting naming

- build/Install-WindowsSdkISO.ps1
Fixes broken build due to missing windows sdk location
> fix: Correct win sdk location

- samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
- samples/Playground/Playground/Playground/Playground.Shared/Playground.Shared.projitems
- samples/Playground/Playground/Playground/Playground.Shared/Playground.Shared.shproj
- samples/Playground/Playground/Playground/Playground.Shared/Views/FlyoutsPopupsDrawerPage.xaml
- samples/Playground/Playground/Playground/Playground.Shared/Views/FlyoutsPopupsDrawerPage.xaml.cs
- samples/Playground/Playground/Playground/Playground.Shared/Views/HomePage.xaml
- src/Uno.Extensions.Navigation.Toolkit/Navigators/DrawerControlNavigator.cs
- src/Uno.Extensions.Navigation.Toolkit/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Navigation.UI/RouteExtensions.cs
- src/Uno.Extensions.Navigation/RouteExtensions.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/App.xaml.cs
GitHub Issue (If applicable): #396
- Feature
Drawer needs to be manually opened and closed
Can use navigation to open and close the drawer. 
> feat: Open/Close drawer using navigation

- src/Uno.Extensions.Navigation.UI/Controls/NavigationViewRequestHandler.cs
- src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs
- Feature
Navigation.Request attached property has to be added to each navigationviewitem
Navigation.Request attached property can be set on the NavigationView to define the navigation for each menuitem
> feat: Adding NavigationViewRequestHandler

- samples/Playground/Playground/Playground/Playground.Shared/Views/CodeBehindPage.xaml
- samples/Playground/Playground/Playground/Playground.Shared/Views/CodeBehindPage.xaml.cs
- src/Uno.Extensions.Navigation.UI/NavigatorExtensions.cs
- src/Uno.Extensions.Navigation/NavigationResponseExtensions.cs
- src/Uno.Extensions.Navigation/NavigatorExtensions.cs
> feat: Adding GetDataAsync extension method

- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/App.xaml.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/AppInfo.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Models/Cart.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Models/Product.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Models/Profile.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Models/ProfileModel.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Models/Review.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/ReactiveClasses.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Services/ProductServices.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/ViewModels/Credentials.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/ViewModels/Filters.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/ViewModels/LoginViewModel.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/ViewModels/ShellViewModel.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Views/CheckoutPage.xaml
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/Views/FilterPage.xaml
- Code style update (formatting)
Remove a number of null reference warnings
> chore: Code tidyup 

- samples/Commerce/Commerce.Shared/App.xaml.cs
- samples/Commerce/Commerce.Shared/ReactiveClasses.cs
- samples/Playground/Playground/Playground/Playground.Shared/App.xaml.cs
- src/Uno.Extensions.Navigation.UI/RouteResolver.cs
- src/Uno.Extensions.Navigation/ViewMap.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/App.xaml.cs
- src/Uno.Extensions.Templates/content/unoapp-samples-commerce/MyExtensionsApp.Shared/ReactiveClasses.cs
GitHub Issue (If applicable): #398
- Code style update (formatting)
To determine which view type to use during navigation the DynamicView property on the viewmap is used
To determine which view type is used during navigation use the ViewSelector property
> feat: Renaming DynamicView to ViewSelector

- src/Directory.Build.props
chore: Enable packing of the reactive testing project
> chore: Enable packing of the reactive testing project

- src/Uno.Extensions.Reactive.Generator/Bindables/BindableGenerationContext.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/BindableViewModelGenerator.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/IMappedMember.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableFromFeedField.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableFromFeedProperty.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/PropertyFromFeedField.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/PropertyFromFeedProperty.cs
- src/Uno.Extensions.Reactive.Tests/Generator/Given_BasicViewModel_Then_Generate.cs
- src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs
- src/Uno.Extensions.Reactive.Tests/Given_Feed.cs
- src/Uno.Extensions.Reactive.Tests/Given_ListFeed.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/ValueAttribute.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/AsyncCommand.SubCommand.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/AsyncCommand.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/Command.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CommandBuilder.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CommandConfig.cs
- src/Uno.Extensions.Reactive/Core/Feed.Extensions.cs
- src/Uno.Extensions.Reactive/Core/Feed.cs
- src/Uno.Extensions.Reactive/Core/ListFeed.Extensions.cs
[Feed] BindableVM: Public methods are now exposed as ICommand by default
> [Feed] BindableVM: Public methods are now exposed as ICommand by default

- samples/Playground/Playground/Playground/Playground.Shared/App.xaml.host.cs
- src/Uno.Extensions.Navigation.UI/RouteResolver.cs
- src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
- Feature
All routes needed to be defined as a routemap
For simple views (eg a Flyout) where there's no additional route info required, a routemap is no longer required.
> feat: Automatically create routeinfo from viewmap

- README.md
Add a synced list of the contributors for README.md
> docs: Add a synced list of the contributors for README.md

- src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.UI.WinUI.csproj
- src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.UI.csproj
fix: Make sure to not compile the reactive packages on unsupported platforms
> fix: Make sure to not compile the reactive packages on unsupported platforms

- doc/Extensions/Serialization/HowTo-Serialization.md
> docs: Add serialization how-to

- doc/toc.yml
> docs: Adjust TOC.yml based on latest plan

- doc/Extensions/DependencyInjection/HowTo-CommunityToolkit.md
- doc/Extensions/DependencyInjection/HowTo-DependencyInjectionSetup.md
- doc/Extensions/GettingStarted/HowTo-UsingUnoExtensions.md
- doc/Extensions/Hosting/HowTo-HostingSetup.md
- doc/Extensions/Localization/HowTo-Localization.md
- doc/Navigation/HowTo-DisplayItem.md
- doc/Navigation/HowTo-DisplayMessageDialog.md
- doc/Navigation/HowTo-NavigateBetweenPages.md
- doc/Navigation/HowTo-NavigateInCode.md
- doc/Navigation/HowTo-NavigateInXAML.md
- doc/Navigation/HowTo-SelectValue.md
- doc/Navigation/HowTo-ShowFlyout.md
GitHub Issue (If applicable): N/A
> fix(docs): Show info banners

- doc/Learn/Tutorials/Configuration/HowTo-Configuration.md
- doc/toc.yml
> docs: Add Configuration tutorial

- src/Uno.Extensions.Reactive.Tests/Operators/Given_StateForEach.cs
- src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
- src/Uno.Extensions.Reactive/Core/State.Extensions.cs
- src/Uno.Extensions.Reactive/Operators/StateForEach.cs
Rename State.Execute to State.ForEachAsync
> feat(feed): Rename State.Execute to State.ForEachAsync

- src/Uno.Extensions.Reactive.Generator/Bindables/BindableGenerationContext.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/BindableGenerator.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/BindableViewModelGenerator.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromFeedOfListField.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromFeedOfListProperty.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromListFeedField.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/BindableListFromListFeedProperty.cs
- src/Uno.Extensions.Reactive.Generator/N.cs
- src/Uno.Extensions.Reactive.Generator/Utils/RoslynExtensions.cs
- src/Uno.Extensions.Reactive.Tests/Generator/Given_BasicViewModel_Then_Generate.cs
- src/Uno.Extensions.Reactive.Tests/Operators/Given_StateForEach.cs
- src/Uno.Extensions.Reactive.slnf
- src/Uno.Extensions.Reactive/Core/ListFeed.Extensions.cs
- src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
- src/Uno.Extensions.Reactive/Core/State.Extensions.cs
- src/Uno.Extensions.Reactive/Operators/FeedToListFeedAdapter.cs
- src/Uno.Extensions.Reactive/Operators/StateForEach.cs
feat(feed): Make Feed<T[]> automatically exposed to binding as IListFeed<T>
>  feat(feed): Make Feed<T[]> automatically exposed to binding as IListFeed<T>

- samples/Commerce/UWP/Commerce.Droid/Properties/AndroidManifest.xml
- samples/Commerce/WinUI/Commerce.Droid/Properties/AndroidManifest.xml
- samples/Playground/Playground/Playground/Playground.Shared/ViewModels/SecondViewModel.cs
- src/Uno.Extensions.Http/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Navigation.UI/Navigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/MessageDialogNavigator.cs
- src/Uno.Extensions.Navigation/NavigationRequest.cs
- src/Uno.Extensions.Reactive/Uno.Extensions.Reactive.csproj
GitHub Issue (If applicable): #497 
- Feature
NavigationRequest doesn't have a reference to originating INavigator
NavigationRequest has a reference to originating INavigator
- [ X ] Contains **NO** breaking changes
> feat: Adding INavigator Source property to NavigationRequest

- src/Uno.Extensions.Reactive.UI/Uno.Extensions.Reactive.UI.csproj
- src/Uno.Extensions.Reactive/Uno.Extensions.Reactive.csproj
chore(feed): Fix error in transient system packages resolution on WinUI
> chore(feed): Fix error in transient system packages resolution on WinUI

- samples/Commerce/Commerce.UI/App.xaml.host.cs
- samples/Commerce/Commerce/Business/ProductServices.cs
- samples/Commerce/Commerce/ViewModels/DealsViewModel.cs
- samples/Commerce/Extensions.props
feat(commerce): Auto refresh Favorites list when adding / removing favorite
> feat(commerce): Auto refresh Favorites list

- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Facets/BindableCollectionExtendedProperties.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/BasicView.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/FlatView.cs
- src/Uno.Extensions.Reactive/Collections/Facades/Slice/SliceEnumerator.cs
chore: Misc typos and alignments
> chore: Misc typos and alignments

- README.md
GitHub Issue (If applicable): #514
- Bugfix
Links on Readme broken
Updated Readme and fixed links
- [N/A ] Tested code with current [supported SDKs](../README.md#supported)
- [ X ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [N/A ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [N/A ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. …
> fix: Updated readme and links

- src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
- src/Uno.Extensions.Navigation.UI/RouteExtensions.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceDealsPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHostInit.cs
- testing/TestHarness/TestHarness.Shared/PageExtensions.cs
- testing/TestHarness/TestHarness.sln
Fixes issue with responsive navigation for nested tabs in Commerce app
> fix: Address edge scenario for responseive navigation

- src/Uno.Extensions.Reactive.Tests/Core/Given_CompositeRequestSource.cs
- src/Uno.Extensions.Reactive.Tests/Core/Given_NoneRequestSource.cs
- src/Uno.Extensions.Reactive.Tests/Core/Given_RequestSource.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindableListFeed.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Services/PaginationService.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/CoercingRequestManager.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/IContextRequest.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/IRequestSource.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSource.Composite.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSource.None.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/RequestSource.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/SequentialRequestManager.cs
- src/Uno.Extensions.Reactive/Core/Internal/SourceContext.cs
- src/Uno.Extensions.Reactive/Sources/AsyncFeed.cs
fix(feeds): Fix possible threading issues while sending requests
> fix(feeds): Fix possible threading issues while sending requests

- samples/Commerce/Commerce/ViewModels/CartViewModel.cs
- samples/Commerce/Commerce/ViewModels/DealsViewModel.cs
Add More/Less and RemoveFromFav commands
> feat(commerce): Add More/Less and RemoveFromFav commands

- src/Uno.Extensions.Navigation.UI/Navigator.cs
- src/Uno.Extensions.Navigation/RouteExtensions.cs
- testing/TestHarness/TestHarness.Core/TestSections.cs
- testing/TestHarness/TestHarness.Shared/App.xaml
- testing/TestHarness/TestHarness.Shared/App.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceMainPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceShellControl.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceShellControl.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceShellControlHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/ToDo/ToDoHomePage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHomePage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHomePage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHomeViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewMainPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewMainPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewSettingsPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewSettingsPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewSettingsViewModel.cs
- testing/TestHarness/TestHarness.Shared/TestFrameHost.xaml
- testing/TestHarness/TestHarness.Shared/TestFrameHost.xaml.cs
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj
GitHub Issue (If applicable): #519
- Bugfix
Using custom ShellControl prevent navigation from working, or causes iterative navigation (ie keeps navigating to Home in nested child regions)
Specifying custom ShellControl doesn't require changes to navigation
> fix: Navigation issue when using ShellControl

- src/Uno.Extensions.Navigation.UI/Navigator.cs
GitHub Issue (If applicable): #625
- Bugfix
An invalid thread exception raised when attempting to iterate over child regions and access their Navigator
Navigators are initialised on the UI thread before being accessed
- [ X ] Tested code with current [supported SDKs](../README.md#supported)
- [ N/A ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ N/A ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ N/A ] [Wasm UI …
> fix: Make sure navigators are created on UI thread before being referenced (eg indirect by the Region.GetRoute() extension method)

- samples/Playground/Playground.Shared/Services/NeedsADispatcherService.cs
- src/Uno.Extensions.Authentication.Msal/MsalAuthenticationProvider.cs
- src/Uno.Extensions.Core/DispatcherExtensions.cs
- src/Uno.Extensions.Core/IDispatcher.cs
- src/Uno.Extensions.Navigation.UI/Dispatcher.cs
- src/Uno.Extensions.Navigation.UI/Navigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs
- src/Uno.Extensions.Navigation.UI/Navigators/SelectorNavigator.cs
docs: Add XML doc for IDispatcher
> docs: Add XML doc for IDispatcher

- doc/Overview/Reactive/concept.md
> Fix spelling

- src/Uno.Extensions.Authentication/TokenCache.cs
- Bugfix
On logout tokens aren't being deleted
Updated persistence logic to ensure tokens are deleted
> fix: Updating token cache implementation

- src/Uno.Extensions.Authentication/Handlers/BaseAuthorizationHandler.cs
- src/Uno.Extensions.Authentication/Handlers/CookieHandler.cs
- src/Uno.Extensions.Authentication/Handlers/HeaderHandler.cs
- src/Uno.Extensions.Authentication/Uno.Extensions.Authentication.csproj
- src/Uno.Extensions.Http/CookieManager.cs
- src/Uno.Extensions.Http/ICookieManager.cs
- src/Uno.Extensions.Http/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Logging/HostBuilderExtensions.cs
- testing/TestHarness/TestHarness.UITest/AuthHttpUtilityTests.cs
- testing/TestHarness/TestHarness.UITest/TestHarness.UITest.csproj
GitHub Issue (If applicable): closes: #682 
- Bugfix
The native platform cookie containers are not being cleared when there are no tokens to set on the request
The native platform cookie containers are cleared and then any tokens are applied manually to the http request
> fix: Adding Cookie Manager to help clear cookies

- src/Uno.Extensions.Reactive/Collections/Facades/Differential/ResetNode.T.cs
fix(feeds): Fix possible OutOfRangeException (causes failure on CI)
> fix(feeds): Fix possible OutOfRangeException (causes failure on CI)

- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Axis.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Changed.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Data.T.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Data.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Error.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/ItemsConstraint.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Pagination.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Progress.cs
- src/Uno.Extensions.Reactive.Testing/ConstraintParts/Refreshed.cs
- src/Uno.Extensions.Reactive.Testing/Fluent/FluentAssertionExtensions.cs
- src/Uno.Extensions.Reactive.Testing/Fluent/MessageAssertions.cs
- src/Uno.Extensions.Reactive.Testing/Fluent/MessageRecorderAssertions.cs
- src/Uno.Extensions.Reactive.Testing/Validators/AxisConstraint.cs
- src/Uno.Extensions.Reactive.Testing/Validators/EntryValidator.cs
- src/Uno.Extensions.Reactive.Testing/Validators/RecorderValidator.cs
Add ability to easily write test for custom axis
No easy way to test custom axis values.
🙃
> feat(feeds): Add ability to easily write test for custom axis

- src/Uno.Extensions.Reactive.Generator/Bindables/BindableGenerationContext.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/Inputs/CommandInput.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.CommandConfigGenerator.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.CommandParameter.cs
- src/Uno.Extensions.Reactive.Generator/Bindables/MappedMembers/CommandFromMethod.cs
- src/Uno.Extensions.Reactive.Generator/NS.cs
- src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs
- src/Uno.Extensions.Reactive.UI/Config/ImplicitCommandsAttribute.cs
- src/Uno.Extensions.Reactive.UI/Config/ImplicitFeedCommandParametersAttribute.cs
- src/Uno.Extensions.Reactive.UI/GlobalUsings.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/AsyncCommand.SubCommand.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/AsyncCommand.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/Command.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CommandAttribute.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CommandBuilder.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CommandConfig.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CommandParametersCoercingStrategy.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/ExecutionCompletedEventArgs.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/ExecutionStartedEventArgs.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/FeedParameterAttribute.cs
- src/Uno.Extensions.Reactive.UI/Utils/ButtonExtensions.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/EventManager.cs
* feat: Add support of ListFeed as command parameter
* fix: CanExecute returning false due to casting issue
* chore: Update namespaces
> Misc fixes for commands

- src/Uno.Extensions.Reactive.Testing/Validators/RecorderValidator.cs
- src/Uno.Extensions.Reactive.Tests/Commands/Given_AsyncCommand.cs
- src/Uno.Extensions.Reactive.Tests/Commands/Given_CompositeCommand.cs
- src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Bindable.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/BindableCollection.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/AsyncCommand.SubCommand.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Commands/CompositeAsyncCommand.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/DispactherHelper.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/DispatcherLocal.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/EventManager.THandler.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/EventManager.cs
> feat: Add CompositeAsyncCommand

- src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs
- src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationSettings.cs
- src/Uno.Extensions.Authentication.UI/WebAuthenticationBuilderExtensions.cs
- Feature
IdTokenKey and OtherTokenKeys could be defined to be extracted automatically during authentication
Removed IdTokenKey and OtherTokenKeys properties/build methods to simplify API
PostLogin has been updated to include the redirect uri - this allows for manual extraction of anything that's not an access or refresh token
> feat: Removing IdToken and OtherTokens

- src/Uno.Extensions.Core/_Compat/DynamicallyAccessedMemberTypes.cs
- src/Uno.Extensions.Core/_Compat/DynamicallyAccessedMembersAttribute.cs
- src/Uno.Extensions.Reactive.Generator/Uno.Extensions.Reactive.Generator.csproj
- src/Uno.Extensions.Reactive.Tests/Utils/Uno.Core/Threading/AsyncLockFixture.cs
- src/Uno.Extensions.Reactive.UI/Utils/ButtonExtensions.cs
- src/Uno.Extensions.Reactive/Operators/ListFeedToFeedAdapter.cs
- src/Uno.Extensions.Reactive/Operators/StateForEach.cs
- src/Uno.Extensions.Reactive/Operators/UpdateFeed.cs
Misc code cleanup, no behavior nor public API change
> chore(feeds): Misc code cleanup

- src/Uno.Extensions.Authentication.UI/Web/WebAuthenticationProvider.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno.extensions/issues/749
- Bugfix
As per #749
Callbacks are invoked correctly
> fix: Calling overridden prepare logout methods for start and callbackuri

- src/Uno.Extensions.Reactive.Testing/ConstraintParts/ItemsConstraint.cs
- src/Uno.Extensions.Reactive.Tests/Utils/FeedUITests.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Bindable.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/BindablePropertyInfo.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/DataLayer.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/AsyncLazyDispatcherProvider.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/DispactherHelper.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/DispatcherLocal.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/DispatcherQueueProvider.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/IDispatcherInternal.cs
- src/Uno.Extensions.Reactive.UI/Utils/Dispatching/LazyDispatcherProvider.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/DispatcherInvocationList.Coalescing.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/DispatcherInvocationList.Queueing.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/DispatcherInvocationList.cs
- src/Uno.Extensions.Reactive.UI/Utils/Events/EventManager.THandler.cs
Improve ability to test Bindable<T>
There is no helper to test Bindable<T> and there is actually no UI thread while in tests.
🙃
> test(feeds): Improve ability to test Bindable<T>

- src/Uno.Extensions.Authentication/Handlers/CookieHandler.cs
- src/Uno.Extensions.Http/CookieManager.cs
- src/Uno.Extensions.Http/ICookieManager.cs
- src/Uno.Extensions.Http/Uno.Extensions.Http.csproj
- src/crosstargeting_override.props.sample
- testing/TestHarness/Directory.Build.props
- testing/TestHarness/TestHarness.Mobile/TestHarness.Mobile.csproj
- testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationHomeTestBackendViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/CustomAuthenticationTestBackendCookieHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Authentication/Custom/appsettings.testbackend.json
GitHub Issue (If applicable): #779
- Bugfix
Cookies aren't cleared
Cookies are cleared (actually set to expired) with each request
> fix: Correcting the application of cookies to requests

- src/Uno.Extensions.Reactive.UI.Tests/Given_FeedView.cs
- src/Uno.Extensions.Reactive.UI/View/FeedView.Loadable.cs
- src/Uno.Extensions.Reactive.UI/View/FeedViewState.cs
- src/Uno.Extensions.RuntimeTests.Core/UIHelper.cs
fixes https://github.com/unoplatform/uno.extensions/issues/699
Ensure that the `ILoadable` implementation of teh `FeedView` is working properly
No tests
🙃
> test(reactive): Make sure the ILoadable is implemented properly

- samples/Playground/Directory.Packages.props
- samples/Playground/Playground.Windows/Playground.Windows.csproj
- src/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- testing/TestHarness/Directory.Packages.props
- testing/TestHarness/TestHarness.Windows/TestHarness.Windows.csproj
Updating Themes, Toolkit and WinAppSdk to stable releases
> chore(deps): Updating themes, toolkit and win app sdk

- doc/Learn/Tutorials/Authentication/HowTo-Authentication.md
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/appsettings.json
GitHub Issue (If applicable): #1049 #1051 
- Bugfix
1049 - Appsettings includes LocalizationSettings section
1051 - Resw files don't have a build action set (ie None)
1049 - Appsettings includes LocalizationConfiguration section
1051 - Resw files are included with PRIResource build action
> fix: Localization issues with new template structure 

- src/Uno.Extensions.Reactive.Tests/Generator/Given_Methods_Then_GenerateCommands.cs
closes https://github.com/unoplatform/uno.chefs/issues/152
Test for fix made in https://github.com/unoplatform/uno.extensions/pull/998
No tests for this feature
Tests
> test(feeds): Add tests to validate multiple feed parameters only support

- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
GitHub Issue (If applicable): #1062 
It was replicated the changes on this PR https://github.com/unoplatform/uno/pull/10889 and the same scenario to macOS.
> feat: Update Windows build filter for Mac

- samples/Playground/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
- testing/TestHarness/Directory.Packages.props
closes: #1110
- Package Update
> chore(deps): Updating WinAppSdk version

- samples/Playground/Directory.Packages.props
- src/Directory.Packages.props
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
- testing/TestHarness/Directory.Packages.props
Package update to uno 4.7 Stable
> chore(deps): Updating to Uno 4.7

- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.nocpm.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.DataContracts/MyExtensionsApp.DataContracts.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
- Bugfix
Fixing various issues in the template
- Defaulting to sdk langversion for net7 (net6 option still requires langversion 10.0 for netstandard projects)
- Removing unnecessary "<None Remove" for appsettings
- Removing xaml update check for when using c# markup
> chore: Tidy up

- build/ci/.azure-pipelines.TemplateValidation.yml
- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Base/App.xaml
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.sln
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/GlobalUsings.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
- #1113
- Refactoring
Option to control Blank template vs Default is called Template Type
It is now referred to as Preset with options Blank / Recommended
> [Template] Updating TemplateType -> Preset

- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
closes: #1133
- Refactor
Duplicated logic between the Directory.Build.props and conditions in the Mobile.csproj
Instead of duplicating the logic we reuse the Properties defined in the Directory.Build.props in the Mobile.csproj
> [Template] reuse platform properties

- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Tests/MyExtensionsApp.Tests.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UITests/MyExtensionsApp.UITests.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
> [Template] update dependencies

- src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2NextPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2NextPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2NextViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/Sections/Blank2Page.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarHostInit.cs
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
- testing/TestHarness/TestHarness.Windows/TestHarness.Windows.csproj
> fix: Addressesing issue with nav route not being consumed when dependson specified

- src/Uno.Extensions.Navigation.UI/Navigators/FrameNavigator.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/ToDo/ToDoTaskListViewModel.cs
- Bugfix
Clicking on different task lists in todo app doesn't load correct data
Clicking on task lists opens the correct task list
> fix: Data navigation issue

- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/dotnetcli.host.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/ide.host.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp-vsmac.slnf
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/Program.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/Properties/launchSettings.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.sln
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
- #1113
- Refactor
This changes the way that platforms are selected in the template
Each platform has a boolean and can be disabled like: 
`dotnet new unoapp-extensions -android false -ios false`
Platforms is now a multi-select list. If you provide any value you must provide all of the values that you want like: 
`dotnet new unoapp-extensions -platforms android,ios,maccatalyst,windows,wasm`
> Use multiselect choice for platforms

- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Base/base.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Server/MyExtensionsApp.Server.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Tests/MyExtensionsApp.Tests.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.UITests/MyExtensionsApp.UITests.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.nocpm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.nocpm.csproj
n/a
- Updates Template Dependencies
> [Template] Package updates

- src/Uno.Extensions.Navigation.UI/Navigator.cs
GitHub Issue (If applicable): #Internal
- Bugfix
Invalid thread exception raised on WinUI when attempting to iterate over nested regions to determine current route.
The pairing of nested regions and their associated navigators is used to prevent threading exception when attempting to retrieve navigator from the service provider.
- [N/A] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [Internal] Associated with an issue (GitHub or internal)
> fix: Preventing thread exception when retrieving routes for nested regions

- samples/Playground/Directory.Packages.props
- src/Directory.Packages.props
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- testing/TestHarness/Directory.Packages.props
n/a
- Dependency Update
- Bugfix
Target Uno.WinUI 4.7.37
Target Uno.WinUI 4.7.44. Includes fix for buttons on WinUI
> Update Uno.WinUI 4.7.44

- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
> feat: Updating text for template

- samples/Playground/Directory.Packages.props
- samples/Playground/Playground.Windows/Playground.Windows.csproj
- src/Directory.Build.targets
- src/Directory.Packages.props
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Windows/Uno.Extensions.RuntimeTests.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Mobile/MyExtensionsApp.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Gtk/MyExtensionsApp.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.Linux.FrameBuffer/MyExtensionsApp.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Skia.WPF/MyExtensionsApp.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Wasm/MyExtensionsApp.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/MyExtensionsApp.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/AppResources.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
- testing/TestHarness/Directory.Packages.props
- testing/TestHarness/TestHarness.Windows/TestHarness.Windows.csproj
> fix: Removing explicit set for frameworkreference

- build/ci/scripts/wasm-uitest-run.sh
> ci: Produce binlog for wasm-uitest build

- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.Windows/Resources.lang-en-us.resw
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp/MyExtensionsApp.csproj
GitHub Issue (If applicable): #1205
- Bugfix
> fix: Class library corrections

- build/ci/.azure-pipelines.TemplateValidation.yml
- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
- closes #1237 
Template uses the shortname `unoapp-extensions`
Template uses the shortname `unoapp`
> Update template shortname

- doc/ExtensionsOverview.md
- doc/GettingStarted.md
- doc/Questions.md
- doc/toc.yml
GitHub Issue (If applicable): N/A
> docs: Improve order, add FAQ and welcome page

- src/Uno.Extensions.Navigation.UI/NavigationRequestExtensions.cs
- src/Uno.Extensions.Navigation.UI/Navigator.cs
- testing/TestHarness/TestHarness.Shared/App.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataCookbookDetailsPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataCookbookDetailsPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataCookbooksPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataCookbooksPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataEntityPickerFlyout.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataEntityPickerFlyout.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataRecipeDetailsPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataRecipeDetailsPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataRecipesPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataRecipesPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataService.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewDataViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewMainPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/NavigationView/NavigationViewMainPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj
- testing/TestHarness/TestHarness.Windows/Properties/PublishProfiles/win10-arm64.pubxml
- testing/TestHarness/TestHarness.Windows/Properties/PublishProfiles/win10-x64.pubxml
- testing/TestHarness/TestHarness.Windows/Properties/PublishProfiles/win10-x86.pubxml
- testing/TestHarness/TestHarness.Windows/Properties/launchSettings.json
- testing/TestHarness/TestHarness.Windows/TestHarness.Windows.csproj
- testing/TestHarness/TestHarness.sln
GitHub Issue (If applicable): #1243
- Bugfix
See #1243
Route is updated to include depedencies to make sure the route is correctly handled
> fix: Forcing navigation to dependent routes

- doc/Learn/Tutorials/Authentication/HowTo-Authentication.md
- doc/Learn/Tutorials/Logging/HowTo-InternalLogging.md
- doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseContentControl.md
- doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseNavigationView.md
- doc/Learn/Tutorials/Navigation/Advanced/HowTo-UsePanel.md
- doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseTabBar.md
- doc/Learn/Tutorials/Navigation/HowTo-DisplayItem.md
- doc/Learn/Tutorials/Navigation/HowTo-NavigateInCode.md
- doc/Learn/Tutorials/Navigation/HowTo-NavigateInXAML.md
- doc/Learn/Tutorials/Navigation/HowTo-SelectValue.md
- doc/Learn/Tutorials/Navigation/HowTo-ShowFlyout.md
- doc/Overview/Hosting/HostingOverview.md
- doc/Overview/Navigation/NavigationOverview.md
- doc/Overview/Reactive/feed.md
- doc/Overview/Reactive/in-apps.md
- doc/Overview/Reactive/listfeed.md
GitHub Issue (If applicable): #1169 
Closes #517 
- Fix broken configuration link
- Fix broken Feed page title
- Fix broken ListFeed page title
- Fix broken code block
- Make use of spaces consistent
> docs: assorted fixes for broken aspects

- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
See https://github.com/unoplatform/uno/pull/11688
> fix(templates): Specify `AndroidManifest` correctly so that design-time builds don't fail

- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.DataContracts/MyExtensionsApp.1.DataContracts.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Server/MyExtensionsApp.1.Server.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Tests/MyExtensionsApp.1.Tests.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.sln
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/Presentation/SecondPage.xaml
- n/a
- Bugfix
Back button image does not appear on the Second Page
Back button image appears with proper path
> back button resource path

- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
GitHub Issue (If applicable): close https://github.com/unoplatform/uno.extensions/issues/1236
> fix(dotnetnew): Add Uno.UITest reference in description

- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.UITests/MyExtensionsApp.1.UITests.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/MyExtensionsApp.1.csproj
> chore: update template dependencies

- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/AppResources.xaml
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/GlobalUsings.cs
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/MyExtensionsApp.1.csproj
n/a
- Refactoring
Toolkit packages are always included
Toolkit is excluded any time we are not using Dependency Injection
> [Template] Conditional Includes for Toolkit

- doc/Learn/Tutorials/Hosting/HowTo-HostingSetup.md
- doc/Overview/Authentication/AuthenticationOverview.md
- doc/Overview/Hosting/HostingOverview.md
GitHub Issue (If applicable): #1198 
> docs(hosting): update based on template

- src/Uno.Extensions.Templates/content/unoapp-extensions/.template.config/template.json
GitHub Issue (If applicable): #1291
> fix: Removing WPF and LinuxFB from default platforms

- samples/Playground/Directory.Packages.props
- src/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Packages.props
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Gtk/MyExtensionsApp.1.Skia.Gtk.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.Linux.FrameBuffer/MyExtensionsApp.1.Skia.Linux.FrameBuffer.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Skia.WPF/MyExtensionsApp.1.Skia.WPF.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Wasm/MyExtensionsApp.1.Wasm.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1.Windows/MyExtensionsApp.1.Windows.csproj
- src/Uno.Extensions.Templates/content/unoapp-extensions/MyExtensionsApp.1/MyExtensionsApp.1.csproj
- testing/TestHarness/Directory.Packages.props
related to https://github.com/unoplatform/uno.toolkit.ui/pull/517
> chore: Bump to uno.toolkit 2.5.5 for WinAppSDK fix

- doc/Overview/KeyEquality/concept.md
> docs: Fix class name

- src/Uno.Extensions.Templates/content/unoapp-extensions/Directory.Build.props
This diagnostic shouldn't be disabled. If there are violations, they should be properly addressed.
> fix: Enable CS1998 in template

- doc/Overview/DependencyInjection/DependencyInjectionOverview.md
GitHub Issue (If applicable): #1198 
> docs(DI): initial overview topic

- doc/Overview/Configuration/ConfigurationOverview.md
- doc/toc.yml
> docs(configuration): Update Overview for IApplicationBuilder

- build/ci/.azure-pipelines.Packages.yml
- src/Uno.Extensions.Reactive.Testing/FeedUITests.cs
- src/Uno.Extensions.Reactive.Testing/TestDispatcher.cs
- src/Uno.Extensions.Reactive.Tests/Core/Given_StateImpl.cs
- src/Uno.Extensions.Reactive.Tests/Presentation/Commands/Given_AsyncCommand.cs
- src/Uno.Extensions.Reactive/Core/Axes/TokenSetAwaiter.cs
- src/Uno.Extensions.Reactive/Core/ChangeCollection.cs
- src/Uno.Extensions.Reactive/Core/Internal/FeedSubscription.cs
- src/Uno.Extensions.Reactive/Core/Internal/StateImpl.cs
- src/Uno.Extensions.Reactive/Core/Internal/StateStore.cs
- src/Uno.Extensions.Reactive/Core/ListFeed.T.cs
- src/Uno.Extensions.Reactive/Core/ListState.cs
- src/Uno.Extensions.Reactive/Presentation/Commands/AsyncCommand.SubCommand.cs
- src/Uno.Extensions.Reactive/Sources/AsyncFeed.cs
- src/Uno.Extensions.Reactive/Utils/AsyncEnumerables/AsyncEnumerableSubject.cs
- src/Uno.Extensions.Reactive/Utils/AsyncEnumerables/ReplayOneAsyncEnumerable.cs
- src/Uno.Extensions.Reactive/Utils/Events/DispatcherInvocationList.cs
ci: Fix tests not running on CI
> ci: Fix tests not running on CI

- src/Uno.Extensions.Reactive.Tests/Utils/Uno.Core/Threading/AsyncLockFixture.cs
Disable tests that are causing the CI to crash
> test: Disable flaky test on CI

- doc/Learn/Tutorials/Navigation/Advanced/HowTo-UsePanel.md
GitHub Issue (If applicable): #1169 
> docs(AdvNav): Panel tutorial

- doc/Learn/Tutorials/Navigation/Advanced/HowTo-UseNavigationView.md
GitHub Issue (If applicable): #1169 
> docs(AdvNav): NavigationView tutorial

- doc/Overview/Mvux/ListFeeds.md
- doc/toc.yml
> docs(mvux): Add List-Feed docs

- doc/Overview/Mvux/ListStates.md
- doc/toc.yml
PR Type
Documentation content changes
This branch is based on another one that has not yet been pushed, as such it's **blocked by #1347**.
> docs(mvux): Add ListStates.md page

- src/Directory.Build.props
- src/Directory.Build.targets
- src/Directory.UnoMetadata.targets
- Feature
Package meta data in csproj
Meta data (including icon downloader) in targets file
> feat: Adding metadata targets file

- doc/README.md
- Project automation
Related: https://github.com/unoplatform/uno/pull/12087
> docs: update information about testing docs

- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Data/BranchStrategy.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/NullCollectionViewGroup.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/NullObservableVector.cs
- src/Uno.Extensions.Reactive.UI/Presentation/Bindings/Collections/Views/MapView.cs
- src/Uno.Extensions.Reactive.UI/Utils/SourceContextHelper.cs
- src/Uno.Extensions.Reactive/Core/ContextRequests/IRequestSource.cs
> fix(feeds): Miscs fixes for feeds

- doc/Learn/Tutorials/Authentication/HowTo-Authentication.md
- doc/Learn/Tutorials/Authentication/HowTo-Cookies.md
- doc/toc.yml
GitHub Issue (If applicable): #1416 
Closes #1416
> docs(auth): Authorize with cookies tutorial

- src/Uno.Extensions.Localization.UI/LinkerDefinition.UI.xml
- src/Uno.Extensions.Localization.UI/LinkerDefinition.WinUI.xml
- src/Uno.Extensions.Localization.UI/Uno.Extensions.Localization.UI.csproj
- src/Uno.Extensions.Localization.UI/Uno.Extensions.Localization.WinUI.csproj
- src/Uno.Extensions.Localization.UI/common.props
GitHub Issue (If applicable): #1473
- Bugfix
See issue
Localization works because correct types are added to linker definition
> fix: Linker correction for localization

- doc/Overview/Localization/LocalizationOverview.md
> docs(localization): Update for IApplicationBuilder

- doc/Overview/Logging/LoggingOverview.md
> docs(logging): Update for IApplicationBuilder

- doc/Overview/Serialization/SerializationOverview.md
> docs(serialization): Update for IApplicationBuilder

- src/Uno.Extensions.Toolkit.UI/GlobalUsings.cs
- src/Uno.Extensions.Toolkit.UI/HostBuilderExtensions.cs
- src/Uno.Extensions.Toolkit.UI/ThemeService.cs
- src/Uno.Extensions.Toolkit.UI/UIElementExtensions.cs
- src/Uno.Extensions.Toolkit.UI/WindowExtensions.cs
- src/Uno.Extensions.Toolkit.UI/common.props
- src/Uno.Extensions.Toolkit/DesiredTheme.cs
- src/Uno.Extensions.Toolkit/IThemeService.cs
- src/Uno.Extensions.Toolkit/Uno.Extensions.Toolkit.csproj
- src/Uno.Extensions.Validation.Fluent/FluentValidator.cs
- src/Uno.Extensions.Validation.Fluent/GlobalUsings.cs
- src/Uno.Extensions.Validation.Fluent/Uno.Extensions.Validation.Fluent.csproj
- src/Uno.Extensions.Validation.Fluent/ValidationBuilderExtensions.cs
- src/Uno.Extensions.Validation.Fluent/build/Package.targets
- src/Uno.Extensions.Validation/GlobalUsings.cs
- src/Uno.Extensions.Validation/HostBuilderExtensions.cs
- src/Uno.Extensions.Validation/IValidationBuilder.cs
- src/Uno.Extensions.Validation/IValidator.cs
- src/Uno.Extensions.Validation/IValidatorTypedInstance.cs
- src/Uno.Extensions.Validation/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Validation/Uno.Extensions.Validation.csproj
- src/Uno.Extensions.Validation/ValidationBuilder.cs
- src/Uno.Extensions.Validation/ValidatorTypedInstance.cs
GitHub Issue (If applicable): #1516 
Missing xml docs
Validation xml docs
Validation.Fluent xml docs
Toolkit xml docs
Toolkit.UI xml docs
- [ N/A ] Tested code with current [supported SDKs](../README.md#supported)
- [ X ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ N/A  ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [  N/A ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) …
> chore(docs): Documenting validation apis

- doc/Learn/Tutorials/Configuration/HowTo-WritableConfiguration.md
GitHub Issue (If applicable): #1470 
> docs: Writable configuration tutorial

- doc/Overview/Mvux/Advanced/InspectGeneratedCode.md
- doc/Overview/Mvux/Advanced/Pagination.md
- doc/Overview/Mvux/FeedView.md
- doc/Overview/Mvux/Feeds.md
- doc/Overview/Mvux/ListFeeds.md
- doc/Overview/Mvux/Overview.md
- doc/Overview/Mvux/States.md
> docs: Review

- .github/workflows/azure-static-app.yml
Warnings about Node.js 12
Update the GitHub Actions we use to versions that use Node.js 16. See https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> ci: Address Node.js 12 warnings

- doc/Overview/Mvux/Advanced/Selection.md
- doc/Overview/Mvux/ListStates.md
- Contains **NO** breaking changes
Syncs between the List-State page and Selection page
> docs(mvux): Review MVUX selection

- doc/toc.yml
Documentation content changes - this PR removes a duplicate toc section.
> docs: Remove duplicate toc items

- doc/Overview/Mvux/Feeds.md
- doc/Overview/Mvux/ListFeeds.md
- doc/Overview/Mvux/States.md
Related: #1562, #1559
This PR adds docs for the following methods:
- Empty
- Value
- ForEachAsync
- FromFeed
- AsListFeed
- AsFeed
- Set
> [MVUX] Docs for more operators

- doc/Overview/Mvux/Advanced/Commands.md
- doc/Overview/Mvux/Advanced/Selection.md
> [MVUX] Fix xref links and internal references

- doc/Questions.md
> docs: fix misplaced hyperlink

- doc/Overview/Mvux/FeedView.md
- Project automation
xref was missing from FeedView.md page.
> docs(mvux): Added xref uid to FeedView

- src/Uno.Extensions.Navigation.Generators/ForceBindingsUpdateGenTool_1.cs
The generated code has a compile-time error.
Note that I'm not using global usings.
> fix: Fix compile error in force bindings generator

- build/ci/.azure-pipelines.yml
- build/ci/gitversion.yml
Bumping to 3.0 with breaking change on xamarin removal
> ci: Adjust for legacy branch

- .github/workflows/conventional-commits.yml
> ci: Fix conventional commits not being run

- src/Uno.Extensions.Core.Generators/PropertySelector/PropertySelectorCandidate.cs
- src/Uno.Extensions.Core.Generators/PropertySelectorGenerator.cs
- src/Uno.Extensions.Core.Tests/Utils/GenerationTestHelper.cs
> perf: Alternative incremental implementation

- samples/MauiEmbedding/Directory.Packages.props
- samples/MauiEmbedding/MauiEmbedding.Skia.Gtk/Program.cs
- samples/Playground/Directory.Packages.props
- samples/Playground/Playground.Skia.Gtk/Program.cs
- samples/Playground/Playground.Skia.Wpf.Host/MainWindow.xaml.cs
- src/Directory.Packages.props
- src/Uno.Extensions.Navigation.UI.Markup/Uno.Extensions.Navigation.WinUI.Markup.csproj
- src/Uno.Extensions.Reactive.UI.Markup/Uno.Extensions.Reactive.WinUI.Markup.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Program.cs
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/MainWindow.xaml.cs
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
- testing/TestHarness/Directory.Packages.props
- testing/TestHarness/TestHarness.Legacy.Skia.Gtk/Program.cs
- testing/TestHarness/TestHarness.Legacy.Skia.WPF.Host/MainWindow.xaml.cs
- testing/TestHarness/TestHarness.Skia.Gtk/Program.cs
- testing/TestHarness/TestHarness.Skia.WPF.Host/MainWindow.xaml.cs
> build: Add explicit dependency to fix canaries

- doc/Overview/Mvux/Advanced/Messaging.md
Closes #1568.
Related: https://github.com/unoplatform/Uno.Samples/pull/382
This adds documentation on `Uno.Extensions.Reactive.Messaging`.
> docs(mvux): Messaging

- src/Directory.Packages.props
- testing/TestHarness/Directory.Packages.props
GitHub Issue (If applicable): closes: #1673
- Bugfix
Build error (see #1673)
No build error
- [N/A] Tested code with current [supported SDKs](../README.md#supported)
> chore(deps): Bump Microsoft.Identity.Client version to ensure build works

- src/Uno.Extensions.Core.Generators/PropertySelectorGenerator.cs
GitHub Issue (If applicable): closes #1755
> fix: Fix thread-safety of PropertySelectorGenerator

- src/Uno.Extensions.Hosting.UI/HostBuilder.cs
- src/Uno.Extensions.Hosting.UI/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Hosting.UI/UnoHost.cs
- src/Uno.Extensions.Hosting/BaseBuilder.cs
- src/Uno.Extensions.Hosting/HostBuilderExtensions.cs
- src/Uno.Extensions.Hosting/HostConfiguration.cs
- src/Uno.Extensions.Hosting/HostingConstants.cs
- src/Uno.Extensions.Hosting/IBuilder.cs
- src/Uno.Extensions.Hosting/IHasAddressBar.cs
- src/Uno.Extensions.Hosting/IStartupService.cs
GitHub Issue (If applicable): #1724
Closes #1724
> chore(docs): Documenting hosting apis

- src/Uno.Extensions.Serialization.Http/StreamSerializerToResponseContentDeserializer.cs
- src/Uno.Extensions.Serialization.Refit/SerializerToContentSerializerAdapter.cs
- src/Uno.Extensions.Serialization/HostBuilderExtensions.cs
- src/Uno.Extensions.Serialization/ISerializer.cs
- src/Uno.Extensions.Serialization/SerializerExtensions.cs
- src/Uno.Extensions.Serialization/ServiceCollectionExtensions.cs
- src/Uno.Extensions.Serialization/SystemTextJsonGeneratedSerializer.cs
- src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs
GitHub Issue (If applicable): #1726 
Closing #1726 
> chore(docs): Documenting serialization apis

- src/Uno.Extensions.Authentication.MSAL/HostBuilderExtensions.cs
- src/Uno.Extensions.Authentication.MSAL/IMsalAuthenticationBuilder.cs
- src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationBuilderExtensions.cs
- src/Uno.Extensions.Authentication.Oidc/HostBuilderExtensions.cs
- src/Uno.Extensions.Authentication.Oidc/IOidcAuthenticationBuilder.cs
- src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationBuilderExtensions.cs
- src/Uno.Extensions.Authentication.UI/HostBuilderExtensions.cs
- src/Uno.Extensions.Authentication.UI/Web/IWebAuthenticationBuilder.cs
- src/Uno.Extensions.Authentication.UI/WebAuthenticationBuilderExtensions.cs
- src/Uno.Extensions.Authentication/AuthenticationServiceExtensions.cs
- src/Uno.Extensions.Authentication/BaseAuthenticationProvider.cs
- src/Uno.Extensions.Authentication/Custom/ICustomAuthenticationBuilder.cs
- src/Uno.Extensions.Authentication/CustomAuthenticationBuilderExtensions.cs
- src/Uno.Extensions.Authentication/HandlerBuilderExtensions.cs
- src/Uno.Extensions.Authentication/Handlers/IHandlerBuilder.cs
- src/Uno.Extensions.Authentication/Headers.cs
- src/Uno.Extensions.Authentication/HostBuilderExtensions.cs
- src/Uno.Extensions.Authentication/IAuthenticationBuilder.cs
- src/Uno.Extensions.Authentication/IAuthenticationService.cs
- src/Uno.Extensions.Authentication/ITokenCache.cs
- src/Uno.Extensions.Authentication/TokenCacheExtensions.cs
GitHub Issue (If applicable): #1727
Closing #1727
> chore(docs): Documenting auth apis

- src/Uno.Extensions.Core/Option.cs
- src/Uno.Extensions.Core/OptionEqualityComparer.cs
- src/Uno.Extensions.Reactive.Tests/Core/Given_StateImpl.cs
- src/Uno.Extensions.Reactive/Core/Axes/DataAxis.cs
- src/Uno.Extensions.Reactive/Core/ISignal.T.cs
- src/Uno.Extensions.Reactive/Core/Internal/FeedSubscription.cs
- src/Uno.Extensions.Reactive/Core/Internal/IStateStore.cs
- src/Uno.Extensions.Reactive/Core/Internal/SourceContext.cs
- src/Uno.Extensions.Reactive/Core/Internal/StateImpl.cs
- src/Uno.Extensions.Reactive/Core/Internal/StateStore.None.cs
- src/Uno.Extensions.Reactive/Core/Internal/StateStore.cs
- src/Uno.Extensions.Reactive/Core/State.Extensions.cs
- src/Uno.Extensions.Reactive/Operators/ListFeedSelection.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/Dependencies/Feed/FeedDependency.T.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/DynamicFeed.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/ExecuteRequest.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/FeedExecution.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/FeedExecutionResult.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/FeedSession.T.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/FeedSession.cs
- src/Uno.Extensions.Reactive/Sources/Dynamic/IDependency.cs
- src/Uno.Extensions.Reactive/Utils/FeedUIHelper.cs
linked to https://github.com/unoplatform/uno.extensions/issues/1674
Miscs prep work for HR 4 MVUX
> chore(mvux): Miscs prep work for HR 4 MVUX

- samples/MauiEmbedding/Directory.Packages.props
Dependency on pre-release version of skiasharp
Update to latest stable skiasharp (2.88.5)
> chore(deps): Update skiasharp

- doc/Overview/Maui/ThirdParty-DevExpress.md
- doc/Overview/Maui/ThirdParty-EsriMaps.md
- doc/Overview/Maui/ThirdParty-GrapeCity.md
- doc/Overview/Maui/ThirdParty-GrialKit.md
- doc/Overview/Maui/ThirdParty-MauiCommunityToolkit.md
- doc/Overview/Maui/ThirdParty-Synfusion.md
- doc/Overview/Maui/ThirdParty-Telerik.md
- doc/toc.yml
> Added docs to MauiEmbbeding samples

- src/Uno.Extensions.Configuration/ConfigBuilderExtensions.cs
- src/Uno.Extensions.Configuration/ConfigurationBinder.cs
- src/Uno.Extensions.Configuration/ConfigurationBuilderExtensions.cs
- src/Uno.Extensions.Configuration/EmbeddedAppConfigurationFile.cs
- src/Uno.Extensions.Configuration/HostBuilderExtensions.cs
- src/Uno.Extensions.Configuration/IConfigBuilder.cs
- src/Uno.Extensions.Configuration/IWritableOptions.cs
- src/Uno.Extensions.Configuration/ServiceCollectionExtensions.cs
- testing/TestHarness/TestHarness.Shared/BaseHostInitialization.cs
GitHub Issue (If applicable): #1531 
Closing #1531 
This PR contains a breaking change (ed6f27eb902667b9945c07708be6aaa0182674f0) which I'm seeking approval for.
> chore(docs): Documenting configuration apis

- src/Uno.Extensions.Localization.UI/HostBuilderExtensions.cs
- src/Uno.Extensions.Localization.UI/LocalizationConfiguration.cs
- src/Uno.Extensions.Localization.UI/LocalizationService.cs
- src/Uno.Extensions.Localization.UI/LocalizationSettings.cs
- src/Uno.Extensions.Localization.UI/LocalizationSettingsExtensions.cs
- src/Uno.Extensions.Localization.UI/ResourceLoaderStringLocalizer.cs
- src/Uno.Extensions.Localization/ILocalizationService.cs
- testing/TestHarness/TestHarness.Shared/App.xaml.cs
GitHub Issue (If applicable): #1725
Closes #1725
> chore(docs): Documenting l10n apis

- src/Directory.Packages.props
- src/Uno.Extensions.Navigation.UI.Markup/Uno.Extensions.Navigation.WinUI.Markup.csproj
- n/a
- Dependencies
Updates Markup packages
> chore: updating Markup packages

- src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationProvider.cs
- src/Uno.Extensions.Authentication.Oidc/OidcAuthenticationSettings.cs
GitHub Issue (If applicable): #1887
Changed access specifiers for classes WebAuthenticatorBrowser, OidcAuthenticationProvider, OidcAuthenticationSettings from internal to public 
> Made 'WebAuthenticatorBrowser' public to reuse it (in our case for Firebase authentication)

- src/Directory.Build.props
- src/Uno.Extensions-packageonly.slnf
Adding use of hardlinks to improve build performance
And dropping tests project for packaging build
> chore: Adding properties to make build faster

- samples/MauiEmbedding/Directory.Packages.props
- samples/Playground/Directory.Packages.props
- src/Directory.Packages.props
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Mobile/Uno.Extensions.RuntimeTests.Mobile.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Gtk/Uno.Extensions.RuntimeTests.Skia.Gtk.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Skia.Wpf/Uno.Extensions.RuntimeTests.Skia.Wpf.csproj
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Wasm/Uno.Extensions.RuntimeTests.Wasm.csproj
- testing/TestHarness/Directory.Packages.props
- testing/TestHarness/TestHarness.Legacy.Skia.Linux.FrameBuffer/Program.cs
- testing/TestHarness/TestHarness.Skia.Linux.FrameBuffer/Program.cs
> chore: Adjust test project for FrameBufferHost breaking change

- src/Uno.Extensions.Navigation.UI/Navigator.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHomePage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceSettingsPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceSettingsPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceSettingsViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Commerce/CommerceShellControlHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/TabBar/TabBarHomePage.xaml
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.shproj
- Bugfix
From within a tab, attempting to navigate to a page at the level of the parent (in route map) doesn't work
Checks added to make sure navigation requests check parent route (if exists)
- [N/A] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [N/A] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [N/A] Associated with an issue (GitHub or internal)
Internal Issue (If …
> feat: Adding settings page

- doc/Reference/Markup/GettingStarted.md
> docs: Fix broken WinUI Markup link on GettingStarted.md

- doc/Overview/Mvux/Tutorials/HowTo-SimpleFeed.md
GitHub Issue (If applicable): closes [#2018](https://github.com/unoplatform/uno.extensions/issues/2018)
The proposed interface and implementation in the tutorial don't match
Update the interface name to match the service implementation and model classes
> docs: Update HowTo-SimpleFeed.md method name

- src/Uno.Extensions-packageonly.slnf
- src/Uno.Extensions.Maui.WinUI.Markup/Uno.Extensions.Maui.WinUI.Markup.csproj
- src/Uno.Extensions.Navigation.UI/MappedRouteResolver.cs
- src/Uno.Extensions.Navigation.UI/Navigator.cs
- src/Uno.Extensions.Navigation.UI/NavigatorExtensions.cs
- src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs
- src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
- testing/TestHarness/Directory.Packages.props
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFivePage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFivePage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFiveViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFourPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveFourPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveMainPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOnePage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOnePage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveOneViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveSixPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveSixPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveSixViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreePage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreePage.xaml.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveThreeViewModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveTwoPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Reactive/ReactiveTwoPage.xaml.cs
- testing/TestHarness/TestHarness.Shared/TestHarness.Shared.projitems
- testing/TestHarness/TestHarness.UITest/Constants.cs
- testing/TestHarness/TestHarness.UITest/Ext/Navigation/Reactive/Given_Reactive.cs
Backport of https://github.com/unoplatform/uno.extensions/pull/2031
> fix: Navigation to implicit route clears backstack (backport)

- doc/Overview/Markup/Binding101.md
This some small fixes on binding 101 docs
> Adjusted code and add comment for clarity

- doc/Questions.md
GitHub Issue (If applicable): closes N/A
- Bugfix
[Teams](https://teams.microsoft.com/l/message/19:787ad1de1af24252b9041bcbd4ec1ca3@thread.tacv2/1701463587295?tenantId=a297d6c0-b635-41a3-b1e3-558efe71e413&groupId=f55cdec8-036b-4efa-8e1a-c4129ba9bf12&parentMessageId=1701463587295&teamName=Uno%20Platform&channelName=Docs%20and%20Getting%20Started&createdTime=1701463587295)
> docs: Overall FAQ and searchability Improvements

- doc/Overview/Markup/Appendix/AccessingControlInstance.md
- doc/Overview/Markup/GeneratingExtensions.md
- doc/Overview/Markup/Overview.md
- doc/toc.yml
> Updating TOC and adding Assign docs

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/documentation-issue.md
- .github/ISSUE_TEMPLATE/documentation-request.md
> chore: update issues templates

- doc/Learn/Maui/MauiOverview.md
Docs for MAUI Embedding setup missing step for changing application type on XAML code
Docs for MAUI Embedding now include additional instructions for changing application type on XAML code
> docs: Add instructions for MAUI embedding

- src/Uno.Extensions.Reactive/Core/ListState.Extensions.cs
Add UpdateAsync helper on ListState that accepts an item : IKeyEquatable with automatic comparison.
No helper
🙃
> feat: Add UpdateAsync helper on ListState

- build/ci/.azure-pipelines.yml
- src/Uno.Extensions.Navigation.UI/RouteExtensions.cs
- src/Uno.Extensions.Navigation.UI/RouteResolver.cs
- src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/PageNavigation/PageNavigationRegisterHostInit.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2149
- Bugfix
See issue
DependsOn links are correctly resolved
> fix: Correcting lookup of route dependencies

- doc/Learn/Mvux/toc.yml
> docs: Fix MVUX case in toc

- doc/Learn/Mvux/ListFeeds.md
- doc/Learn/Mvux/ListStates.md
- doc/Learn/Mvux/States.md
- doc/Learn/Mvux/Tutorials/HowTo-SimpleFeed.md
> docs: Misc docs fixes

- doc/Learn/Mvux/Advanced/InspectGeneratedCode.md
- doc/Learn/Mvux/Advanced/Selection.md
- doc/Learn/Mvux/Tutorials/HowTo-ListFeed.md
- doc/Learn/Mvux/Tutorials/HowTo-PushListFeed.md
- doc/Learn/Mvux/Tutorials/HowTo-SimpleState.md
There are multiple minor issues in the docs which should be fixed. 
> docs: Misc docs fixes pt. 2

- build/ci/.azure-pipelines.UITests.Wasm.yml
- build/ci/scripts/wasm-uitest-run.sh
Bumps chrome to align with the one uno is using for UI tests.
> ci: Bump chromium

- doc/Learn/Markup/Overview.md
`.Source("ms-appx:///Counter/Assets/logo.png"),`
`.Source("ms-appx:///Assets/logo.png"),`
> docs: Adjust image path for Single Project

- doc/Learn/Mvux/FeedView.md
> docs: FeedView templates

- doc/Learn/Storage/HowTo-RequiredEntitlements.md
- doc/Learn/Storage/StorageOverview.md
- doc/Learn/Storage/toc.yml
Fix Uno.Extensions Storage documentation links
> docs: Fix Uno.Extensions Storage documentation links and adjust content

- doc/Learn/Markup/Overview.md
Update C# Markup Overview.md to add missing links
> docs: Update C# Markup Overview.md to add missing links

- doc/Learn/Markup/Resources.md
- reported by #2268
- Bugfix
Documentation shows an invalid code sample for creating ThemeResources
Documentation has been fixed to reflect the proper API
> Fix Resource sample

- doc/Learn/Markup/toc.yml
- doc/toc.yml
GitHub Issue (If applicable): closes #2286 
> Chore: Updated the TOC to include SourceUsage

- doc/Learn/Navigation/Advanced/HowTo-UseNavigationView.md
GitHub Issue (If applicable): closes #2290
> docs(NavigationView): Add note regarding Grid for navigation

- samples/MauiEmbedding/Directory.Packages.props
- samples/Playground/Directory.Packages.props
- src/Directory.Packages.props
- src/Uno.Extensions.RuntimeTests/Uno.Extensions.RuntimeTests.Windows/Uno.Extensions.RuntimeTests.Windows.csproj
- testing/TestHarness/Directory.Packages.props
Adjusts for net7.0 introduced method https://github.com/unoplatform/Uno.Core/pull/90
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2225
> chore: Update to uno.core 4.1.1

- doc/Learn/Mvux/States.md
> docs: Update doc to not use renamed operators

- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsFavoriteRecipesModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsFavoriteRecipesPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsHomeModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsHomePage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsLiveCookingModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsLiveCookingPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsRecipeDetailsModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsRecipeDetailsPage.xaml
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsSearchModel.cs
- testing/TestHarness/TestHarness.Shared/Ext/Navigation/Apps/Chefs/ChefsSearchPage.xaml
GitHub Issue (If applicable): https://github.com/unoplatform/uno.chefs/issues/1151
- Feature
Missing buttons for navigation
Added buttons for navigation
> fix: Added chefs navigation buttons

- samples/Playground/Directory.Packages.props
- src/Directory.Packages.props
- src/Uno.Extensions.Core.Generators/Common/GenTool/CodeGenToolExtensions.cs
- src/Uno.Extensions.Core.Generators/KeyEquality/KeyEqualityGenerationTool.cs
- src/Uno.Extensions.Navigation.Generators/ForceBindingsUpdateGenTool_1.cs
- src/Uno.Extensions.Navigation.Generators/ForceBindingsUpdateGenerationContext.cs
- testing/TestHarness/Directory.Packages.props
GitHub Issue (If applicable): closes #2378
> fix: Make sure generators use `global::`

- src/Uno.Extensions.Navigation.UI/ServiceProviderExtensions.cs
> fix: Calling activation before awaiting initial navigation

- doc/Reference/Reactive/rules.md
> docs: Fix typo

- doc/Learn/ThemeService/HowTo-UseThemeService.md
- doc/Learn/ThemeService/toc.yml
- doc/toc.yml
GitHub Issue (If applicable): closes #2294
> docs: use theme service

- doc/Learn/Navigation/HowTo-DefineRoutes.md
- doc/Learn/Navigation/toc.yml
GitHub Issue (If applicable): closes #2273
> docs: How To Define Routes

- src/Uno.Extensions.Authentication.MSAL/build/Package.targets
GitHub Issue (If applicable): closes #2346
> chore: Add target for MSAL when target is wasm

- src/Uno.Extensions.Authentication.MSAL/GlobalUsings.cs
- src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationBuilderExtensions.cs
- src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationSettings.cs
- src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.UI.csproj
- src/Uno.Extensions.Authentication.MSAL/Uno.Extensions.Authentication.MSAL.WinUI.csproj
- src/Uno.Extensions.Authentication.MSAL/build/Package.targets
- src/Uno.Extensions.Authentication.MSAL/common.props
- testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationHostInit.cs
- testing/TestHarness/TestHarness.Shared/Ext/Authentication/Msal/MsalAuthenticationMultiHostInit.cs
This is a backport of pull request #2489
> chore: backport msal fix

- doc/Learn/Navigation/HowTo-NavigateInXAML.md
GitHub Issue (If applicable): https://github.com/unoplatform/uno.extensions-private/issues/204
> docs: Sending data among view models using navigationview and regions

- src/Uno.Extensions.Reactive.Generator/Bindables/ViewModelGenerator_2.cs
- src/Uno.Extensions.Reactive.Tests/Generator/Given_RecordWithList_Then_GenerateListOfBindable.cs
GitHub Issue (If applicable): closes #2525
- Bugfix
> fix(mvux): name clashing between model and record class

- doc/Learn/Http/HowTo-EndpointOptions.md
- doc/Learn/Http/HowTo-Http.md
- doc/Learn/Http/HttpOverview.md
GitHub Issue (If applicable): https://github.com/unoplatform/private/issues/504
> chore: Fix old TestHarness links

- doc/Learn/Markup/HowTo-MarkupProjectToolkit.md
GitHub Issue (If applicable): closes #1664
> docs: Remove Extensions Toolkit packages references

- doc/Learn/Mvux/Tutorials/HowTo-ListFeed.md
> docs: Add example for ListFeed with parameter

- doc/Learn/Hosting/HostingOverview.md
- doc/Learn/Navigation/NavigationOverview.md
- doc/Learn/includes/getting-help.md
GitHub Issue (If applicable): closes #1606
Related PR: https://github.com/unoplatform/uno/pull/17291
https://github.com/unoplatform/uno/pull/17291 adds the UWP common issues. This PR adds a box to take users to common issues page.
> docs: Add Getting Help box

- src/Uno.Extensions.Authentication/HostBuilderExtensions.cs
- src/Uno.Extensions.Storage.UI/ServiceCollectionExtensions.cs
- testing/TestHarness/TestHarness/Platforms/WebAssembly/LinkerConfig.xml
GitHub Issue (If applicable): closes #2524
> fix: Properly annotate AddAuthentication so that it's linker friendly

- testing/TestHarness/Directory.Packages.props
fix for canaries that are failing due to package issues
> chore: Add PackageVersion for canaries

- doc/Learn/Markup/VisualStateManager.md
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.extensions/issues/2565
Missing important information on state triggers
Added with link to MS Docs
> docs: Note on `VisualStateGroup.StateTriggers` usage

- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsFavoriteRecipesPage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHomePage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHostInit.cs
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsLiveCookingPage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsRecipeDetailsPage.xaml
> chore: Add NavBar to chefs pages

- testing/TestHarness/TestHarness/TestHarness.csproj
- Bugfix
Example of file being used as EmbeddedResource https://github.com/unoplatform/uno.extensions/blob/eb7986bdc2ac2fa2a1fd255d35c02e084d582b2f/testing/TestHarness/TestHarness/Ext/Authentication/Msal/MsalAuthenticationSettingsHostInit.cs#L5-L6
appsettings.json files should be set as EmbeddedResource to be found and used.
> chore: Set appsettings file as EmbeddedResource

- src/Directory.Packages.props
GitHub Issue (If applicable): related to https://github.com/unoplatform/uno/issues/18840
> feat: `WinAppSdkBuildToolsVersion` can be bumped

- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsRootPage.xaml
> chore: Reset vm when navigating to Search

- doc/Learn/Mvux/reactive-migration.md
- doc/Learn/Mvux/toc.yml
> docs: update mvux upgrade title

- doc/Learn/Http/HowTo-Kiota.md
> docs: (kiota) fix typo

- src/Uno.Extensions.Logging/Uno.Extensions.Logging.WinUI.csproj
> fix: Include Logging.WebAssembly.Console on all targets

- src/Uno.Extensions.Navigation.UI/Navigators/PanelVisiblityNavigator.cs
> fix: add region routes for panel vis navigator on loaded

- doc/Learn/Http/HowTo-Kiota.md
> docs: kiota - spec file details

- doc/Learn/Http/toc.yml
Update Http toc.yml to fix the Kiota link
> docs: Update Http toc.yml to fix the Kiota link

- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHomeModel.cs
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsHomePage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsLoginModel.cs
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsProfilePage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsRootModel.cs
- testing/TestHarness/TestHarness/Ext/Navigation/Apps/Chefs/ChefsSearchModel.cs
> chore: Reflect chefs app on testharness

- src/Uno.Extensions.Navigation.UI/Navigator.cs
- testing/TestHarness/TestHarness.UITest/Ext/Navigation/AddressBar/Given_AddressBar.cs
- testing/TestHarness/TestHarness.UITest/Ext/Navigation/PageNavigation/Given_PageNavigation.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationJSImports.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationOnePage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationOneViewModel.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationRegisterHostInit.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationThreePage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationThreePage.xaml.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationThreeViewModel.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationTwoPage.xaml
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationTwoPage.xaml.cs
- testing/TestHarness/TestHarness/Ext/Navigation/PageNavigation/PageNavigationTwoViewModel.cs
GitHub Issue (If applicable): closes #2774
> fix: Add query param navigation with dependson

- .github/workflows/azure-static-app.yml
GitHub Issue (If applicable): 
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore: bump github ci upload artifact

- .gitignore
- build/ci/.azure-pipelines.yml
- build/ci/publish/publish-nuget-dev.yml
- build/ci/publish/publish-nuget-prod-dev.yml
- build/ci/publish/publish-nuget-prod.yml
- build/ci/stage-build-packages.yml
- build/ci/templates/nuget-publish-dev.yml
- build/ci/templates/nuget-publish-public.yml
> ci: move to yaml deployment stages

- doc/Learn/Mvux/faq.md
- doc/Learn/Mvux/toc.yml
> docs: add mvux faq
